/**
 * Advanced Dungeons & Dragons 2nd Edition
 * Monstrous Manual (1993) and the 15+ Monstrous Compendium appendices
 *
 * Covering: Forgotten Realms, Ravenloft, Planescape, Dark Sun,
 * Spelljammer, Dragonlance, Greyhawk, Kara-Tur, Al-Qadim, Mystara.
 */
import type { BestiaryEntry } from '../DnDKnowledge';

export const ADND2E_BESTIARY: BestiaryEntry[] = [
  // ═══════════════════════════════════════════════════════════
  //  MONSTROUS MANUAL (1993) — 600+ monsters, key picks
  // ═══════════════════════════════════════════════════════════
  {
    id: '2e_yuan_ti_abomination', name: 'Yuan-ti Abomination', type: 'monstrosity (yuan-ti)', size: 'Large', alignment: 'neutral evil',
    cr: 7, ac: 15, hp: '127 (15d10 + 45)', speed: '40 ft.',
    description: 'A serpentine horror — a humanoid torso on a massive snake tail, head flattened into a cobra\'s hood. Fangs drip venom.',
    lore: 'Yuan-ti are the serpent empire that ruled the jungles before the rise of men. Abominations are the purest and most powerful of their kind, commanding cults of lesser yuan-ti and human worshipers. They seek to resurrect their fallen god and reclaim the world.',
    tactics: 'Poison bite. Constriction with tail. Innate spellcasting. Commands yuan-ti and charmed humanoids.',
    habitat: 'Jungle ruins, serpent temples, sunken cities',
    abilities: ['Poison bite', 'Constrict', 'Innate spellcasting', 'Magic resistance'],
    languages: ['Abyssal', 'Common', 'Draconic', 'Yuan-ti'],
    senses: ['darkvision 60 ft.', 'passive Perception 15'],
  },
  {
    id: '2e_elder_brain', name: 'Elder Brain', type: 'aberration', size: 'Large', alignment: 'lawful evil',
    cr: 14, ac: 10, hp: '210 (20d10 + 100)', speed: '5 ft., swim 10 ft.',
    description: 'A colossal brain floating in a pool of psychic brine, its surface furrowed with the thoughts of an entire civilization.',
    lore: 'The elder brain is the nexus of every mind flayer colony, a gestalt of consumed minds fused into a single psionic entity. It coordinates the illithids telepathically across miles and contains the memories of billions of consumed brains. Its death shatters the colony.',
    tactics: 'Psionic blast. Mind blast at extreme range. Uses thralls and mind flayers as shields. Psychic link to all illithids.',
    habitat: 'Mind flayer colony brine pools, Underdark',
    abilities: ['Psionic blast', 'Mind link', 'Spell reflection', 'Psychic barrier', 'Legendary resistance'],
    languages: ['Deep Speech', 'Undercommon', 'telepathy 5 miles'],
    senses: ['blindsight 120 ft.', 'passive Perception 20'],
  },
  {
    id: '2e_greater_doppelganger', name: 'Greater Doppelganger', type: 'monstrosity (shapechanger)', size: 'Medium', alignment: 'neutral evil',
    cr: 5, ac: 15, hp: '75 (10d8 + 30)', speed: '30 ft.',
    description: 'An unremarkable-looking humanoid — except that you have seen its face on three different people today.',
    lore: 'Greater doppelgangers do not merely copy appearances — they consume personalities. After eating a victim\'s brain, they gain all their memories, mannerisms, and abilities. They can maintain multiple stolen personas and switch between them at will.',
    tactics: 'Infiltrates communities. Copies abilities of consumed victims. Psychic assault. Flees if exposed.',
    habitat: 'Cities, courts, anywhere with valuable identities',
    abilities: ['Shapechanger', 'Personality theft', 'Mind reading', 'Surprise attack'],
    languages: ['Common', 'any language of consumed victims'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },

  // ═══════════════════════════════════════════════════════════
  //  FORGOTTEN REALMS Appendices (MC3, MC11)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'fr_alhoon', name: 'Alhoon (Illithilich)', type: 'undead (illithid)', size: 'Medium', alignment: 'any evil',
    cr: 15, ac: 16, hp: '150 (20d8 + 60)', speed: '30 ft.',
    description: 'A mind flayer that has abandoned the elder brain for the path of lichdom — a desiccated illithid in arcane robes, psionic energy still crackling at its tentacles.',
    lore: 'Alhoons are mind flayers who chose arcane mastery over servitude to the elder brain, transforming themselves into undead liches. They are hunted and despised by normal illithids but feared for their combined psionic and arcane power. They build private domains in the darkest reaches.',
    tactics: 'Psionic blast plus wizard spellcasting. Lich paralyzing touch. Rejuvenation from phylactery.',
    habitat: 'Forgotten Realms Underdark, private demiplanes',
    abilities: ['Spellcasting (wizard)', 'Psionics', 'Paralyzing tentacles', 'Lich rejuvenation'],
    languages: ['Deep Speech', 'Undercommon', 'Common', 'telepathy 120 ft.'],
    senses: ['truesight 120 ft.', 'passive Perception 19'],
  },
  {
    id: 'fr_deep_dragon', name: 'Deep Dragon', type: 'dragon', size: 'Large', alignment: 'chaotic evil',
    cr: 8, ac: 17, hp: '147 (14d10 + 70)', speed: '40 ft., burrow 15 ft., fly 80 ft., swim 30 ft.',
    description: 'A serpentine dragon with scales the color of cave fungus — pale gray and violet — breathing corrosive gas that eats through stone.',
    lore: 'Deep dragons are the chromatic dragons of the Underdark, adapted for a world without light. They burrow through stone, breathe flesh-dissolving gas, and know the Underdark\'s secrets better than any save the drow. They are cunning traders of information and favors.',
    tactics: 'Corrosive gas breath (also works on stone). Burrows through walls. Amphibious. Psychological warfare.',
    habitat: 'Underdark caverns, underground rivers, drow trade routes',
    abilities: ['Corrosive gas breath', 'Burrow', 'Amphibious', 'Darkvision', 'Fly'],
    languages: ['Common', 'Draconic', 'Undercommon'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 17'],
  },
  {
    id: 'fr_dark_naga', name: 'Dark Naga', type: 'monstrosity', size: 'Large', alignment: 'lawful evil',
    cr: 8, ac: 15, hp: '75 (10d10 + 20)', speed: '40 ft.',
    description: 'A serpent with a disturbingly beautiful human face and a crown of lesser snakes writhing around its head.',
    lore: 'Dark nagas are the immortal guardians of forgotten temples and forbidden lore. They are schemers who weave century-spanning plots, using their charm to corrupt mortals. A dark naga never truly dies — it reincarnates days later unless a specific ritual is used.',
    tactics: 'Charm person at will. Venomous bite. Spellcasting. Retreats and reincarnates if killed.',
    habitat: 'Forgotten temples, ruins, hidden libraries',
    abilities: ['Charm (at will)', 'Venomous bite', 'Spellcasting', 'Reincarnation', 'Immortal'],
    languages: ['Abyssal', 'Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'fr_shade', name: 'Shade (Shadow Walker)', type: 'humanoid (shade)', size: 'Medium', alignment: 'any',
    cr: 5, ac: 15, hp: '66 (12d8 + 12)', speed: '30 ft.',
    description: 'A humanoid of shadow-stuff — dark gray skin, black hair, and a palpable aura of cold and shadow.',
    lore: 'Shades are the descendants of Netherese humans who fled into the Plane of Shadow to escape their empire\'s destruction. Centuries in shadow transformed them into beings of living darkness. They have returned to Faerun to rebuild their lost empire.',
    tactics: 'Shadow step for mobility. Shadow magic. Hard to hit in dim light. Controls shadows.',
    habitat: 'The Plane of Shadow, returned Netherese enclaves',
    abilities: ['Shadow step', 'Shadow magic', 'Light sensitivity', 'Shadow blend'],
    languages: ['Common', 'Netherese'],
    senses: ['darkvision 120 ft.', 'passive Perception 13'],
  },
  {
    id: 'fr_phylaskia', name: 'Phylaskia', type: 'undead', size: 'Medium', alignment: 'lawful evil',
    cr: 5, ac: 16, hp: '75 (10d8 + 30)', speed: '40 ft.',
    description: 'A silent, armored guardian with an empty helm, standing eternal vigil before a sealed door.',
    lore: 'Phylaskia are the undying sentinels of Mulhorand, created by the god-kings to guard the tombs of their divine children. They never speak, never sleep, and never stop guarding. Only the correct passwords or divine authority can pass them.',
    tactics: 'Detects alignment. Sacred smite against the unworthy. Fights in perfect silence. Bound to its post.',
    habitat: 'Mulhorandi tombs, sealed vaults, divine temples',
    abilities: ['Alignment detection', 'Sacred smite', 'Bound guardian', 'Silent sentinel'],
    languages: ['understands Mulhorandi'],
    senses: ['darkvision 60 ft.', 'passive Perception 15'],
  },

  // ═══════════════════════════════════════════════════════════
  //  DARK SUN Appendices (MC12, DSE2)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'ds_thri_kreen', name: 'Thri-Kreen (Mantis Warrior)', type: 'humanoid (thri-kreen)', size: 'Medium', alignment: 'chaotic neutral',
    cr: 1, ac: 15, hp: '33 (6d8 + 6)', speed: '40 ft.',
    description: 'A six-limbed insectoid with a mantis-like head, compound eyes, and chitin the color of the desert.',
    lore: 'Thri-kreen are the dominant intelligent race of the Athasian wastes — nomadic hunters who live for the chase. They do not sleep and have a short lifespan. They bond for life with clutch-mates and cannot comprehend the concept of lying.',
    tactics: 'Multiattack (four claws and bite). Leap attack. Poison in bite. Never sleeps — always alert.',
    habitat: 'Deserts of Athas, rocky wastes',
    abilities: ['Multiattack (four limbs)', 'Leap', 'Poison bite', 'Sleepless', 'Chatkcha throwing weapon'],
    languages: ['Thri-Kreen'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'ds_braxat', name: 'Braxat', type: 'humanoid (braxat)', size: 'Large', alignment: 'neutral evil',
    cr: 5, ac: 14, hp: '85 (10d10 + 30)', speed: '35 ft.',
    description: 'An armored, hunchbacked giant with a thick carapace and eyes that burn with psionic fire.',
    lore: 'Braxats are the cruel enforcers of the Athasian wastes, a race of slavers and mercenaries with natural psionic powers. Their armored shells turn aside most weapons. Their most feared ability is a cone of cold that erupts from their minds.',
    tactics: 'Psionic cold cone. Carapace armor. Telepathic threats. Enslaves the weak.',
    habitat: 'Athasian wastes, slaver strongholds',
    abilities: ['Psionic cold cone', 'Carapace armor', 'Telepathy'],
    languages: ['Braxat', 'telepathy 60 ft.'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'ds_silt_horror', name: 'Silt Horror', type: 'monstrosity', size: 'Huge', alignment: 'unaligned',
    cr: 7, ac: 16, hp: '126 (12d12 + 48)', speed: '5 ft., swim 30 ft.',
    description: 'A writhing mass of tentacles that churns the silt sea itself — something vast and hungry beneath the dust.',
    lore: 'Silt horrors are the apex predators of the Sea of Silt, an ocean of fine dust that covers much of Athas. They swim through silt like a squid through water, their tentacles erupting from the dust to drag victims beneath. Nothing survives a silt horror\'s grip.',
    tactics: 'Tentacles erupt from silt. Grapples and drags victims under the dust. Senses vibrations.',
    habitat: 'The Sea of Silt, Athas',
    abilities: ['Tentacle grapple', 'Drag under', 'Tremorsense', 'Silt swim'],
    languages: [],
    senses: ['tremorsense 120 ft.', 'passive Perception 10'],
  },
  {
    id: 'ds_gith_athas', name: 'Gith of Athas', type: 'humanoid (gith)', size: 'Medium', alignment: 'chaotic neutral',
    cr: 3, ac: 15, hp: '49 (9d8 + 9)', speed: '30 ft.',
    description: 'A lean, feral humanoid with gray skin and wild eyes, brandishing a jagged bone weapon.',
    lore: 'The gith of Athas are a divergent branch of the gith race, stranded on the dying world when their rebellion against the illithids failed. They have devolved into tribal scavengers, losing their psionic powers but gaining a fierce survival instinct.',
    tactics: 'Ambush in the wastes. Bone weapons. Ferocious pack tactics. Psionic vestiges.',
    habitat: 'Athasian wastes, ruins, badlands',
    abilities: ['Pack tactics', 'Ambush', 'Survival instinct', 'Psionic vestiges'],
    languages: ['Gith'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'ds_id_fiend', name: 'Id Fiend', type: 'aberration', size: 'Medium', alignment: 'chaotic evil',
    cr: 4, ac: 13, hp: '66 (12d8 + 12)', speed: '30 ft.',
    description: 'A creature of nightmare given flesh — its form shifts based on the deepest fears of whoever looks at it.',
    lore: 'Id fiends are psionic predators that feed on terror. They project an aura that forces victims to hallucinate their worst fears, then attack while the mind is paralyzed with dread. They are creations of the Pristine Tower, warped by Athasian defiling magic.',
    tactics: 'Fear aura. Hallucinatory form. Feeds on psionic energy. Attacks terrified prey.',
    habitat: 'Athasian ruins, haunted wastes',
    abilities: ['Fear aura', 'Hallucinatory form', 'Psionic feed', 'Mind blast'],
    languages: ['telepathy 60 ft.'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },

  // ═══════════════════════════════════════════════════════════
  //  PLANESCAPE Appendices (MC8, Planescape MC I/II/III)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'ps_modron', name: 'Modron', type: 'construct', size: 'Medium', alignment: 'lawful neutral',
    cr: 2, ac: 16, hp: '44 (8d8 + 8)', speed: '30 ft.',
    description: 'A cube-shaped clockwork being with a single eye and stubby mechanical limbs, clicking as it performs its designated function.',
    lore: 'Modrons are the living gears of Mechanus, the plane of absolute law. They exist in a rigid caste hierarchy from monodrones to Primus, the One and the Prime. Every 289 years, they march across the planes in the Great Modron March, cataloguing all of existence.',
    tactics: 'Coordinated attacks. Repair each other. Absolutely predictable — and absolutely relentless.',
    habitat: 'Mechanus (the Clockwork Nirvana of Nirvana)',
    abilities: ['Coordinated attack', 'Repair', 'Clockwork mind (immune to charm)', 'Perfect coordination'],
    languages: ['Modron'],
    senses: ['truesight 120 ft.', 'passive Perception 10'],
  },
  {
    id: 'ps_modron_pentadrone', name: 'Pentadrone', type: 'construct', size: 'Large', alignment: 'lawful neutral',
    cr: 5, ac: 18, hp: '104 (11d10 + 44)', speed: '30 ft.',
    description: 'A five-limbed modron enforcer with a body like a walking starfish and the cold precision of absolute law.',
    lore: 'Pentadrones are the enforcers and guards of higher modrons, the first tier to demonstrate individual initiative — within strict parameters. They are the police-force of Mechanus and will chase lawbreakers across the planes.',
    tactics: 'Five attacks per round. Paralyzing gaze. Tracks lawbreakers across planes.',
    habitat: 'Mechanus',
    abilities: ['Multiattack (five limbs)', 'Paralyzing gaze', 'Planar tracking', 'Flight'],
    languages: ['Modron'],
    senses: ['truesight 120 ft.', 'passive Perception 13'],
  },
  {
    id: 'ps_tanarri_vrock', name: 'Vrock', type: 'fiend (demon)', size: 'Large', alignment: 'chaotic evil',
    cr: 6, ac: 15, hp: '104 (11d10 + 44)', speed: '40 ft., fly 60 ft.',
    description: 'A vulture-headed demon with filthy black wings, the stench of carrion clinging to it like a shroud.',
    lore: 'Vrocks are the shock troops and scavengers of the Abyss. They take immense joy in causing pain and emit a screech that ruptures eardrums and stuns. A circle of three or more vrocks can perform a Dance of Ruin that calls down devastating lightning.',
    tactics: 'Screech stuns. Multiattack (bite and claws). Dance of Ruin with other vrocks. Flies.',
    habitat: 'The Abyss',
    abilities: ['Stunning screech', 'Dance of Ruin', 'Multiattack', 'Fly', 'Spore cloud'],
    languages: ['Abyssal', 'telepathy 60 ft.'],
    senses: ['darkvision 120 ft.', 'passive Perception 13'],
  },
  {
    id: 'ps_tanarri_glabrezu', name: 'Glabrezu', type: 'fiend (demon)', size: 'Huge', alignment: 'chaotic evil',
    cr: 9, ac: 17, hp: '157 (15d12 + 60)', speed: '40 ft.',
    description: 'A towering demon with four arms — two ending in massive pincers, two in human-like hands — and a dog\'s head.',
    lore: 'Glabrezu are the tempters of the Abyss, specializing in twisting mortal desires into damnation. They offer power, wealth, and love — and the price is always a soul. Their four arms let them cast spells and fight in close combat simultaneously.',
    tactics: 'Pincer grapple. Spellcasting while grappling. Offers false bargains. Teleports.',
    habitat: 'The Abyss',
    abilities: ['Multiattack (pincers and claws)', 'Innate spellcasting', 'Teleport', 'False bargain'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    senses: ['truesight 120 ft.', 'passive Perception 16'],
  },
  {
    id: 'ps_tanarri_hezrou', name: 'Hezrou', type: 'fiend (demon)', size: 'Large', alignment: 'chaotic evil',
    cr: 8, ac: 16, hp: '136 (13d10 + 65)', speed: '30 ft.',
    description: 'A toad-like demon reeking of rot and sewage, its croaking voice a blasphemy against all that is clean.',
    lore: 'Hezrou are the sergeants of the Abyssal hordes, leading lesser demons into battle. Their mere presence is a pollution — the air around them becomes foul, and their croaking sows confusion. They serve more powerful demons in exchange for the privilege of commanding.',
    tactics: 'Stench aura. Confusion croak. Multiattack (bite and claws). Commands lesser demons.',
    habitat: 'The Abyss',
    abilities: ['Stench aura', 'Confusion', 'Multiattack', 'Amphibious'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    senses: ['darkvision 120 ft.', 'passive Perception 13'],
  },
  {
    id: 'ps_tanarri_marilith', name: 'Marilith', type: 'fiend (demon)', size: 'Large', alignment: 'chaotic evil',
    cr: 16, ac: 18, hp: '189 (18d10 + 90)', speed: '40 ft.',
    description: 'A six-armed serpent-woman, each hand holding a different blade, her body moving in a deadly dance of steel.',
    lore: 'Mariliths are the strategists and generals of the Abyss, master tacticians who wield six weapons simultaneously. They have been known to plan campaigns lasting centuries. Their vanity is legendary, but their skill with a blade is unmatched.',
    tactics: 'Six attacks per round. Parry and riposte. Teleports. Commands demon armies.',
    habitat: 'The Abyss',
    abilities: ['Multiattack (six weapons)', 'Parry', 'Reactive', 'Innate spellcasting', 'Teleport'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    senses: ['truesight 120 ft.', 'passive Perception 18'],
  },
  {
    id: 'ps_tanarri_nalfeshnee', name: 'Nalfeshnee', type: 'fiend (demon)', size: 'Huge', alignment: 'chaotic evil',
    cr: 13, ac: 18, hp: '184 (16d12 + 80)', speed: '20 ft., fly 30 ft.',
    description: 'A boar-headed behemoth with tiny wings that somehow keep it aloft, its beady eyes sizing up souls to judge and devour.',
    lore: 'Nalfeshnees are the judges of the Abyss, once celestial beings who fell from grace. They preside over the transformation of mortal souls into manes — the lowest form of demon — and feed on the agony of the process. Their stench can incapacitate.',
    tactics: 'Horror nimbus frightens. Stench. Bite and claws. Flies despite impossible proportions.',
    habitat: 'The Abyss',
    abilities: ['Horror nimbus', 'Stench', 'Multiattack', 'Fly', 'Teleport'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    senses: ['truesight 120 ft.', 'passive Perception 15'],
  },
  {
    id: 'ps_baatezu_barbazu', name: 'Barbazu (Bearded Devil)', type: 'fiend (devil)', size: 'Medium', alignment: 'lawful evil',
    cr: 3, ac: 13, hp: '52 (8d8 + 16)', speed: '30 ft.',
    description: 'A wiry, bearded devil with a glaive wreathed in the fires of Hell, its face split by a savage grin.',
    lore: 'Barbazu are the shock troops of Hell\'s legions, aggressive and fearless. Their filthy beards carry infernal wounds that resist mortal healing. They are the first real devils most planar travelers encounter — and often the last.',
    tactics: 'Infernal wound glaive. Frenzied charge. Beard attack. Fights to the death if ordered.',
    habitat: 'The Nine Hells (particularly Avernus)',
    abilities: ['Infernal wound', 'Beard attack', 'Frenzy', 'Devil\'s sight'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    senses: ['darkvision 120 ft.', 'passive Perception 10'],
  },
  {
    id: 'ps_baatezu_osyluth', name: 'Osyluth (Bone Devil)', type: 'fiend (devil)', size: 'Large', alignment: 'lawful evil',
    cr: 9, ac: 19, hp: '142 (15d10 + 60)', speed: '40 ft., fly 40 ft.',
    description: 'A skeletal devil — all bone and sinew — with a scorpion-like tail dripping venom and eyes of frozen hate.',
    lore: 'Osyluths are the secret police of the Nine Hells, punishing devils who step out of line. They are also used as interrogators and torturers of captured mortals. Their venom causes searing pain without granting the release of death.',
    tactics: 'Poison tail sting. Fear aura. Invisible at will. Flies. Interrogates prisoners.',
    habitat: 'The Nine Hells',
    abilities: ['Poison sting', 'Fear aura', 'Invisibility', 'Fly', 'Magic resistance'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    senses: ['darkvision 120 ft.', 'passive Perception 14'],
  },
  {
    id: 'ps_baatezu_hamatula', name: 'Hamatula (Barbed Devil)', type: 'fiend (devil)', size: 'Medium', alignment: 'lawful evil',
    cr: 5, ac: 15, hp: '110 (13d8 + 52)', speed: '30 ft.',
    description: 'A spike-covered devil — every inch of its hide is a barb, a hook, or a thorn, and it embraces its victims to make them share the pain.',
    lore: 'Hamatulas are the jailors and sentinels of Hell, appointed to guard important prisoners and treasures. They delight in close combat where their barbs can tear flesh. Their very skin is a weapon.',
    tactics: 'Grapples and hugs for barb damage. Hurls Flame. Holds ground as a living barrier.',
    habitat: 'The Nine Hells',
    abilities: ['Barbed defense', 'Grapple', 'Hurl Flame', 'Devil\'s sight'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    senses: ['darkvision 120 ft.', 'passive Perception 11'],
  },
  {
    id: 'ps_baatezu_erinyes', name: 'Erinyes', type: 'fiend (devil)', size: 'Medium', alignment: 'lawful evil',
    cr: 12, ac: 18, hp: '153 (18d8 + 72)', speed: '30 ft., fly 60 ft.',
    description: 'A fallen angel with black-feathered wings and a rope of entanglement in one hand, beautiful and terrible.',
    lore: 'Erinyes are devils who were once celestial beings, now corrupted to Hell\'s service. They retain their angelic beauty and poise, making them Hell\'s most effective tempters and assassins. Their rope of entanglement never misses its mark.',
    tactics: 'Rope of entanglement. Longbow from the air. Charm person. Fights with angelic skill and devilish cruelty.',
    habitat: 'The Nine Hells',
    abilities: ['Rope of entanglement', 'Fly', 'Charm', 'Multiattack', 'Magic resistance'],
    languages: ['Infernal', 'telepathy 120 ft.'],
    senses: ['truesight 120 ft.', 'passive Perception 17'],
  },
  {
    id: 'ps_yugoloth_mezzoloth', name: 'Mezzoloth (Mezzodaemon)', type: 'fiend (yugoloth)', size: 'Medium', alignment: 'neutral evil',
    cr: 5, ac: 18, hp: '75 (10d8 + 30)', speed: '40 ft.',
    description: 'An insectoid mercenary in spiked plate armor, its multifaceted eyes calculating the market value of your soul.',
    lore: 'Mezzoloths are the rank-and-file mercenaries of the yugoloth race — fiends of pure selfish greed who sell their services to the highest bidder in the Blood War. They fight for neither side, only for profit. When not hired, they raid for souls.',
    tactics: 'Cloudkill spell. Disease claws. Teleports. Disciplined mercenary tactics.',
    habitat: 'The Grey Wastes of Hades, Gehenna',
    abilities: ['Cloudkill', 'Disease', 'Teleport', 'Magic resistance'],
    languages: ['Abyssal', 'Infernal', 'telepathy 60 ft.'],
    senses: ['blindsight 60 ft.', 'darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'ps_yugoloth_nycaloth', name: 'Nycaloth', type: 'fiend (yugoloth)', size: 'Large', alignment: 'neutral evil',
    cr: 9, ac: 18, hp: '123 (13d10 + 52)', speed: '40 ft., fly 60 ft.',
    description: 'A gargoyle-like flying yugoloth with great bat wings and claws that can rend steel.',
    lore: 'Nycaloths are the aerial cavalry of the yugoloth armies, swooping down to carry off the wounded and the valuable. They are the most aggressive of the yugoloths, genuinely enjoying slaughter beyond the monetary reward.',
    tactics: 'Swooping claw attacks. Grabs and drops victims from height. Magic resistance. Teleports.',
    habitat: 'The Grey Wastes, Gehenna, Lower Planes',
    abilities: ['Fly', 'Swoop attack', 'Rake', 'Teleport', 'Magic resistance'],
    languages: ['Abyssal', 'Infernal', 'telepathy 60 ft.'],
    senses: ['blindsight 60 ft.', 'darkvision 60 ft.', 'passive Perception 13'],
  },

  // ═══════════════════════════════════════════════════════════
  //  RAVENLOFT Appendices (MC10, MC15, RMCI-III)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'rl_werebeast', name: 'Werebeast (Ravenloft)', type: 'humanoid (shapechanger)', size: 'Medium', alignment: 'neutral evil',
    cr: 5, ac: 11, hp: '78 (12d8 + 24)', speed: '40 ft.',
    description: 'A shapechanger cursed by the Dark Powers, its lupine form twisted and unnatural, its howl a cry of despair.',
    lore: 'Ravenloft\'s lycanthropes are different — their curse is bound to the land itself, enforced by the Dark Powers. They cannot simply be cured; each must confront their own moral darkness. They are tragic figures as often as monsters.',
    tactics: 'Regenerates unless hit by silver or magic. Bite spreads the curse. Hunts lone prey.',
    habitat: 'The domains of Ravenloft',
    abilities: ['Shapechanger', 'Regeneration (bypassed by silver/magic)', 'Curse of lycanthropy'],
    languages: ['Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'rl_geist', name: 'Geist', type: 'undead', size: 'Medium', alignment: 'neutral evil',
    cr: 4, ac: 12, hp: '45 (10d8)', speed: '0 ft., fly 40 ft. (hover)',
    description: 'A poltergeist on a grand scale — a ghost that throws furniture, slams doors, and howls with the voice of a storm.',
    lore: 'Geists are ghosts that have mastered the ability to affect the physical world from beyond the grave. They are not merely haunting spirits — they are active, violent presences that turn their haunts into deathtraps.',
    tactics: 'Telekinesis to hurl objects. Frightful moan. Possesses objects rather than creatures.',
    habitat: 'Haunted houses, condemned buildings, Ravenloft domains',
    abilities: ['Telekinesis', 'Frightful moan', 'Incorporeal', 'Object possession'],
    languages: ['the languages it knew in life'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'rl_golem_flesh_rl', name: 'Ravenloft Flesh Golem', type: 'construct', size: 'Medium', alignment: 'neutral',
    cr: 7, ac: 9, hp: '110 (13d8 + 52)', speed: '30 ft.',
    description: 'A stitched horror of dead parts. But this one weeps. Somewhere inside, a soul still struggles.',
    lore: 'In Ravenloft, flesh golems are not merely constructs — they are tragic figures whose creation demands the suffering of intelligent beings. Many carry fragments of memory from their donor parts. The Dark Powers ensure their existence is torment.',
    tactics: 'Berserk rage when damaged. Healed by lightning. Vulnerable to fire. A tragic, reluctant killer.',
    habitat: 'Ravenloft laboratories, mad scientist lairs',
    abilities: ['Berserk', 'Lightning absorption', 'Immutable form', 'Fragmented memory'],
    languages: ['understands creator\'s language, may whisper fragmented words'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'rl_vampire_slavic', name: 'Nosferatu (Slavic Vampire)', type: 'undead', size: 'Medium', alignment: 'chaotic evil',
    cr: 10, ac: 16, hp: '127 (15d8 + 60)', speed: '30 ft.',
    description: 'A vampire that never passes for human — a bald, bat-eared predator with needle fangs and claws like a grave-digger.',
    lore: 'The nosferatu is the vampire of Slavic folklore, the strigoi — a walking corpse that drinks blood and spreads plague. Unlike the suave Dracula archetype, it cannot charm or seduce; it simply takes. It must rest in its native soil.',
    tactics: 'Drains Constitution on hit. Spreads plague. Must rest in native soil. Weakened by holy symbols.',
    habitat: 'Eastern European domains of Ravenloft',
    abilities: ['Constitution drain', 'Plague spread', 'Regeneration', 'Spider climb'],
    languages: ['the languages it knew in life'],
    senses: ['darkvision 120 ft.', 'passive Perception 15'],
  },
  {
    id: 'rl_mummy_rl', name: 'Ravenloft Mummy', type: 'undead', size: 'Medium', alignment: 'lawful evil',
    cr: 6, ac: 13, hp: '85 (10d8 + 40)', speed: '25 ft.',
    description: 'An embalmed noble still dressed in funeral silks, its gaze a curse and its touch a creeping rot.',
    lore: 'Ravenloft mummies are not merely guardians of tombs — they are the embalmed remains of those who bargained with the Dark Powers for undeath. Their curse is stronger than normal mummies\'. They are bound to elaborate rituals and can only be truly destroyed under specific conditions.',
    tactics: 'Rot curse that resists ordinary healing. Frightful gaze. Cannot be permanently killed without a specific ritual.',
    habitat: 'Ravenloft tombs, desecrated temples, ancient estates',
    abilities: ['Greater mummy rot', 'Dreadful gaze', 'Regeneration (stopped only by ritual)', 'Fire vulnerability'],
    languages: ['the languages of its domain'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },

  // ═══════════════════════════════════════════════════════════
  //  SPELLJAMMER Appendices (MC7, MC9)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'sj_neogi', name: 'Neogi', type: 'aberration', size: 'Small', alignment: 'lawful evil',
    cr: 3, ac: 16, hp: '44 (8d6 + 16)', speed: '30 ft., climb 30 ft.',
    description: 'A spider-like eel with a bloated body, its eight legs carrying it with disturbing speed. Slaves pull its howdah.',
    lore: 'Neogi are the slavers of Wildspace — spider-eel merchants who see all other races as property. They travel in spelljamming ships crewed by charmed slaves and umber hulk bodyguards. A neogi\'s bite enslaves; its ship never returns empty.',
    tactics: 'Enslaving bite. Charm person. Commands umber hulks and slave crews. Spider climb.',
    habitat: 'Wildspace, neogi spelljamming ships, asteroid bases',
    abilities: ['Enslaving bite', 'Charm person', 'Spider climb', 'Slave master'],
    languages: ['Common', 'Neogi'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'sj_beholder_tyrant', name: 'Beholder Hive Mother', type: 'aberration', size: 'Huge', alignment: 'lawful evil',
    cr: 15, ac: 19, hp: '225 (18d20 + 36)', speed: '0 ft., fly 20 ft. (hover)',
    description: 'A beholder grown obscenely large — its central eye a void and its body swelling with the next generation of beholders.',
    lore: 'Hive mothers are the rarest and most terrifying beholder variant, capable of laying eggs that hatch into new beholders. They command entire cities of beholder-kin through psychic domination. A single hive mother can threaten an entire sphere.',
    tactics: 'Antimagic cone that affects entire rooms. Spawns beholders. Psychic domination. Legendary actions.',
    habitat: 'Spelljammer asteroid hives, deep wildspace',
    abilities: ['Greater antimagic cone', 'Spawn beholders', 'Psychic domination', 'Legendary resistance', 'Fly'],
    languages: ['Deep Speech', 'Undercommon', 'Beholder'],
    senses: ['darkvision 120 ft.', 'passive Perception 22'],
  },
  {
    id: 'sj_mercane', name: 'Mercane (Arcane)', type: 'giant', size: 'Large', alignment: 'lawful neutral',
    cr: 8, ac: 15, hp: '93 (11d10 + 33)', speed: '30 ft.',
    description: 'A twelve-foot-tall blue-skinned merchant in robes of gold thread, fingers adorned with rings from a hundred worlds.',
    lore: 'The mercanes — or arcanes — are the merchant-princes of Wildspace. They alone trade in spelljamming helms, the artifacts that make interstellar travel possible. They are universally neutral, selling to anyone with enough gold, and protected by fierce pacts.',
    tactics: 'Bargains rather than fights. Protected by planar contracts. Summons bodyguards when threatened. Teleports.',
    habitat: 'Wildspace trading posts, the spacelanes',
    abilities: ['Spelljamming helm creation', 'Planar contract protection', 'Summon bodyguard', 'Teleport'],
    languages: ['Common', 'any 10 others'],
    senses: ['passive Perception 14'],
  },
  {
    id: 'sj_space_clown', name: 'Space Clown', type: 'fey', size: 'Medium', alignment: 'chaotic evil',
    cr: 3, ac: 14, hp: '49 (9d8 + 9)', speed: '30 ft.',
    description: 'A grinning clown in motley whose makeup is not paint and whose balloon animals are made of intestines.',
    lore: 'Space clowns are the horrific jesters of the Doomguard, roaming wildspace in battered ships that look like carnival wagons. Their humor is lethal — they kill with joy buzzers, explode with laughter, and turn their victims into "performers."',
    tactics: 'Lethal joy buzzer. Explosive death (laughs while detonating). Illusions. Fear on seeing its true face.',
    habitat: 'Wildspace, "carnival" ships',
    abilities: ['Lethal joy buzzer', 'Explosive death', 'Illusions', 'Fey mischief'],
    languages: ['Common', 'Sylvan'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },
  {
    id: 'sj_scro', name: 'Scro', type: 'humanoid (orc)', size: 'Medium', alignment: 'lawful evil',
    cr: 1, ac: 16, hp: '32 (5d8 + 10)', speed: '30 ft.',
    description: 'An orc in crisp military uniform. Its tusks are polished, its armor gleaming. It meets your eyes with cold intelligence.',
    lore: 'Scro are what happens when orcs evolve beyond chaos — a disciplined, intelligent, and terrifying foe. The name is simply "orcs" spelled backwards. They command spelljamming warships and have carved out an empire in the spacelanes.',
    tactics: 'Military discipline. Tactical squads. Spelljamming boarding actions. Hates elves with cold precision.',
    habitat: 'Wildspace, scro warships, conquered asteroid bases',
    abilities: ['Military discipline', 'Tactical training', 'Spelljamming combat'],
    languages: ['Common', 'Orc', 'Scro battle cant'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },

  // ═══════════════════════════════════════════════════════════
  //  DRAGONLANCE Appendix (MC4)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'dl_draconian_baaz', name: 'Baaz Draconian', type: 'monstrosity (draconian)', size: 'Medium', alignment: 'lawful evil',
    cr: 1, ac: 15, hp: '22 (4d8 + 4)', speed: '30 ft.',
    description: 'A humanoid dragon-man with dull brass scales and a short sword, its eyes full of hate for the life it was denied.',
    lore: 'Draconians are dragon-men created from corrupted metallic dragon eggs by the Dark Queen\'s sorcery. Baaz are the lowest caste, born from brass dragon eggs. When slain, their bodies turn to stone, trapping the weapon that killed them.',
    tactics: 'Sword and shield. Death throes turn body to stone, trapping weapons. Cannon fodder.',
    habitat: 'Dragon armies, Krynn battlefields',
    abilities: ['Death throes (petrify weapon)', 'Dragon heritage', 'Darkvision'],
    languages: ['Common', 'Draconic'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'dl_draconian_kapak', name: 'Kapak Draconian', type: 'monstrosity (draconian)', size: 'Medium', alignment: 'lawful evil',
    cr: 2, ac: 15, hp: '39 (6d8 + 12)', speed: '30 ft.',
    description: 'A lean, copper-scaled draconian whose tongue flicks out like a snake, tasting the air for weakness.',
    lore: 'Kapak draconians are born from copper dragon eggs. They are the skirmishers and assassins of the dragon armies — faster than baaz, with a venomous bite and a death that dissolves into an acid pool that eats through armor.',
    tactics: 'Poison bite. Hit-and-run skirmish tactics. Death throes dissolve into acid.',
    habitat: 'Dragon armies, ambush sites',
    abilities: ['Poison bite', 'Death throes (acid pool)', 'Skirmish training'],
    languages: ['Common', 'Draconic'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },
  {
    id: 'dl_draconian_bozak', name: 'Bozak Draconian', type: 'monstrosity (draconian)', size: 'Medium', alignment: 'lawful evil',
    cr: 3, ac: 15, hp: '58 (9d8 + 18)', speed: '30 ft.',
    description: 'A bronze-scaled draconian whose hands crackle with lightning and whose mind holds centuries of lore.',
    lore: 'Bozak draconians come from bronze dragon eggs and are the mages of the dragon armies. They are natural sorcerers, able to cast lightning bolts and shield themselves with magic. Their death throes explode in arcs of electricity.',
    tactics: 'Lightning spells. Front line with magical backup. Death throes explode with lightning.',
    habitat: 'Dragon army command posts',
    abilities: ['Innate sorcery (lightning)', 'Death throes (lightning explosion)', 'Spellcasting'],
    languages: ['Common', 'Draconic', 'Magius'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },
  {
    id: 'dl_draconian_sivak', name: 'Sivak Draconian', type: 'monstrosity (draconian)', size: 'Large', alignment: 'lawful evil',
    cr: 4, ac: 17, hp: '75 (10d10 + 20)', speed: '30 ft., fly 40 ft.',
    description: 'A towering silver-scaled draconian with wings and the ability to assume the form of whoever it kills.',
    lore: 'Sivak draconians are the elite shock troops, born from silver dragon eggs. They are winged warriors who can shapeshift into the form of any humanoid they slay, making them devastating infiltrators. Dying, they take the shape of their killer.',
    tactics: 'Shapeshift into slain enemies. Aerial charges. Death throes mimic the killer\'s form.',
    habitat: 'Dragon army elite units, infiltration missions',
    abilities: ['Shapechanger (into killed humanoids)', 'Fly', 'Death throes (mimic killer)'],
    languages: ['Common', 'Draconic'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'dl_draconian_aurak', name: 'Aurak Draconian', type: 'monstrosity (draconian)', size: 'Medium', alignment: 'lawful evil',
    cr: 5, ac: 18, hp: '65 (10d8 + 20)', speed: '30 ft.',
    description: 'A gold-scaled draconian who barely seems to touch the ground — a being of pure magical hate wearing a dragon\'s form.',
    lore: 'Auraks are the rarest draconians, born from gold dragon eggs. They are the highest caste — spellcasters, tacticians, and commanders. Their magic is innate and terrible. When they die, they explode in a blast of green flame and then fight on for three rounds as a vengeful spirit.',
    tactics: 'Arcane spellcasting. Energy rays. Death throes: green flame explosion, then fights as spirit for 3 rounds before dying again.',
    habitat: 'Dragon army high command',
    abilities: ['Arcane spellcasting', 'Energy ray', 'Death throes (explosion + vengeful spirit)', 'Mind blank'],
    languages: ['Common', 'Draconic', 'any 5 others'],
    senses: ['darkvision 60 ft.', 'passive Perception 15'],
  },

  // ═══════════════════════════════════════════════════════════
  //  AL-QADIM Appendix (MC13)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'aq_gen', name: 'Jann', type: 'elemental (genie)', size: 'Medium', alignment: 'neutral',
    cr: 4, ac: 16, hp: '66 (12d8 + 12)', speed: '30 ft., fly 20 ft.',
    description: 'The least of the genie races, wearing the face of a desert nomad — but those eyes have seen the Elemental Planes.',
    lore: 'Jann are the weakest and most mortal of the genies, composed of all four elements in balance. They are the only genies that can travel freely between the material world and the planes. They live as desert nomads, guarding oases and ancient secrets.',
    tactics: 'Elemental adaptation. Fights with scimitar and bow. Teleports short distances.',
    habitat: 'Deserts, oases, elemental crossroads',
    abilities: ['Elemental balance', 'Teleport', 'Combat training'],
    languages: ['Common', 'Auran', 'Aquan', 'Ignan', 'Terran'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'aq_silat', name: 'Silat', type: 'monstrosity', size: 'Large', alignment: 'neutral',
    cr: 6, ac: 15, hp: '95 (10d10 + 40)', speed: '40 ft.',
    description: 'A creature with the torso of a man, the body of a lion, and the face of a hawk, wearing golden bracers.',
    lore: 'Silats are guardians of Zakharan bridges and fords, demanding payment or riddles from those who wish to cross. They are honorable but fierce, bound by ancient pacts. Answer their riddle and they may become a temporary ally.',
    tactics: 'Riddle challenge. Leaps and claws. Demands payment. Honorable combat.',
    habitat: 'Bridges, fords, desert passes',
    abilities: ['Pounce', 'Riddle challenge', 'Leap', 'Honor-bound'],
    languages: ['Common', 'Midani'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },

  // ═══════════════════════════════════════════════════════════
  //  KARA-TUR Appendix (MC6)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'kt_jiki_nikukabe', name: 'Jiki-niku-kabe (Flesh Wall)', type: 'undead', size: 'Huge', alignment: 'neutral evil',
    cr: 8, ac: 14, hp: '136 (16d12 + 32)', speed: '0 ft.',
    description: 'A wall of fused human bodies, faces and limbs still moving, moaning, reaching, pulling anything close into itself.',
    lore: 'The jiki-niku-kabe is an undead construction from Kara-Tur\'s darkest sorceries — a wall made of living bodies fused into a single writhing mass. It blocks passages and absorbs living things that come into contact with it, adding them to its substance.',
    tactics: 'Engulfs creatures that touch it. Occupies an entire passage. Drains life.',
    habitat: 'Kara-Tur fortresses, necromantic lairs',
    abilities: ['Engulf', 'Life drain', 'Immobile', 'Absorb'],
    languages: [],
    senses: ['blindsight 60 ft.', 'passive Perception 8'],
  },
  {
    id: 'kt_oni', name: 'Oni (Ogre Mage)', type: 'giant', size: 'Large', alignment: 'lawful evil',
    cr: 7, ac: 16, hp: '110 (13d10 + 39)', speed: '30 ft., fly 30 ft.',
    description: 'A blue-skinned, horned ogre in fine robes, its tusks filed to points and a fan of steel in one hand.',
    lore: 'The oni — the ogre mage — is a creature of Kara-Tur that combines ogre strength with powerful sorcery. It can fly, turn invisible, assume human form, and cast a cone of cold. Oni serve as warlords, crime bosses, and secret rulers.',
    tactics: 'Turns invisible. Cone of cold. Shapechange to infiltrate. Regenerates.',
    habitat: 'Kara-Tur mountains, criminal underworlds',
    abilities: ['Invisibility', 'Cone of cold', 'Shapechanger', 'Regeneration', 'Fly'],
    languages: ['Common', 'Giant'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },

  // ═══════════════════════════════════════════════════════════
  //  GREYHAWK Appendix (MC5)
  // ═══════════════════════════════════════════════════════════
  {
    id: 'gh_valley_elf', name: 'Valley Elf', type: 'humanoid (elf)', size: 'Medium', alignment: 'chaotic good',
    cr: 0.5, ac: 13, hp: '11 (2d8 + 2)', speed: '35 ft.',
    description: 'An elf with the look of someone who has never seen a dungeon — open, trusting, and carrying a hunting bow.',
    lore: 'Valley elves are the secluded, peaceful cousins of the high elves, dwelling in the hidden Valleys of the Flanaess. Unlike their cousins, they eschew contact with the outside world. They are experts with the bow and masters of forest camouflage.',
    tactics: 'Longbow from cover. Forest camouflage. Fights defensively to protect their valley.',
    habitat: 'Hidden valleys of Greyhawk, deep forests',
    abilities: ['Forest camouflage', 'Skilled archer', 'Fey ancestry'],
    languages: ['Elvish', 'Sylvan'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'gh_swordwraith', name: 'Swordwraith', type: 'undead', size: 'Medium', alignment: 'lawful evil',
    cr: 4, ac: 17, hp: '67 (9d8 + 27)', speed: '30 ft.',
    description: 'A spectral soldier in the armor of a fallen empire, its gaze fixed on a battle that ended centuries ago.',
    lore: 'Swordwraiths are the ghosts of soldiers who died in battles so terrible that their spirits refused to move on. They endlessly refight their last battle, attacking any who enter their field. Some still carry the banners of nations that no longer exist.',
    tactics: 'Martial spirit — fights with ghost-soldier discipline. Phase through solid objects. Rallies other swordwraiths.',
    habitat: 'Ancient battlefields, forgotten war camps',
    abilities: ['Incorporeal', 'Martial training', 'Battle cry', 'Phalanx formation'],
    languages: ['the languages of its fallen nation'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
];