/**
 * Advanced Dungeons & Dragons 1st Edition
 * Monster Manual (1977), Fiend Folio (1981), Monster Manual II (1983)
 *
 * Original writeups in the modern BestiaryEntry shape.
 */
import type { BestiaryEntry } from '../DnDKnowledge';

export const ADND1E_BESTIARY: BestiaryEntry[] = [
  // ═══════════════════════════════════════════════════════
  //  MONSTER MANUAL (1977)
  // ═══════════════════════════════════════════════════════
  {
    id: 'adnd_bulette', name: 'Bulette (Landshark)', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 5, ac: 17, hp: '94 (9d10 + 45)', speed: '40 ft., burrow 10 ft.',
    description: 'A squat, armadillo-plated horror that bursts from the earth with a leap, its massive jaws shearing through flesh and bone.',
    lore: 'The bulette — called the landshark by those who survive its attacks — is a tunnelling predator that hunts by vibration. It explodes out of the ground, devours its target, and vanishes back into the earth before retaliation can come. It fears nothing, not even dragons.',
    tactics: 'Burrows beneath prey and erupts in a deadly leap. Bites and claws. Swallows human-sized prey whole.',
    habitat: 'Plains, hills, forests — anywhere with soft enough soil to tunnel',
    abilities: ['Deadly leap', 'Burrow', 'Tremorsense', 'Multiattack'],
    languages: [],
    senses: ['darkvision 60 ft.', 'tremorsense 60 ft.', 'passive Perception 16'],
  },
  {
    id: 'adnd_ankheg', name: 'Ankheg', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 2, ac: 14, hp: '39 (6d10 + 6)', speed: '30 ft., burrow 10 ft.',
    description: 'A ten-foot insectoid with glossy brown chitin, oversized mandibles dripping with acid, and the strength to drag a horse underground.',
    lore: 'Ankhegs are subterranean ambush predators of farmland and forest edges. They burrow beneath the soil and wait for the vibrations of passing prey. Their acidic digestive juices can dissolve plate armor, and they drag victims into their tunnels to feed.',
    tactics: 'Ambushes from underground. Grapples with mandibles, sprays acid. Drags prey into burrow.',
    habitat: 'Farmlands, forest edges, soft-soil plains',
    abilities: ['Ambush burrow', 'Acid spray', 'Grapple', 'Tremorsense'],
    languages: [],
    senses: ['darkvision 60 ft.', 'tremorsense 60 ft.', 'passive Perception 11'],
  },
  {
    id: 'adnd_carrion_crawler', name: 'Carrion Crawler', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 2, ac: 13, hp: '51 (6d10 + 18)', speed: '30 ft., climb 30 ft.',
    description: 'A pallid, segmented horror with a forest of writhing tentacles around its beak-like maw, each tentacle dripping paralytic slime.',
    lore: 'Carrion crawlers are the scavengers of deadly dungeons, drawn to battlefields and corpses. Their tentacles deliver paralysis that lasts for minutes — long enough for them to feed at leisure. They climb walls and ceilings with ease, striking from above.',
    tactics: 'Paralytic tentacles strike first. Bites paralyzed victims. Climbs out of melee reach.',
    habitat: 'Dungeons, caverns, sewers',
    abilities: ['Paralyzing tentacles', 'Spider climb', 'Keen smell'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'adnd_otyugh', name: 'Otyugh', type: 'aberration', size: 'Large', alignment: 'neutral',
    cr: 5, ac: 14, hp: '114 (12d10 + 48)', speed: '30 ft.',
    description: 'A rubbery, three-legged mound of flesh with a central eye-stalk and two tentacle arms, reeking of the filth it consumes.',
    lore: 'Otyughs are the garbage-disposal monsters of the dungeon ecology, eating carrion, offal, and anything that falls into their pits. They are not inherently evil and can sometimes be bargained with. They communicate through a limited telepathic chatter.',
    tactics: 'Grapples with two tentacles, then bites. Drags prey into its filth-pit lair. Uses stench aura.',
    habitat: 'Dungeon refuse pits, sewers, swamps',
    abilities: ['Multiattack (tentacles, bite)', 'Stench aura', 'Limited telepathy', 'Grapple'],
    languages: ['Otyugh', 'telepathy 120 ft. (simple concepts)'],
    senses: ['darkvision 120 ft.', 'passive Perception 11'],
  },
  {
    id: 'adnd_neo_otyugh', name: 'Neo-Otyugh', type: 'aberration', size: 'Huge', alignment: 'neutral',
    cr: 8, ac: 16, hp: '175 (14d12 + 84)', speed: '30 ft.',
    description: 'A larger, meaner otyugh with a brain that has developed true intelligence and a taste for live prey over refuse.',
    lore: 'The neo-otyugh is what happens when an otyugh eats enough intelligent prey — it grows smarter, hungrier, and far more dangerous. Unlike its humble kin, the neo-otyugh actively hunts and can form crude plans. Its telepathy becomes a weapon.',
    tactics: 'Grapples and crushes. Uses stench to disorient. Telepathically taunts and confuses prey.',
    habitat: 'Deep dungeon pits, mind flayer disposal chambers',
    abilities: ['Multiattack', 'Stench aura', 'Telepathic assault', 'Grapple'],
    languages: ['Common', 'telepathy 120 ft.'],
    senses: ['darkvision 120 ft.', 'passive Perception 13'],
  },
  {
    id: 'adnd_remorhaz', name: 'Remorhaz', type: 'monstrosity', size: 'Huge', alignment: 'unaligned',
    cr: 11, ac: 17, hp: '195 (17d12 + 85)', speed: '30 ft., burrow 20 ft.',
    description: 'A polar horror — a segmented ice-worm with glowing fins along its back that melt snow and ice into steam, its mandibles hot enough to sear through plate.',
    lore: 'Remorhaz hunt the frozen wastes, their bodies generating heat intense enough to melt the ice they burrow through. They lie dormant under snow, then erupt beneath their prey. Frost giants hunt them as rites of passage — most do not return.',
    tactics: 'Burrows beneath snow/ice for ambush. Heated body burns anything touching it. Swallows prey whole.',
    habitat: 'Arctic tundra, frozen seas, glacial caves',
    abilities: ['Heated body (fire damage on touch)', 'Burrow', 'Swallow whole'],
    languages: [],
    senses: ['darkvision 60 ft.', 'tremorsense 60 ft.', 'passive Perception 12'],
  },
  {
    id: 'adnd_umber_hulk', name: 'Umber Hulk', type: 'monstrosity', size: 'Large', alignment: 'chaotic evil',
    cr: 5, ac: 18, hp: '93 (11d10 + 33)', speed: '30 ft., burrow 20 ft.',
    description: 'A broad-shouldered insectoid with four eyes and massive digging claws, its gaze a weapon as much as its fists.',
    lore: 'Umber hulks are subterranean brutes that tunnel through solid rock, leaving chaos in their wake. Their four eyes project a confusing gaze that scrambles the minds of those who meet them. They are solitary, aggressive, and nearly unstoppable diggers.',
    tactics: 'Confusing gaze before melee. Multiattack with claws and mandibles. Burrows through walls to escape or flank.',
    habitat: 'Deep Underdark, cave networks',
    abilities: ['Confusing gaze', 'Tunneler', 'Multiattack'],
    languages: ['Umber Hulk'],
    senses: ['darkvision 120 ft.', 'tremorsense 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'adnd_ettercap', name: 'Ettercap', type: 'monstrosity', size: 'Medium', alignment: 'neutral evil',
    cr: 2, ac: 13, hp: '44 (8d8 + 8)', speed: '30 ft., climb 30 ft.',
    description: 'A man-spider with a swollen abdomen and spindly arms, weaving web traps in dark places.',
    lore: 'Ettercaps are the weavers of the deep forest and cave, tending giant spiders like a shepherd tends sheep. They build elaborate web-traps and garrote the unwary with silken cords. Their bite delivers a numbing venom.',
    tactics: 'Web traps and garrotes. Poisonous bite. Commands giant spiders. Uses webs to control the battlefield.',
    habitat: 'Dark forests, caves, cavern ceilings',
    abilities: ['Web garrote', 'Poison bite', 'Spider climb', 'Spider command'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'adnd_piercer', name: 'Piercer', type: 'monstrosity', size: 'Medium', alignment: 'unaligned',
    cr: 0.5, ac: 15, hp: '22 (3d8 + 9)', speed: '5 ft., climb 5 ft.',
    description: 'A cone of stone hanging from a cavern ceiling — until it drops onto the head of whoever walks beneath.',
    lore: 'The piercer is a living stalactite, indistinguishable from its inanimate brethren until it lets go. A single drop can kill an unwary adventurer. They cling in clusters, so one strike rarely means safety.',
    tactics: 'Drops from ceiling for surprise attack. Waits motionless until prey is directly underneath.',
    habitat: 'Cavern ceilings, dungeon corridors with high ceilings',
    abilities: ['Drop attack', 'False appearance', 'Climb'],
    languages: [],
    senses: ['blindsight 30 ft.', 'passive Perception 6'],
  },
  {
    id: 'adnd_trapper', name: 'Trapper', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 3, ac: 13, hp: '85 (10d10 + 30)', speed: '20 ft., climb 20 ft.',
    description: 'An entire section of floor that unfolds into a leathery manta-like predator, folding up around anything standing on it.',
    lore: 'The trapper is the floor-dwelling cousin of the piercer — a broad, flat creature that disguises itself as stone flooring. When prey walks across it, the trapper folds up like a snapping purse, crushing and smothering everything inside.',
    tactics: 'Lies in wait as "floor." Folds up to smother and crush. Grapples all creatures standing on it.',
    habitat: 'Dungeon floors, smooth cave bottoms',
    abilities: ['False appearance (floor)', 'Smother', 'Crush'],
    languages: [],
    senses: ['blindsight 60 ft.', 'passive Perception 6'],
  },
  {
    id: 'adnd_lurker_above', name: 'Lurker Above', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 4, ac: 12, hp: '76 (8d10 + 32)', speed: '10 ft., fly 40 ft.',
    description: 'A section of ceiling that peels downward, spreading wings of stony flesh to smother the air.',
    lore: 'Completing the dungeon camouflage trinity, the lurker above masquerades as a high ceiling. It drops down like a blanket, smothering and constricting its prey while it digests them alive with acidic secretions.',
    tactics: 'Falls from ceiling to smother. Constricts for ongoing damage. Acidic underside.',
    habitat: 'Cavern ceilings, tall dungeon chambers',
    abilities: ['False appearance (ceiling)', 'Smother', 'Constrict', 'Acid'],
    languages: [],
    senses: ['blindsight 60 ft.', 'passive Perception 6'],
  },
  {
    id: 'adnd_shambling_mound', name: 'Shambling Mound', type: 'plant', size: 'Large', alignment: 'unaligned',
    cr: 5, ac: 15, hp: '136 (16d10 + 48)', speed: '20 ft., swim 20 ft.',
    description: 'A heap of rotting vegetation that rises into a roughly humanoid shape, with vines that reach and constrict.',
    lore: 'Shambling mounds are born where lightning strikes fetid swamps. They are unintelligent but relentless, absorbing weapons into their vegetative mass. Lightning not only fails to harm them — it heals and strengthens them.',
    tactics: 'Engulfs and constricts. Healed by lightning. Resistant to blunt and piercing weapons. Absorbs fallen foes.',
    habitat: 'Swamps, marshes, bogs',
    abilities: ['Engulf', 'Lightning absorption', 'Resistant to bludgeoning/piercing', 'Swim'],
    languages: [],
    senses: ['blindsight 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'adnd_treant', name: 'Treant', type: 'plant', size: 'Huge', alignment: 'chaotic good',
    cr: 9, ac: 16, hp: '138 (12d12 + 60)', speed: '30 ft.',
    description: 'A walking oak with bark like armor and a voice that is the sound of wind through ancient branches.',
    lore: 'Treants are the eldest guardians of the forest, ancient trees awakened to protect the green world. They sleep for centuries between threats but are terrifying when roused. They command the forest itself — trees and roots answer their call.',
    tactics: 'Animate two trees as allies. Crush with great branches. Rock throwing. Hates fire.',
    habitat: 'Ancient forests, sacred groves',
    abilities: ['Animate trees', 'Siege monster', 'Bark armor', 'Forest stride'],
    languages: ['Common', 'Druidic', 'Elvish', 'Sylvan'],
    senses: ['passive Perception 13'],
  },
  {
    id: 'adnd_intellect_devourer', name: 'Intellect Devourer', type: 'aberration', size: 'Tiny', alignment: 'lawful evil',
    cr: 2, ac: 12, hp: '21 (6d4 + 6)', speed: '40 ft.',
    description: 'A walking brain with clawed legs, its surface pulsing with malevolent psionic energy.',
    lore: 'Intellect devourers are the scouts and spies of the mind flayers, created from the brains of humanoids enslaved to the elder brain. They devour a victim\'s intellect and pilot the empty body like a puppet, passing among the living undetected.',
    tactics: 'Psionic assault to stun. Devours intellect. Body theft — pilots the husk of a brainless victim.',
    habitat: 'Underdark, mind flayer colonies, anywhere illithids need spies',
    abilities: ['Devour intellect', 'Body thief', 'Psionic blast', 'Detect sentience'],
    languages: ['Deep Speech', 'Undercommon', 'telepathy 120 ft.'],
    senses: ['blindsight 60 ft.', 'passive Perception 11'],
  },
  {
    id: 'adnd_sahuagin', name: 'Sahuagin', type: 'humanoid (sahuagin)', size: 'Medium', alignment: 'lawful evil',
    cr: 0.5, ac: 12, hp: '22 (4d8 + 4)', speed: '30 ft., swim 40 ft.',
    description: 'A fish-like humanoid — the "sea devil" — with webbed claws, a dorsal crest, and jet-black shark eyes.',
    lore: 'Sahuagin are the militant terrors of coastal waters, raiding shore settlements and enslaving aquatic humanoids. Their society is a brutal hierarchy run by priestesses of their shark-god. They can communicate telepathically with sharks.',
    tactics: 'Underwater ambush. Swarm tactics with shark allies. Raiding parties with nets and tridents.',
    habitat: 'Coastal waters, reefs, undersea cities',
    abilities: ['Blood frenzy', 'Shark telepathy', 'Amphibious', 'Darkvision'],
    languages: ['Sahuagin'],
    senses: ['darkvision 120 ft.', 'passive Perception 15'],
  },

  // ═══════════════════════════════════════════════════════
  //  FIEND FOLIO (1981) — UK import of fan submissions
  // ═══════════════════════════════════════════════════════
  {
    id: 'ff_death_knight_adnd', name: 'Death Knight', type: 'undead', size: 'Medium', alignment: 'chaotic evil',
    cr: 17, ac: 20, hp: '180 (19d8 + 95)', speed: '30 ft.',
    description: 'A skeletal champion in blackened plate, hellfire glowing in its empty sockets, a greatsword humming with necrotic power.',
    lore: 'The death knight was codified in the Fiend Folio — a fallen paladin, cursed to undeath for breaking a sacred oath. It commands undead armies and retains the martial prowess of its living days, now augmented by terrible dark powers.',
    tactics: 'Hellfire orb at range. Commands undead. Closes with greatsword and smites. Magic resistance.',
    habitat: 'Fallen fortresses, betrayed temples, sites of great oaths broken',
    abilities: ['Magic resistance', 'Hellfire orb', 'Marshal undead', 'Smite'],
    languages: ['Abyssal', 'Common'],
    senses: ['darkvision 120 ft.', 'passive Perception 12'],
  },
  {
    id: 'ff_githyanki', name: 'Githyanki', type: 'humanoid (gith)', size: 'Medium', alignment: 'lawful evil',
    cr: 3, ac: 17, hp: '49 (9d8 + 9)', speed: '30 ft.',
    description: 'A gaunt, yellow-skinned warrior in ornate silvered armor, a silver sword in hand and a cold, predatory gaze.',
    lore: 'Githyanki are the liberator-race that cast off the mind flayer yoke millennia ago — only to become raiders themselves, dwelling on the Astral Plane and waging eternal war. Their silver swords can sever the silver cords of astral travelers.',
    tactics: 'Psionic leap for mobility. Silver sword severs astral cord. Fights in disciplined squads.',
    habitat: 'The Astral Plane, githyanki fortresses',
    abilities: ['Innate psionics', 'Silver sword', 'Astral stride', 'Martial prowess'],
    languages: ['Common', 'Gith'],
    senses: ['passive Perception 14'],
  },
  {
    id: 'ff_githzerai', name: 'Githzerai', type: 'humanoid (gith)', size: 'Medium', alignment: 'lawful neutral',
    cr: 3, ac: 17, hp: '49 (9d8 + 9)', speed: '30 ft.',
    description: 'A lean, ascetic figure in simple robes, moving with preternatural calm. A mind sharpened like a blade.',
    lore: 'The githzerai split from the githyanki after the mind flayer rebellion, choosing the path of monastic discipline over conquest. They dwell in Limbo, shaping the chaos with their will. They are masters of defensive psionics and unarmed combat.',
    tactics: 'Psionic barriers. Mental stillness counters mind flayers. Unarmed strikes with psychic force.',
    habitat: 'Limbo, githzerai monasteries',
    abilities: ['Innate psionics', 'Unarmored defense', 'Monastic discipline', 'Chaos shaping'],
    languages: ['Common', 'Gith'],
    senses: ['passive Perception 14'],
  },
  {
    id: 'ff_slaadi_red', name: 'Red Slaad', type: 'aberration (slaad)', size: 'Large', alignment: 'chaotic neutral',
    cr: 5, ac: 14, hp: '93 (11d10 + 33)', speed: '30 ft.',
    description: 'A giant, blood-red frog-creature with long claws and a throat pouch that pulses with barely contained chaos.',
    lore: 'Slaad are the chaos-spawn of Limbo, amphibious engines of pure unpredictability. Red slaad implant eggs in living hosts with their claws — a horrific gestation that culminates in a new slaad bursting from the victim\'s chest.',
    tactics: 'Claw implantation. Regenerates. Spreads chaos through reproduction. Attacks anything without pattern.',
    habitat: 'Limbo, places touched by pure chaos',
    abilities: ['Implant egg', 'Regeneration', 'Chaotic aura', 'Magic resistance'],
    languages: ['Slaad', 'telepathy 60 ft.'],
    senses: ['darkvision 60 ft.', 'passive Perception 11'],
  },
  {
    id: 'ff_slaadi_blue', name: 'Blue Slaad', type: 'aberration (slaad)', size: 'Large', alignment: 'chaotic neutral',
    cr: 7, ac: 15, hp: '123 (13d10 + 52)', speed: '30 ft.',
    description: 'A larger, stronger slate-blue slaad with a bone spur protruding from each wrist and a gaze of raw violence.',
    lore: 'Blue slaad are the next stage in the chaotic life cycle, stronger and more aggressive than the red. Their claws carry a wasting disease called chaos phage. They spread chaos not by implanting eggs but by transforming their victims.',
    tactics: 'Chaos phage infection. Regenerates. Aggressive, unpredictable melee.',
    habitat: 'Limbo, chaos-touched planes',
    abilities: ['Chaos phage', 'Regeneration', 'Magic resistance'],
    languages: ['Slaad', 'telepathy 60 ft.'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },
  {
    id: 'ff_slaadi_green', name: 'Green Slaad', type: 'aberration (slaad)', size: 'Large', alignment: 'chaotic neutral',
    cr: 8, ac: 16, hp: '127 (15d10 + 45)', speed: '30 ft.',
    description: 'A towering, sage-green slaad with intelligence gleaming in its amphibian eyes and magic crackling at its claws.',
    lore: 'Green slaad are the evolved form that has attained spellcasting and true cunning. They are the sorcerer-priests of slaadkind, able to shapeshift into humanoid form and work chaos magic. They are the most dangerous — because they can plan.',
    tactics: 'Spellcasting (chaos magic). Shapechange to infiltrate. Regenerates. Commands lesser slaad.',
    habitat: 'Limbo, any plane where chaos has been summoned',
    abilities: ['Innate spellcasting', 'Shapechanger', 'Regeneration', 'Magic resistance'],
    languages: ['Slaad', 'Common', 'telepathy 60 ft.'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'ff_slaadi_death', name: 'Death Slaad', type: 'aberration (slaad)', size: 'Medium', alignment: 'chaotic evil',
    cr: 10, ac: 18, hp: '170 (20d8 + 80)', speed: '30 ft.',
    description: 'A black-scaled slaad, lean and deadly, its chaos refined into pure martial lethality and killing magic.',
    lore: 'Death slaad are the ultimate evolution of the chaotic bloodline — the assassins and executioners of the slaad lords. They combine the green\'s magic with the physical power of a greater devil. They hunt for sport across the planes.',
    tactics: 'Innate spellcasting including power word stun and cloudkill. Multiattack. Regenerates.',
    habitat: 'Limbo, the hunting grounds of the slaad lords',
    abilities: ['Innate spellcasting', 'Multiattack', 'Regeneration', 'Magic resistance'],
    languages: ['Slaad', 'Abyssal', 'Common', 'telepathy 60 ft.'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'ff_bullywug', name: 'Bullywug', type: 'humanoid (bullywug)', size: 'Medium', alignment: 'neutral evil',
    cr: 0.25, ac: 15, hp: '11 (2d8 + 2)', speed: '20 ft., swim 40 ft.',
    description: 'A frog-man with mottled green skin, bulging eyes, and a crude spear. Its croak carries across the marsh.',
    lore: 'Bullywugs are the crude tribes of the deep marsh, worshiping giant frogs and toad-demons. They are cruel, stupid, and organized by a brutal caste system. Their speech is a language of croaks and gestures.',
    tactics: 'Amphibious ambush. Swarming leap attacks. Swamp camouflage.',
    habitat: 'Marshes, swamps, wetlands',
    abilities: ['Amphibious', 'Swamp camouflage', 'Leap attack'],
    languages: ['Bullywug'],
    senses: ['passive Perception 10'],
  },
  {
    id: 'ff_kua_toa', name: 'Kuo-Toa', type: 'humanoid (kuo-toa)', size: 'Medium', alignment: 'neutral evil',
    cr: 0.25, ac: 13, hp: '18 (4d8)', speed: '30 ft., swim 30 ft.',
    description: 'A fish-skinned humanoid with a distended belly and bulging, unblinking eyes. It holds a harpoon in webbed fingers.',
    lore: 'Kuo-toa are the mad deep-fish who worship gods of their own imagining. Their collective belief is so powerful it can create actual deities from nothing. They are the ultimate example of how faith shapes reality in the D&D multiverse.',
    tactics: 'Sticky shield grapples. Harpoon and net tactics. Mad fervor from faith. Amphibious.',
    habitat: 'Underground seas, coastal caves, sunken temples',
    abilities: ['Amphibious', 'Sticky shield', 'Divine madness', 'Darkvision'],
    languages: ['Undercommon'],
    senses: ['darkvision 120 ft.', 'passive Perception 14'],
  },
  {
    id: 'ff_kenku', name: 'Kenku', type: 'humanoid (kenku)', size: 'Medium', alignment: 'chaotic neutral',
    cr: 0.25, ac: 13, hp: '13 (3d8)', speed: '30 ft.',
    description: 'A crow-headed humanoid with patchy black feathers and yellow eyes, its beak opening to release another person\'s voice.',
    lore: 'Kenku are cursed bird-people, stripped of their wings and creativity by an ancient crime. They can perfectly mimic any sound they\'ve heard, speaking in stolen voices. They make skilled spies, forgers, and thieves — because they can only build from what they\'ve already seen.',
    tactics: 'Mimicry to confuse and distract. Stealth and ambush. Forgery and deception over direct combat.',
    habitat: 'Cities, underworld, shadow markets',
    abilities: ['Mimicry', 'Forgery', 'Stealth'],
    languages: ['Common', 'Auran', 'understands others but only mimics'],
    senses: ['passive Perception 14'],
  },
  {
    id: 'ff_drow', name: 'Drow (Fiend Folio)', type: 'humanoid (elf)', size: 'Medium', alignment: 'neutral evil',
    cr: 0.25, ac: 15, hp: '13 (3d8)', speed: '30 ft.',
    description: 'A dark elf with obsidian skin and white hair, moving with disturbing silence through the shadows where it belongs.',
    lore: 'The drow were introduced to D&D proper through the Fiend Folio, codifying what had been Greyhawk villains into a full Underdark civilization. They serve the spider-goddess Lolth in a matriarchal society of poison, intrigue, and cruelty.',
    tactics: 'Poisoned crossbows. Darkness and faerie fire spells. Hit-and-run guerrilla warfare.',
    habitat: 'Underdark cities, Lolth temples, caverns',
    abilities: ['Fey ancestry', 'Innate darkness/faerie fire', 'Poison', 'Sunlight sensitivity'],
    languages: ['Elvish', 'Undercommon'],
    senses: ['darkvision 120 ft.', 'passive Perception 12'],
  },
  {
    id: 'ff_hook_horror', name: 'Hook Horror', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 3, ac: 15, hp: '75 (10d10 + 20)', speed: '30 ft., climb 30 ft.',
    description: 'A vulture-headed thing in beetle plate, walking on two legs, with a great curved hook of bone where each hand should be.',
    lore: 'Hook horrors are blind and do not miss. They navigate by sound in caverns too large for any light to matter, clicking their carapaces and reading the returning echo the way a mapmaker reads a chart. A colony announces itself long before it arrives — a rattling, clattering percussion coming down the tunnel from every direction at once, which is the last useful information a party will get.',
    tactics: 'Descends the cavern wall behind the party while the noise ahead of them holds their attention. Hooks a target and hauls them off their feet, then works on them where they have fallen. A silenced party it cannot hear is a party it will walk straight past.',
    habitat: 'Vast Underdark caverns, sinkholes, vertical shafts',
    abilities: ['Echolocation', 'Multiattack (hook/hook)', 'Wall climb', 'Blind (sight useless)'],
    languages: ['Hook Horror'],
    senses: ['blindsight 60 ft.', 'blind beyond that radius', 'passive Perception 13'],
  },
  {
    id: 'ff_necrophidius', name: 'Necrophidius (Death Worm)', type: 'construct', size: 'Medium', alignment: 'unaligned',
    cr: 3, ac: 13, hp: '52 (8d8 + 16)', speed: '30 ft.',
    description: 'A serpent assembled from human vertebrae with a fanged skull at its head, swaying upright and utterly silent.',
    lore: 'The necrophidius is a made thing, and whoever makes one has a specific person in mind. It is given a name, a face or a scent, and it goes; it does not eat, does not tire, and does not stop. It makes no sound at all when it moves, which is the detail every account fixates on — the bones do not click, the joints do not scrape. Assassins\' guilds regard commissioning one as a confession, since nothing else on earth kills quite like that.',
    tactics: 'Sways into the target\'s eyeline and holds it there. The dance paralyses those who watch it, and it bites the paralysed. Pursues one named victim across a continent and ignores everyone else, including anyone standing in the way, unless they strike it first.',
    habitat: 'Assassin workshops, tomb corridors, wherever it was pointed',
    abilities: ['Dance of Death (paralysing sway)', 'Silent movement', 'Paralysing bite', 'Construct immunities'],
    languages: [],
    senses: ['blindsight 30 ft.', 'darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'ff_blindheim', name: 'Blindheim', type: 'monstrosity', size: 'Small', alignment: 'unaligned',
    cr: 1, ac: 13, hp: '22 (5d6 + 5)', speed: '30 ft.',
    description: 'A knee-high frog-man with mottled skin and two enormous eyes that are, at the moment, closed.',
    lore: 'A blindheim\'s eyes emit light as bright as a full noon, and it can open them whenever it likes. It lives in absolute darkness and hunts things that also live in absolute darkness, which makes those eyes both a lantern and a weapon. Deep miners hate them out of all proportion to the threat: the bite is nothing, but a blindheim ambush costs a party their night vision for the rest of the expedition.',
    tactics: 'Waits in a side passage with its eyes shut, opens them at three paces, and blinds the entire front rank at once. Then it eats whoever fell over. Squats and hops away into the dark the moment anything with a reliable light source arrives.',
    habitat: 'Deep caverns, disused mine workings, Underdark side passages',
    abilities: ['Blinding gaze (30 ft. radius)', 'Light immunity', 'Leap', 'Bite'],
    languages: [],
    senses: ['darkvision 90 ft.', 'passive Perception 11'],
  },
  {
    id: 'ff_thought_eater', name: 'Thought Eater', type: 'aberration', size: 'Small', alignment: 'unaligned',
    cr: 2, ac: 12, hp: '27 (6d6 + 6)', speed: '10 ft., fly 30 ft. (Ethereal Plane only)',
    description: 'A gaunt, hairless platypus-thing the size of a badger, faintly visible from the corner of the eye and nowhere else.',
    lore: 'The thought eater grazes on the Ethereal Plane and eats nothing physical. What it eats is preparation — a memorised spell, a rehearsed argument, the shape of a plan. It is not malicious and probably not intelligent; it simply crops what it finds, the way a sheep crops grass, and what it finds are the working memories of anyone thinking hard nearby. Wizards blame apprentices, apprentices blame wizards, and the actual culprit drifts three feet away and slightly out of phase.',
    tactics: 'Never attacks a body. Feeds on the mind, stripping prepared spells and memorised knowledge from anyone it hovers near. Cannot be touched from the Material Plane at all and cannot touch it in return, so the only defence is to stop thinking about anything worth eating.',
    habitat: 'The Ethereal Plane, the border ether around wizards\' towers and libraries',
    abilities: ['Devour thought (erases prepared spells and memories)', 'Ethereal only', 'Cannot be harmed by material weapons', 'Psychic feeding'],
    languages: [],
    senses: ['detect thoughts 60 ft.', 'passive Perception 10'],
  },

  // ═══════════════════════════════════════════════════════
  //  MONSTER MANUAL II (1983)
  // ═══════════════════════════════════════════════════════
  {
    id: 'mm2_behir', name: 'Behir', type: 'monstrosity', size: 'Huge', alignment: 'neutral evil',
    cr: 11, ac: 17, hp: '168 (16d12 + 64)', speed: '50 ft., climb 40 ft.',
    description: 'A forty-foot serpentine horror with a dozen legs and scales of electric blue, lightning crackling along its coils.',
    lore: 'Behirs are apex predators designed by storm giants to hunt dragons. Their hatred of true dragons is so deep it is written in their blood. They swallow prey whole and discharge lightning breath in a devastating line.',
    tactics: 'Lightning breath line. Constricts after swallowing. Multiattack with bite and claws. Climb ceilings to ambush.',
    habitat: 'Mountains, stormy highlands, dragon territories',
    abilities: ['Lightning breath', 'Swallow whole', 'Constrict', 'Multiattack'],
    languages: ['Draconic'],
    senses: ['darkvision 90 ft.', 'passive Perception 16'],
  },
  {
    id: 'mm2_drider', name: 'Drider', type: 'aberration (elf)', size: 'Large', alignment: 'chaotic evil',
    cr: 6, ac: 19, hp: '123 (13d10 + 52)', speed: '30 ft., climb 30 ft.',
    description: 'The punishment of Lolth made flesh — a drow torso fused to a giant spider\'s body, driven mad by the transformation.',
    lore: 'Driders are drow who failed Lolth\'s test. Instead of being killed, they are transformed into half-spider abominations and cast out. They are shunned by drow society and live as outcast hunters in the Underdark, hating all that they once were.',
    tactics: 'Longbow and poisonous bite. Spider climb. Faerie fire and darkness. Ambush from ceilings.',
    habitat: 'Underdark outskirts, wild caverns',
    abilities: ['Spider climb', 'Innate darkness/faerie fire', 'Poison bite', 'Sunlight sensitivity'],
    languages: ['Elvish', 'Undercommon'],
    senses: ['darkvision 120 ft.', 'passive Perception 15'],
  },
  {
    id: 'mm2_dracolisk', name: 'Dracolisk', type: 'dragon', size: 'Large', alignment: 'chaotic evil',
    cr: 7, ac: 16, hp: '105 (10d10 + 50)', speed: '20 ft., fly 40 ft.',
    description: 'The unnatural union of a black dragon and a basilisk — a winged horror whose gaze turns flesh to stone.',
    lore: 'Dracolisks are born from magical experiments fusing dragon and basilisk eggs. They combine the dragon\'s cunning and breath weapon with the basilisk\'s petrifying gaze. They are sterile, hateful of all living things, and terrifyingly effective predators.',
    tactics: 'Petrifying gaze plus acid breath. Flies above prey forcing them to look up. Multiattack.',
    habitat: 'Deep swamps, ruins, dragon lairs',
    abilities: ['Petrifying gaze', 'Acid breath', 'Fly', 'Darkvision'],
    languages: ['understands Draconic'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'mm2_dust_digger', name: 'Dust Digger', type: 'monstrosity', size: 'Medium', alignment: 'unaligned',
    cr: 1, ac: 14, hp: '32 (5d8 + 10)', speed: '10 ft., burrow 10 ft.',
    description: 'A five-tentacled starfish-like creature that buries itself in loose earth, tentacles lying just beneath the surface.',
    lore: 'Dust diggers are desert ambush predators that feel prey through vibrations in the sand. Their five tentacles erupt simultaneously to grab, constrict, and drag their victim into the waiting mouth below.',
    tactics: 'Tentacle grapple from below. Constricts prey while dragging down into its burrow. Tremorsense.',
    habitat: 'Deserts, sandy wastelands, dry plains',
    abilities: ['Burrow ambush', 'Multi-grapple', 'Constrict', 'Tremorsense'],
    languages: [],
    senses: ['tremorsense 60 ft.', 'passive Perception 8'],
  },
  {
    id: 'mm2_froghemoth', name: 'Froghemoth', type: 'monstrosity', size: 'Huge', alignment: 'unaligned',
    cr: 10, ac: 14, hp: '184 (16d12 + 80)', speed: '20 ft., swim 30 ft.',
    description: 'A three-eyed swamp horror — a giant frog body, four tentacles, and a maw that unhinges to swallow a horse.',
    lore: 'The froghemoth is the alien terror of the swamps, perhaps a refugee from another world. Its tentacles grab and its tongue lashes out to drag prey into a gullet that stretches like a snake. It shrugs off fire but is slowed by electricity.',
    tactics: 'Tentacles grapple. Tongue pulls prey into its mouth. Swallow whole. Resistant to fire, slows from lightning.',
    habitat: 'Deep swamps, jungle rivers, alien crash sites',
    abilities: ['Multiattack (tentacles/tongue/bite)', 'Swallow whole', 'Shock susceptibility', 'Amphibious'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'mm2_nabassu', name: 'Nabassu', type: 'fiend (demon)', size: 'Medium', alignment: 'chaotic evil',
    cr: 13, ac: 17, hp: '135 (18d8 + 54)', speed: '40 ft., fly 60 ft.',
    description: 'A bat-winged demon with gaunt limbs and a head like a gargoyle, its eyes reflecting stolen souls.',
    lore: 'Nabassu are demons that grow from feeders on death to winged hunters of souls. They slip onto the material plane through gates of blood and feed until they can manifest fully. A mature nabassu is a predator of living souls, its gaze a death sentence.',
    tactics: 'Death-stealing gaze. Drains life energy with strikes. Grows stronger with each kill. Flies.',
    habitat: 'The Abyss, sites of mass death',
    abilities: ['Death gaze', 'Life drain', 'Soul theft', 'Grow with kills', 'Fly'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    senses: ['darkvision 120 ft.', 'passive Perception 14'],
  },
  {
    id: 'mm2_tarrasque_adnd', name: 'Tarrasque (AD&D)', type: 'monstrosity (titan)', size: 'Gargantuan', alignment: 'unaligned',
    cr: 30, ac: 25, hp: '676 (33d20 + 330)', speed: '40 ft.',
    description: 'The walking apocalypse — 50 feet of claws, teeth, horns, and spiked carapace. Its roar is an earthquake.',
    lore: 'The tarrasque\'s definitive writeup came in MM2. It is a unique creature, perhaps the spawn of a dead god or a weapon that escaped its maker. It sleeps for decades underground, then rises to consume everything in its path. It cannot be truly killed — only forced back into its slumber.',
    tactics: 'Charges the nearest creature. Swallows Medium or smaller targets. Reflective carapace bounces magic. Fears nothing.',
    habitat: 'Unknown — sleeps in the planet\'s core or deepest earth',
    abilities: ['Reflective carapace', 'Swallow whole', 'Frightful presence', 'Legendary resistance', 'Siege monster'],
    languages: [],
    senses: ['blindsight 120 ft.', 'passive Perception 10'],
  },
  {
    id: 'mm2_quickling', name: 'Quickling', type: 'fey', size: 'Tiny', alignment: 'chaotic evil',
    cr: 1, ac: 16, hp: '10 (3d4 + 3)', speed: '120 ft.',
    description: 'A tiny, withered fey moving at a blurring speed, its knife already inside your ribs before you see it move.',
    lore: 'Quicklings are fey cursed with speed — their bodies have withered to tiny, gray forms, but they move faster than any creature their size has a right to. Their speed makes them almost impossible to hit with targeted attacks. They are bitter and cruel.',
    tactics: 'Blurring speed grants incredible AC. Stabs and retreats before retaliation. Covers vast ground in a round.',
    habitat: 'Feywild thickets, cursed forests',
    abilities: ['Blurring speed', 'Fey ancestry', 'Multiattack'],
    languages: ['Common', 'Sylvan'],
    senses: ['passive Perception 12'],
  },
  {
    id: 'mm2_phantom_stalker', name: 'Phantom Stalker', type: 'elemental', size: 'Medium', alignment: 'neutral',
    cr: 4, ac: 14, hp: '58 (9d8 + 18)', speed: '0 ft., fly 40 ft. (hover)',
    description: 'A ghost-shaped flame, visible only as a heat shimmer, tracking its prey with elemental patience.',
    lore: 'Phantom stalkers are fire elementals bound to hunt a specific target, much like invisible stalkers are air-bound hunters. They burn without mercy and cannot be deterred. Their flame body is nearly invisible in bright light.',
    tactics: 'Invisible in bright light. Relentless tracker. Burns target on contact. Ignores obstacles.',
    habitat: 'The Plane of Fire, planes of its target',
    abilities: ['Fire form', 'Invisibility (in light)', 'Faultless tracker', 'Fly'],
    languages: ['Ignan'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'mm2_tomb_tainted', name: 'Tomb Tainted', type: 'undead', size: 'Medium', alignment: 'neutral evil',
    cr: 0.5, ac: 10, hp: '22 (3d8 + 9)', speed: '30 ft.',
    description: 'A corpse animated by the negative energy of its own tomb, with grave dirt still under its fingernails.',
    lore: 'Tomb-tainted are the restless dead, raised not by necromancy but by the sheer evil of their burial sites. They hunger for the warmth of the living and cannot stray far from their grave. Their touch drains life and their wounds heal in darkness.',
    tactics: 'Life-draining touch. Regenerates in darkness. Bound to its tomb site.',
    habitat: 'Cursed tombs, desecrated graveyards, unholy sites',
    abilities: ['Life drain', 'Regeneration in darkness', 'Undead fortitude'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'mm2_chaos_imp', name: 'Chaos Imp', type: 'fiend (demon)', size: 'Tiny', alignment: 'chaotic evil',
    cr: 0.5, ac: 13, hp: '14 (4d4 + 4)', speed: '20 ft., fly 30 ft.',
    description: 'A tiny, bat-winged demon with shifting, melting features and a cackle that scrapes the nerves.',
    lore: 'Chaos imps are the weakest demons, the lowest rung of the Abyss, but they swarm in horrifying numbers. Their very presence warps reality in small ways — a glass becomes poison, a rope becomes a snake, a word becomes a lie.',
    tactics: 'Chaos aura warps surroundings. Swarms overwhelm. Spawns in large groups from chaotic magic.',
    habitat: 'The Abyss, sites of wild magic',
    abilities: ['Chaos aura', 'Fly', 'Swarm', 'Bite'],
    languages: ['Abyssal'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
];