/**
 * Basic / Classic Dungeons & Dragons
 * AC9 Creature Catalogue (1986) and DMR2 Creature Catalog (1993)
 *
 * These books compiled creatures from across the BECMI and Rules Cyclopedia
 * era, including obscure and region-specific monsters.
 */
import type { BestiaryEntry } from '../DnDKnowledge';

export const CLASSIC_BESTIARY: BestiaryEntry[] = [
  // ── AC9 Creature Catalogue (1986) key entries ──
  {
    id: 'cl_shadow_elf', name: 'Shadow Elf', type: 'humanoid (elf)', size: 'Medium', alignment: 'neutral',
    cr: 1, ac: 14, hp: '18 (4d8)', speed: '30 ft.',
    description: 'A pale elf of the deep earth, eyes adapted to utter darkness, moving in silence through stone corridors.',
    lore: 'Shadow elves are the Mystara-specific Underdark elves — the descendants of elves who fled underground to escape a magical cataclysm. Unlike the evil drow of AD&D, shadow elves are morally complex, with their own civilization, religion, and code of honor. They worship a deity of earth and darkness and shun surface light.',
    tactics: 'Darkness spells and shadow magic. Stone-shaping for ambushes. Avoids direct sunlight.',
    habitat: 'Underdark cities, deep caverns, the Shadowlands',
    abilities: ['Innate darkness', 'Stone sense', 'Sunlight sensitivity', 'Shadow step'],
    languages: ['Elvish', 'Shadow Elf dialect'],
    senses: ['darkvision 120 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_lupin', name: 'Lupin', type: 'humanoid (lupin)', size: 'Medium', alignment: 'lawful good',
    cr: 0.5, ac: 13, hp: '13 (3d8)', speed: '30 ft.',
    description: 'A wolf-headed humanoid in rustic clothes, tail wagging slightly as it raises a hand in greeting.',
    lore: 'Lupins are the dog-folk of Mystara, honorable and clan-based, living in the borderlands between human nations and the wilderness. They have an ancient enmity with werewolves — lycanthropes who pervert the canine form. Lupin rangers are among the finest trackers in the known world.',
    tactics: 'Pack tactics. Keen smell for tracking. Loyal to clan. Distrusts lycanthropes.',
    habitat: 'Borderlands, forests, clan villages',
    abilities: ['Keen hearing and smell', 'Pack tactics', 'Lycanthrope hunter'],
    languages: ['Common', 'Lupin'],
    senses: ['passive Perception 15'],
  },
  {
    id: 'cl_rakasta', name: 'Rakasta', type: 'humanoid (rakasta)', size: 'Medium', alignment: 'neutral',
    cr: 0.5, ac: 13, hp: '13 (3d8)', speed: '35 ft.',
    description: 'A feline humanoid with striped fur and retractable claws, eyes gleaming with independent intelligence.',
    lore: 'Rakasta are the cat-folk of Mystara — proud, nomadic, and highly independent. They ride tamed sabre-tooth tigers and fight with paired claws and scimitars. They are deeply spiritual, worshipping the spirits of ancestors and great cats.',
    tactics: 'Pounce and claw. Hit-and-run mounted attacks. Superior night vision. Agile acrobatics.',
    habitat: 'Savannahs, grasslands, desert edges',
    abilities: ['Pounce', 'Claw attacks', 'Darkvision', 'Mounted combat'],
    languages: ['Common', 'Rakasta'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'cl_aranea', name: 'Aranea', type: 'magical beast (shapechanger)', size: 'Medium', alignment: 'neutral',
    cr: 4, ac: 13, hp: '45 (7d8 + 14)', speed: '30 ft., climb 30 ft.',
    description: 'A giant spider that shimmers and reshapes into a robed humanoid, silk trailing from its sleeves.',
    lore: 'Aranea are intelligent spider-people capable of shifting between giant spider, humanoid, and hybrid forms. They are natural sorcerers, their magic inherited through blood. They live in hidden forest communities and are among the most misunderstood of Mystara\'s peoples.',
    tactics: 'Shapechange for deception. Web spells. Poison. Sorcerer spellcasting.',
    habitat: 'Deep forests, hidden valley communities',
    abilities: ['Shapechanger (spider/humanoid/hybrid)', 'Innate sorcery', 'Web', 'Spider climb'],
    languages: ['Common', 'Aranea'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'cl_phaton', name: 'Phaton', type: 'humanoid (phaton)', size: 'Medium', alignment: 'neutral good',
    cr: 2, ac: 13, hp: '33 (6d8 + 6)', speed: '30 ft., fly 40 ft. (with wing-cloak)',
    description: 'A slender, winged humanoid with skin like polished wood and eyes like amber drops.',
    lore: 'Phatons are a fey-touched flying race who live in the high canopies of Mystara\'s greatest forests. They use wing-cloaks that unfurl for short-distance flight. They are peaceful but fiercely territorial, using blowguns tipped with sleeping poison.',
    tactics: 'Blowgun with sleep poison. Swooping hit-and-run. Tree platform ambushes.',
    habitat: 'Forest canopies, high trees',
    abilities: ['Fly (limited)', 'Sleep poison', 'Keen sight'],
    languages: ['Common', 'Phaton'],
    senses: ['passive Perception 15'],
  },
  {
    id: 'cl_hsiao', name: 'Hsiao', type: 'magical beast', size: 'Large', alignment: 'lawful good',
    cr: 4, ac: 14, hp: '52 (8d10 + 8)', speed: '20 ft., fly 60 ft.',
    description: 'A giant owl with intelligent, golden eyes and feathers that seem woven from moonlight.',
    lore: 'Hsiao are the guardian owls of Mystara, wise and fiercely protective of the innocent. They are the patrons of the forest elves and clerics of the celestial order. A hsiao\'s hoot can heal the wounded or frighten evildoers.',
    tactics: 'Swooping claw attacks. Healing hoot. Clerical spellcasting. Defends allies.',
    habitat: 'Sacred groves, ancient forests, elven lands',
    abilities: ['Healing magic', 'Fly', 'Keen sight and hearing', 'Spellcasting (cleric)'],
    languages: ['Common', 'Elvish', 'Hsiao'],
    senses: ['darkvision 120 ft.', 'passive Perception 18'],
  },
  {
    id: 'cl_pegataur', name: 'Pegataur', type: 'monstrosity', size: 'Large', alignment: 'lawful good',
    cr: 5, ac: 16, hp: '85 (10d10 + 30)', speed: '50 ft., fly 80 ft.',
    description: 'A winged centaur — the torso of an elf fused to the body of a winged horse, a lance balanced in one hand.',
    lore: 'Pegataurs are the sky-wardens of Mystara, combining the centaur\'s martial skill with the pegasus\'s gift of flight. They patrol high mountain passes and defend elven kingdoms from aerial threats. They are rare and noble, born from celestial blessings.',
    tactics: 'Aerial charges with lance. Swooping hooves. Bow from the wing.',
    habitat: 'High mountains, cloud peaks, elven skies',
    abilities: ['Fly', 'Lance charge', 'Trample', 'Aerial combat'],
    languages: ['Common', 'Elvish', 'Sylvan'],
    senses: ['passive Perception 16'],
  },
  {
    id: 'cl_chelonian', name: 'Chelonian', type: 'humanoid (chelonian)', size: 'Medium', alignment: 'lawful neutral',
    cr: 2, ac: 18, hp: '32 (5d8 + 10)', speed: '25 ft.',
    description: 'A tortoise-man in plate-like shell armor, slow of foot but steady of purpose.',
    lore: 'Chelonians are the tortoise-folk of Mystara\'s coasts and swamps. Their natural shell provides armor as strong as steel, and their slow, deliberate culture values patience above all. They are master crafters of shell and coral.',
    tactics: 'Natural AC from shell. Slow but crushing melee. Retracts into shell for total defense.',
    habitat: 'Coasts, swamps, slow rivers',
    abilities: ['Shell armor', 'Shell defense', 'Amphibious', 'Crafting'],
    languages: ['Common', 'Chelonian'],
    senses: ['passive Perception 12'],
  },
  {
    id: 'cl_nagpa', name: 'Nagpa', type: 'humanoid (cursed)', size: 'Medium', alignment: 'chaotic evil',
    cr: 6, ac: 15, hp: '90 (12d8 + 36)', speed: '30 ft.',
    description: 'A vulture-headed humanoid in tattered robes, a staff in one gnarled hand and madness in its yellow eyes.',
    lore: 'Nagpa are a race of humanoids cursed by the Immortals for the hubris of their ancient empire. Now they are twisted, vulture-like schemers consumed with hatred for civilization and desperate to undo the curse. Each nagpa is a potent spellcaster who hoards arcane secrets.',
    tactics: 'Arcane spellcasting. Manipulates rather than fights directly. Curses and corrupts.',
    habitat: 'Ruins of their ancient empire, desolate wastelands',
    abilities: ['Arcane spellcasting', 'Curse of ruin', 'Flight', 'Ancient knowledge'],
    languages: ['Common', 'Nagpa', 'three ancient languages'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_pegataur_flame', name: 'Flame Pegataur', type: 'monstrosity', size: 'Large', alignment: 'neutral good',
    cr: 3, ac: 14, hp: '45 (6d10 + 12)', speed: '50 ft.',
    description: 'A centaur-like fire elemental — a horse body of living flame and a humanoid torso wielding a burning spear.',
    lore: 'Flame pegataurs are elemental guardians bound to sacred fires or volcanic chambers. They are not evil, but they are dangerous to approach without proper tribute. They serve as guardians of ancient dwarven forges and elven fire-groves.',
    tactics: 'Fire aura burns nearby creatures. Burning spear. Immune to fire. Healed by flame.',
    habitat: 'Volcanoes, sacred fires, dwarven forges',
    abilities: ['Fire aura', 'Burning weapons', 'Fire immunity', 'Fire healing'],
    languages: ['Ignan', 'Dwarvish'],
    senses: ['darkvision 60 ft.', 'passive Perception 11'],
  },

  // ── DMR2 Creature Catalog (1993) key entries ──
  {
    id: 'dmr2_actaeon', name: 'Actaeon', type: 'humanoid (cursed)', size: 'Medium', alignment: 'neutral',
    cr: 2, ac: 12, hp: '33 (6d8 + 6)', speed: '40 ft.',
    description: 'A stag-headed hunter in leathers, a longbow in hand, moving silently through the forest.',
    lore: 'Actaeons are hunters cursed by forest spirits for over-hunting, transformed into creatures that are neither fully human nor fully beast. They now hunt only those who harm the forest, becoming its protectors. Their antlers grow with each season.',
    tactics: 'Skilled archers. Forest ambush. Antler charge when cornered. Relentless trackers.',
    habitat: 'Deep forests, sacred hunting grounds',
    abilities: ['Skilled archer', 'Forest stalker', 'Antler gore', 'Trackless step'],
    languages: ['Common', 'Sylvan'],
    senses: ['passive Perception 16'],
  },
  {
    id: 'dmr2_geonid', name: 'Geonid', type: 'humanoid', size: 'Small', alignment: 'lawful neutral',
    cr: 0.5, ac: 16, hp: '13 (3d6 + 3)', speed: '20 ft.',
    description: 'A small boulder that unfolds into a rocky humanoid with crystal eyes, perfectly still until it is not.',
    lore: 'Geonids are living stones — patient, slow, and nearly impossible to detect when motionless. They are not hostile but fiercely defend their mountain homes. Their language is a slow vibration through stone that other races find difficult to parse.',
    tactics: 'Perfect stillness for ambush. Stone fists. Retracts into boulder form. Speaks through stone.',
    habitat: 'Mountains, rock slides, stone quarries',
    abilities: ['False appearance (boulder)', 'Stone fists', 'Retract', 'Stone speech'],
    languages: ['Terran (through vibration)'],
    senses: ['tremorsense 60 ft.', 'passive Perception 9'],
  },
  {
    id: 'dmr2_catoblepas', name: 'Catoblepas', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 5, ac: 14, hp: '84 (8d10 + 40)', speed: '30 ft.',
    description: 'A bloated, wildebeest-like creature with a neck too weak for its heavy head, dragging its snout through the swamp. Its gaze is death.',
    lore: 'The catoblepas is the most pathetic-looking monster in the swamps — and one of the deadliest. Its head is too heavy to lift, but if it manages to raise its gaze, that glance means death by rotting from within. Its swamp lairs are surrounded by the fallen.',
    tactics: 'Death gaze if it lifts its head. Stench repels predators. Poisonous swamp gas around it.',
    habitat: 'Fetid swamps, dead marshes',
    abilities: ['Death gaze (when head raised)', 'Stench aura', 'Poison aura'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'dmr2_werebat', name: 'Werebat', type: 'humanoid (shapechanger)', size: 'Medium', alignment: 'neutral evil',
    cr: 3, ac: 13, hp: '58 (9d8 + 18)', speed: '30 ft., fly 40 ft. (bat form)',
    description: 'A humanoid whose form ripples between man and giant bat, with membrane wings that fold like a cape.',
    lore: 'Werebats are lycanthropes of the night sky, spreading their curse through bite. Unlike many lycanthropes, they can take a hybrid form that retains wings and humanoid limbs. They lair in high dark places — bell towers, cave ceilings, and ruined keeps.',
    tactics: 'Aerial ambush. Bite spreads lycanthropy. Sonic shriek disorients. Flies in darkness.',
    habitat: 'Cave ceilings, bell towers, abandoned keeps',
    abilities: ['Shapechanger', 'Fly', 'Lycanthropic bite', 'Echolocation'],
    languages: ['Common'],
    senses: ['blindsight 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'dmr2_coltpixie', name: 'Coltpixie', type: 'fey', size: 'Tiny', alignment: 'chaotic good',
    cr: 0.25, ac: 15, hp: '2 (1d4)', speed: '20 ft., fly 40 ft.',
    description: 'A tiny winged horse with a mane of gossamer and a playful glint in its eyes.',
    lore: 'Coltpixies are miniature pegasi — fey spirits that look exactly like tiny winged foals. They are mischievous, innocent, and adored by fey and children alike. Their whinny can lift spirits and dispel sadness.',
    tactics: 'Fly out of reach. Inspires allies with neigh. Too small and fast to effectively target.',
    habitat: 'Fey meadows, flower fields, enchanted springs',
    abilities: ['Fly', 'Inspirational neigh', 'Tiny', 'Fey mischief'],
    languages: ['Sylvan'],
    senses: ['passive Perception 12'],
  },
  {
    id: 'dmr2_bone_golem', name: 'Bone Golem', type: 'construct', size: 'Medium', alignment: 'neutral',
    cr: 4, ac: 15, hp: '60 (8d8 + 24)', speed: '30 ft.',
    description: 'A skeletal construct cobbled together from the bones of many different creatures, its ribcage clicking as it moves.',
    lore: 'Bone golems are the cheapest golems to construct — assembled from battlefield remains and animated with dark prayer. They are weaker than stone or iron but can be made in numbers. Some are jointed to rearrange into four-legged hunter-killer forms.',
    tactics: 'Multiattack (four bony limbs). Reassembles broken bones. Fear aura of rattling death.',
    habitat: 'Necromancer lairs, bone pits, ossuaries',
    abilities: ['Multiattack', 'Reassemble', 'Bone rattle (fear)', 'Poison immunity'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'dmr2_silver_drake', name: 'Silver Drake', type: 'dragon', size: 'Medium', alignment: 'lawful good',
    cr: 3, ac: 16, hp: '45 (6d10 + 12)', speed: '30 ft., fly 60 ft.',
    description: 'A sleek, silver-scaled drake with intelligent eyes and a breath of sparkling cold.',
    lore: 'Silver drakes are the loyal companions and messengers of silver dragons, smaller and less powerful but sharing their noble spirit. They are often sent to aid adventurers fighting evil. Their cold breath freezes foes solid.',
    tactics: 'Cold breath. Flies and dives. Loyal to its silver dragon master. Aids the worthy.',
    habitat: 'Silver dragon lairs, alpine peaks, cloud aeries',
    abilities: ['Cold breath', 'Fly', 'Keen senses'],
    languages: ['Draconic', 'understands Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'dmr2_zombie_plague', name: 'Plague Zombie', type: 'undead', size: 'Medium', alignment: 'neutral evil',
    cr: 0.5, ac: 7, hp: '22 (3d8 + 9)', speed: '20 ft.',
    description: 'A shambling corpse covered in weeping sores. Its touch spreads the rot that killed it.',
    lore: 'Plague zombies are created not by necromancy but by disease — victims of magical plagues that reanimate the dead. Their rotting touch spreads the contagion, threatening to turn whole villages into shambling hordes. Fire is the only certain cure.',
    tactics: 'Disease spread on hit. Undead fortitude. Swarms. Fire vulnerability.',
    habitat: 'Plague villages, mass graves, cursed battlegrounds',
    abilities: ['Disease spread', 'Undead fortitude', 'Fire vulnerability', 'Swarm'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 6'],
  },
  {
    id: 'dmr2_fungoid', name: 'Fungoid', type: 'plant', size: 'Medium', alignment: 'neutral evil',
    cr: 2, ac: 12, hp: '39 (6d8 + 12)', speed: '25 ft.',
    description: 'A mushroom that walks on root-like legs, its cap opening to reveal a face of fungal folds and sorrow.',
    lore: 'Fungoids are sentient mushroom people born from the decay of great forests. They spread fungal spores that can control the minds of humanoids. They are not malicious — they simply see flesh creatures as temporary vessels for spore propagation.',
    tactics: 'Spore clouds (confusion/control). Decomposing touch. Regenerates in damp darkness.',
    habitat: 'Dying forests, fungal caves, decaying woodlands',
    abilities: ['Spore cloud', 'Zombie fungus (mental control)', 'Regeneration (in damp dark)', 'Plant'],
    languages: ['Fungoid', 'telepathy 30 ft.'],
    senses: ['blindsight 60 ft.', 'passive Perception 11'],
  },
  {
    id: 'dmr2_elder_orb', name: 'Elder Orb', type: 'aberration', size: 'Large', alignment: 'lawful evil',
    cr: 15, ac: 19, hp: '210 (20d10 + 100)', speed: '0 ft., fly 20 ft. (hover)',
    description: 'A beholder ancient beyond counting, its central eye an abyss of negative energy and its eyestalks heavy with death.',
    lore: 'Elder orbs are beholders that have lived so long their antimagic gaze has evolved into pure death magic. They are the feared elders of beholder society, ruling over younger beholders and their slave-races. An elder orb does not merely disintegrate — it unmakes.',
    tactics: 'Death ray central eye. Finger of death and disintegrate eyestalks. Legendary actions. Commands beholders.',
    habitat: 'Deepest Underdark, beholder hive-cities',
    abilities: ['Death gaze', 'Finger of death', 'Disintegrate', 'Legendary resistance', 'Fly'],
    languages: ['Deep Speech', 'Undercommon', 'Beholder'],
    senses: ['darkvision 120 ft.', 'passive Perception 22'],
  },

  // ── Basic Set & Expert Set staples (B/X, BECMI, Rules Cyclopedia) ──
  {
    id: 'cl_thoul', name: 'Thoul', type: 'monstrosity', size: 'Medium', alignment: 'chaotic evil',
    cr: 3, ac: 14, hp: '33 (6d8 + 6)', speed: '30 ft.',
    description: 'What appears at forty paces to be a hobgoblin in mail. At ten paces the skin is wrong — grey, loose, and slowly knitting shut over an old wound.',
    lore: 'Thouls are a wizard\'s crossbreed of ghoul and troll, dressed and drilled to pass for hobgoblins. That disguise is the whole point: a party that has counted three hobgoblins and priced the fight accordingly will commit to melee, and the first paralysing claw arrives two rounds after the decision is irreversible. Old campaigners in the Grand Duchy learned to hesitate before every hobgoblin patrol, which is exactly the tax the thoul was bred to collect.',
    tactics: 'Fights in the front rank like the hobgoblin it resembles. Claws to paralyse, then steps past the frozen body to reach the soft ranks behind. Wounds close between rounds, so a foe who stops attacking to reassess loses everything they gained.',
    habitat: 'Hobgoblin warbands, borderland keeps, ruined wizard holdings',
    abilities: ['Paralysing claw', 'Regeneration 3', 'False appearance (hobgoblin)', 'Multiattack (claw/claw/bite)'],
    languages: ['Goblin', 'Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 11'],
  },
  {
    id: 'cl_rhagodessa', name: 'Rhagodessa', type: 'beast', size: 'Large', alignment: 'unaligned',
    cr: 2, ac: 13, hp: '30 (4d10 + 8)', speed: '45 ft., climb 30 ft.',
    description: 'A pale, hairless solifuge the size of a pony. Its front pair of legs end in fleshy suction pads; the rest of it is jaws.',
    lore: 'The rhagodessa is the reason Karameikan miners work in pairs. It does not stalk — it simply outruns everything in the tunnel, slaps a sucker-leg onto whatever is nearest, and hauls the catch up to its mandibles while still moving. It is blind in the usual sense and hunts entirely by the drum of footsteps on stone, which makes standing perfectly still a genuine and terrifying option.',
    tactics: 'Charges in a straight sprint, faster than an armoured party can scatter. A hit with a sucker-leg means a grapple, and a grappled target is bitten automatically on the following turn. Ignores anyone it has not felt move.',
    habitat: 'Mine shafts, dry caverns, warm underground rubble',
    abilities: ['Sucker-leg grapple', 'Automatic bite vs grappled', 'Sprint', 'Wall climb'],
    languages: [],
    senses: ['tremorsense 60 ft.', 'blindsight 10 ft.', 'passive Perception 8'],
  },
  {
    id: 'cl_cave_locust', name: 'Cave Locust', type: 'beast', size: 'Small', alignment: 'unaligned',
    cr: 0.125, ac: 14, hp: '9 (2d8)', speed: '20 ft., fly 60 ft. (leaps only)',
    description: 'A cricket the length of a forearm, mottled grey, clinging to the ceiling in numbers no one wants to count.',
    lore: 'A single cave locust is nothing — a lantern, a boot, done. A cavern of them is a different animal entirely. They spook as one body, and the sound of four hundred of them launching at once in the dark has broken more expeditions than most monsters on this list. They eat fungus and carrion and cannot properly hurt an armoured adventurer, but a torch is easily knocked from a hand, and a panicked party in a lightless cave is a party that is already lost.',
    tactics: 'Leaps blindly toward light and noise rather than at any particular target. Spits a brown, foul-smelling bile that clings for days and marks the victim for anything with a nose. Never presses an attack — the danger is the stampede, not the bite.',
    habitat: 'Fungus caverns, guano-floored caves, the deep dark',
    abilities: ['Erratic leap', 'Foul bile spit', 'Startle swarm', 'Ceiling cling'],
    languages: [],
    senses: ['blindsight 30 ft.', 'passive Perception 8'],
  },
  {
    id: 'cl_rock_baboon', name: 'Rock Baboon', type: 'beast', size: 'Medium', alignment: 'unaligned',
    cr: 0.25, ac: 13, hp: '13 (3d8)', speed: '40 ft., climb 30 ft.',
    description: 'A six-foot baboon with a grey mane and a length of broken timber held in one hand like a club, screaming from a ledge.',
    lore: 'Rock baboons are the lesson that daylight is not safety. They live in troops of a dozen along cliff roads and quarry edges, they carry sticks and thrown stones, and they are just clever enough to work out that a person on a narrow path cannot easily retreat. Caravan guards on the Duke\'s Road do not treat them as animals; they treat them as bandits with better climbing.',
    tactics: 'Opens with stones thrown from above, then drops into the road behind the party to cut off the way back. Wields clubs with real intent. Breaks and scatters the instant the troop leader falls.',
    habitat: 'Cliff roads, quarries, rocky hills and canyon rims',
    abilities: ['Pack tactics', 'Thrown stones', 'Improvised club', 'Sure-footed climb'],
    languages: [],
    senses: ['passive Perception 13'],
  },
  {
    id: 'cl_living_crystal_statue', name: 'Living Crystal Statue', type: 'construct', size: 'Medium', alignment: 'lawful neutral',
    cr: 3, ac: 16, hp: '45 (6d10 + 12)', speed: '25 ft.',
    description: 'A faceted human figure of clear quartz standing among the cave formations, indistinguishable from them until it turns its head.',
    lore: 'Living statues of rock, iron and crystal were the standard guardians of the old Alphatian houses — cheaper than golems, and patient beyond reckoning. The crystal kind is the worst to meet, because it has no obvious front, no eyes to read, and a body that swallows a blade rather than turning it. A vault sealed nine hundred years ago will still have its crystal statue standing exactly where the last mason left it.',
    tactics: 'Stands motionless until its warded threshold is crossed, then attacks whoever crossed it and no one else. A weapon that hits it lodges in the quartz and must be wrenched free, which costs the wielder their next attack. Fights until shattered; it does not have the concept of losing.',
    habitat: 'Alphatian vaults, sealed tombs, crystal caverns',
    abilities: ['False appearance (crystal formation)', 'Weapon-catching body', 'Immutable form', 'Construct immunities'],
    languages: ['understands its creator\'s orders'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },

  // ── Known World / Mystara regional creatures ──
  {
    id: 'cl_decapus', name: 'Decapus', type: 'monstrosity', size: 'Large', alignment: 'chaotic evil',
    cr: 4, ac: 13, hp: '52 (8d8 + 16)', speed: '20 ft., climb 30 ft.',
    description: 'A hairy purple sac the size of a barrel with ten muscular arms, hanging in the branches directly above where the lantern-light seems to be.',
    lore: 'The decapus is a poor climber, a slow walker, and a superb liar. It projects an image — a campfire through the trees, a lost child, a lantern bobbing on the path ahead — and holds it steady while it positions itself in the canopy above the real route. Woodsmen in the Dymrak forest say you should never walk toward a light you did not see arrive.',
    tactics: 'Sets its illusion, waits directly above the approach, and drops into the middle of the party. Grapples two victims at once with its arms and constricts. Cannot maintain the illusion once it attacks, so it commits fully or not at all.',
    habitat: 'Dense forest canopy, cave mouths, overgrown ruins',
    abilities: ['Illusory lure', 'Multiattack (up to four arms)', 'Constrict (two targets)', 'Drop attack'],
    languages: ['understands Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'cl_kopru', name: 'Kopru', type: 'monstrosity', size: 'Medium', alignment: 'lawful evil',
    cr: 5, ac: 14, hp: '60 (8d10 + 16)', speed: '5 ft., swim 40 ft.',
    description: 'A muscular humanoid torso on a thick eel body that splits into three prehensile tails. Its face is mostly mouth, and its eyes never leave yours.',
    lore: 'The kopru built a city on the Isle of Dread and ruled it through other people\'s hands. They do not need armies; they need one governor, one high priest, one captain of the guard. A kopru\'s domination is not a spell that wears off in an hour — it takes root, and the victim keeps their memories, their skills, and their entire personality, all of it now pointed at serving something in the water they will never mention aloud.',
    tactics: 'Never fights first. Dominates the strongest swimmer or the loudest voice in the party and sends them back at their friends. Retreats into deep water where its tails give it every advantage and where a dominated ally will follow it down.',
    habitat: 'Sunken cities, warm reefs, flooded temple pools of the Isle of Dread',
    abilities: ['Permanent domination', 'Triple tail grapple', 'Amphibious', 'Drag underwater'],
    languages: ['Kopru', 'Common', 'telepathy 100 ft.'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_phanaton', name: 'Phanaton', type: 'humanoid (phanaton)', size: 'Small', alignment: 'neutral good',
    cr: 0.25, ac: 14, hp: '11 (2d6 + 4)', speed: '30 ft., climb 30 ft.',
    description: 'A two-foot creature with a raccoon\'s masked face, a monkey\'s tail, and a membrane of skin stretched between its limbs. It is already looking at your pack.',
    lore: 'Phanatons live in woven villages high in the Isle of Dread canopy, a hundred feet above anything that wants to eat them, and they have been at war with the aranea and the yuan-ti for longer than any of the three can remember. They are not fighters and know it. What they are is the only reliable source of information on the interior of the island, and they will trade it for steel, salt, or a convincing promise about spiders.',
    tactics: 'Glides in, throws a javelin, and is thirty feet up a trunk before the return shot is aimed. Fights only from height and only in numbers. Withdraws the instant a fight becomes fair.',
    habitat: 'Rainforest canopy, jungle villages, the Isle of Dread interior',
    abilities: ['Glide', 'Javelin volley', 'Nimble escape', 'Canopy stealth'],
    languages: ['Phanaton', 'broken Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_hutaakan', name: 'Hutaakan', type: 'humanoid (hutaakan)', size: 'Medium', alignment: 'lawful neutral',
    cr: 2, ac: 15, hp: '33 (6d8 + 6)', speed: '30 ft.',
    description: 'A tall figure with the head of a jackal, robed in linen dyed a colour no living dyer can reproduce, holding a rod of office.',
    lore: 'The Hutaaka were the priest-kings of a hidden valley for a thousand years, and their subjects were the ancestors of half the human villages in Karameikos. Then the subjects revolted, and the Hutaaka sealed the valley and have been arguing about it ever since. They regard outsiders as an administrative problem. Every Hutaakan you meet is measuring you against a legal code written before your nation had a name.',
    tactics: 'Fights defensively and by the book — formation, ranged support, prepared ground. Prefers to bind or drive off rather than kill, because a corpse cannot be tried. Calls on ancestral wards when its temple is threatened.',
    habitat: 'The sealed valley, cliff temples, terraced river towns',
    abilities: ['Ritual spellcasting', 'Temple ward', 'Formation drill', 'Keen smell'],
    languages: ['Hutaakan', 'Traldar', 'Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_enduk', name: 'Enduk', type: 'monstrosity', size: 'Large', alignment: 'lawful good',
    cr: 4, ac: 16, hp: '68 (8d10 + 24)', speed: '30 ft., fly 60 ft.',
    description: 'A bull-headed giant in bronze scale, with a pair of great feathered wings folded flat against its back and a mace across its shoulder.',
    lore: 'The Enduks ruled Nimmur and lost it. Their empire was betrayed from below by the manscorpions they had raised up as servants, and the survivors fled to the high mesas, where they have spent the centuries maintaining a court, a liturgy, and a war they cannot win. An Enduk is unfailingly courteous, unfailingly grim, and will absolutely march to its death over a point of honour.',
    tactics: 'Opens from the air with a diving mace strike, then lands in a shield line and holds. Will not break formation, will not retreat, will not leave a fallen comrade. Manscorpions read all three of these as weaknesses, and are usually right.',
    habitat: 'High mesas above Nimmur, cliff-cut fortresses, sky temples',
    abilities: ['Flight', 'Diving charge', 'Shield line', 'Radiant mace'],
    languages: ['Enduk', 'Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 15'],
  },
  {
    id: 'cl_manscorpion', name: 'Manscorpion', type: 'monstrosity', size: 'Large', alignment: 'lawful evil',
    cr: 5, ac: 16, hp: '76 (9d10 + 27)', speed: '40 ft.',
    description: 'A human torso rising from the body of a black scorpion, tail arched overhead, bearing a bronze standard of a sun with no light in it.',
    lore: 'The manscorpions of Nimmur were made to serve the winged Enduks and took the country instead. They kept the temples, the calendar and the bureaucracy, and simply changed which god the sun belonged to. Their society is rigidly ordered and utterly without mercy in a way that reads, from the outside, as a kind of terrible competence. They have never once broken a treaty; they simply write treaties no one else would sign.',
    tactics: 'Fights in disciplined ranks with spear and shield while the tails work over the top of the line. Targets officers and spellcasters first, by doctrine rather than instinct. Poison is meant to incapacitate for capture — Nimmur prefers prisoners.',
    habitat: 'Nimmur, sun temples, desert cities of black stone',
    abilities: ['Poison sting (paralytic)', 'Spear and shield drill', 'Pincer grapple', 'Sunless faith (fear immunity)'],
    languages: ['Nimmurian', 'Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'cl_gurrash', name: 'Gurrash', type: 'humanoid (gator-kin)', size: 'Medium', alignment: 'neutral evil',
    cr: 2, ac: 14, hp: '39 (6d8 + 12)', speed: '30 ft., swim 30 ft.',
    description: 'An alligator standing upright, hide crusted with dried mud, a stone-headed axe in its claws and a necklace of teeth that are not its own.',
    lore: 'The gurrash hold the Malpheggi swamp and have held it against three separate Karameikan expeditions, largely by never once fighting on dry ground. They are not stupid and they are not savages — they simply live in a place where every advantage belongs to whoever is already in the water. They trade with the swamp\'s human squatters and eat them in roughly equal measure, depending on the season.',
    tactics: 'Waits submerged with only the eyes above the surface until the party is committed to the crossing. Drags a single victim under and holds them there while the rest of the band harries the bank. Will not pursue more than a spear\'s throw from open water.',
    habitat: 'Malpheggi swamp, mangrove channels, flooded ruins',
    abilities: ['Hold breath (15 min)', 'Ambush from water', 'Drag under', 'Stone axe'],
    languages: ['Gurrash', 'broken Common'],
    senses: ['darkvision 30 ft.', 'passive Perception 12'],
  },
  {
    id: 'cl_diaboli', name: 'Diaboli', type: 'humanoid (planar)', size: 'Medium', alignment: 'neutral',
    cr: 3, ac: 14, hp: '45 (7d8 + 14)', speed: '30 ft.',
    description: 'A slim blue-skinned figure with backswept horns, a barbed tail, and an expression of profound and weary patience.',
    lore: 'The diaboli come from a neighbouring dimension where they are the ordinary people, and they have spent a great deal of effort trying to explain this. It has not worked. They arrive as merchants, scholars and gate-wardens, and are met with holy water and torches by villages that have never seen an actual fiend. Some diaboli have given up and become exactly what everyone insists they already are, which is the whole tragedy in one sentence.',
    tactics: 'Talks first, and keeps talking well past the point most creatures would have drawn steel. Steps sideways through a dimensional seam to break contact rather than escalate. Fights only when the gate home is threatened, and fights very well.',
    habitat: 'The Dimension of Nightmares, planar crossings, gate-towns',
    abilities: ['Dimensional step', 'Innate gate-sense', 'Charm resistance', 'Rapier and tail'],
    languages: ['Diabolic', 'Common', 'two others'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },

  // ── Creature Catalogue oddities ──
  {
    id: 'cl_velya', name: 'Velya', type: 'undead', size: 'Medium', alignment: 'chaotic evil',
    cr: 8, ac: 16, hp: '105 (14d8 + 42)', speed: '20 ft., swim 40 ft.',
    description: 'A drowned nobleman in the rotted brocade of two centuries ago, hair drifting upward, moving through the water without disturbing it.',
    lore: 'The velya is what a vampire becomes when it dies at sea. It cannot cross onto dry land, cannot enter a house, cannot be invited anywhere — the whole social predation of vampirism is closed to it, and what is left is a two-hundred-year grudge with gills. Velyas haunt the wrecks they went down in and take their victims from ships\' rails at night. Coastal towns in the Minrothad Guilds still weight their coffins.',
    tactics: 'Rises against the hull and takes whoever is leaning over the side, dragging them under before they can shout. Drains blood in the water, where a victim cannot fight and cannot breathe. Retreats into the wreck at dawn and is effectively unkillable there without diving gear.',
    habitat: 'Shipwrecks, harbour bottoms, drowned coastal manors',
    abilities: ['Blood drain (underwater)', 'Bound to water', 'Charm gaze', 'Regeneration (in seawater)'],
    languages: ['the languages it knew in life'],
    senses: ['darkvision 120 ft.', 'passive Perception 15'],
  },
  {
    id: 'cl_wichtlin', name: 'Wichtlin', type: 'undead', size: 'Medium', alignment: 'chaotic evil',
    cr: 5, ac: 15, hp: '71 (11d8 + 22)', speed: '0 ft., fly 40 ft. (hover)',
    description: 'The ghost of an elf, still beautiful, still armed, and looking at you with the specific hatred of someone who knows exactly whose fault this is.',
    lore: 'When an elf dies with a grievance large enough, it does not go where elves go. Wichtlin haunt the woods their people abandoned and the halls their people lost, and they are dangerous in proportion to how justified they are. They cannot be reasoned with about the grievance — that is the entire substance of what remains — but they can occasionally be redirected onto whoever is currently occupying the place they died defending.',
    tactics: 'Opens with a wail that freezes the living in place, then closes on whoever is holding a weapon it recognises. Passes through walls to reach a fleeing target. Cannot be permanently laid to rest until the wrong is answered, and it knows this.',
    habitat: 'Abandoned elven halls, burned groves, contested woodland',
    abilities: ['Paralysing wail', 'Incorporeal movement', 'Chilling touch', 'Grudge-bound (reforms nightly)'],
    languages: ['Elvish'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_malfera', name: 'Malfera', type: 'aberration', size: 'Large', alignment: 'chaotic evil',
    cr: 6, ac: 16, hp: '95 (10d10 + 40)', speed: '30 ft.',
    description: 'A hunched, tusked thing with a mouth ringed by short tentacles and hands too large for its arms. It smells of ozone and spoiled fruit.',
    lore: 'Malferas are not native to anywhere. They come through when a summoning goes slightly wrong — never entirely wrong, which is the trouble, because the ritual appears to have worked and the cult notices the substitution somewhat later. They are strong, cunning enough to be patient, and hungry in a way that has nothing to do with food. A malfera left alone in a town will still be there in a month, and the town will not.',
    tactics: 'Grapples with its oversized hands and applies the mouth-tentacles at leisure. Shrugs off ordinary steel. Hunts by scent through walls and does not lose a trail. Cannot be banished by the rite that summoned it, which cults consistently fail to check beforehand.',
    habitat: 'The Dimension of Nightmares, botched summoning circles, cult cellars',
    abilities: ['Tentacle maw', 'Crushing grapple', 'Resistance to nonmagical weapons', 'Keen scent (through stone)'],
    languages: ['Diabolic', 'understands Common'],
    senses: ['darkvision 90 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_nuckalavee', name: 'Nuckalavee', type: 'fey', size: 'Large', alignment: 'chaotic evil',
    cr: 7, ac: 15, hp: '114 (12d10 + 48)', speed: '50 ft., swim 40 ft.',
    description: 'A skinless horse with a skinless rider grown out of its back, sinew and vein exposed, one vast eye burning red in a head that lolls on its neck.',
    lore: 'The nuckalavee comes out of the sea and it kills crops. That is the whole of its purpose as far as anyone has ever determined — not livestock, not people first, but the harvest, blighted by its breath for a mile in every direction it walks. Coastal villages know two facts about it and both are true: it will not cross running fresh water, and it will not stop until it is stopped. Every stream and burn on that coastline was dug by someone who learned this the hard way.',
    tactics: 'Rides down the fastest runner first, purely to establish that no one is going to outrun it. Its breath withers plants, sickens animals and rots wounds. Refuses to cross running fresh water even to finish a kill, which is the only lever anyone has ever had on it.',
    habitat: 'Sea caves, storm coasts, the fields half a mile inland',
    abilities: ['Blighting breath', 'Trample', 'Cannot cross running fresh water', 'Terrifying appearance'],
    languages: ['Sylvan'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'cl_mujina', name: 'Mujina', type: 'monstrosity (shapechanger)', size: 'Medium', alignment: 'neutral evil',
    cr: 4, ac: 14, hp: '60 (8d8 + 24)', speed: '30 ft.',
    description: 'A well-dressed traveller who turns around at your greeting. Where the face should be there is smooth, featureless skin.',
    lore: 'A mujina can wear any humanoid face it has seen, and does, right up until the moment it decides the performance is over. It takes the face off in front of you. This is not a tactical choice so much as the thing it enjoys most, and it is a genuinely effective weapon — grown warriors have run into the sea. Mujina work alone, take positions of trust, and are almost never uncovered by anyone who lives to report it.',
    tactics: 'Infiltrates first and fights second, often after weeks in a household. Reveals its blank face at the moment of ambush to break the party\'s nerve, then attacks whoever froze. Kills with strangling hands rather than weapons and takes the face of the last thing it killed.',
    habitat: 'Roadside inns, noble households, mountain passes at dusk',
    abilities: ['Face-stealing shapechange', 'Faceless reveal (fear)', 'Strangling grapple', 'Perfect mimicry of voice'],
    languages: ['Common', 'plus any it has worn'],
    senses: ['darkvision 60 ft.', 'passive Perception 15'],
  },
  {
    id: 'cl_sollux', name: 'Sollux', type: 'celestial', size: 'Medium', alignment: 'lawful good',
    cr: 6, ac: 17, hp: '82 (11d8 + 33)', speed: '30 ft., fly 40 ft.',
    description: 'A humanoid outline made of standing daylight, too bright to look at directly and casting no shadow of its own.',
    lore: 'The Sollux call themselves the Children of the Sun and regard darkness not as an absence but as an occupying force. This makes them superb allies against the undead and exhausting company for everyone else, since a Sollux considers a closed shutter a small moral failure. They cannot be lied to in daylight, will not enter a lightless place without a stated purpose, and burn out utterly rather than be extinguished.',
    tactics: 'Radiates light that suppresses undead and blinds those that thrive in the dark. Strikes with hands of solid glare. Grows measurably stronger under open sky and weaker underground, and will pick the battlefield accordingly if allowed.',
    habitat: 'Sun temples, mountain summits, anywhere the sky is unobstructed',
    abilities: ['Blinding radiance', 'Radiant strike', 'Undead suppression aura', 'Weakened in darkness'],
    languages: ['Celestial', 'Common'],
    senses: ['truesight 30 ft.', 'passive Perception 16'],
  },
  {
    id: 'cl_gargantua', name: 'Gargantua', type: 'monstrosity (gargantua)', size: 'Gargantuan', alignment: 'unaligned',
    cr: 11, ac: 15, hp: '210 (15d20 + 60)', speed: '40 ft.',
    description: 'A perfectly ordinary creature — a spider, a toad, a crayfish — rendered at ninety feet, with everything that implies about the sound it makes when it moves.',
    lore: 'Gargantua are not a species. They are an accident of the Immortals, or of a wild magic node, or of an experiment whose notes were burned: a normal animal scaled up until the square-cube law should have killed it and somehow did not. The creature\'s instincts are unchanged, which is the horror of it. A gargantuan toad still just sits there waiting for something to move. It is simply that now the something is a cart.',
    tactics: 'Behaves precisely as its ordinary counterpart does, which makes it predictable and does not remotely help. Its attacks flatten armoured targets outright and its bulk collapses the terrain it fights on. Ordinary weapons do work; there is just a great deal of it.',
    habitat: 'Wild magic zones, Immortal experiment sites, isolated valleys',
    abilities: ['Colossal frame', 'Trample', 'Siege damage to structures', 'Unchanged animal instincts'],
    languages: [],
    senses: ['as the base creature', 'passive Perception 10'],
  },
];