/**
 * Basic / Classic Dungeons & Dragons
 * AC9 Creature Catalogue (1986) and DMR2 Creature Catalog (1993)
 *
 * These books compiled creatures from across the BECMI and Rules Cyclopedia
 * era, including obscure and region-specific monsters.
 */
import type { BestiaryEntry } from '../DnDKnowledge';

export const CLASSIC_BESTIARY: BestiaryEntry[] = [
  // ── AC9 Creature Catalogue (1986) key entries ──
  {
    id: 'cl_shadow_elf', name: 'Shadow Elf', type: 'humanoid (elf)', size: 'Medium', alignment: 'neutral',
    cr: 1, ac: 14, hp: '18 (4d8)', speed: '30 ft.',
    description: 'A pale elf of the deep earth, eyes adapted to utter darkness, moving in silence through stone corridors.',
    lore: 'Shadow elves are the Mystara-specific Underdark elves — the descendants of elves who fled underground to escape a magical cataclysm. Unlike the evil drow of AD&D, shadow elves are morally complex, with their own civilization, religion, and code of honor. They worship a deity of earth and darkness and shun surface light.',
    tactics: 'Darkness spells and shadow magic. Stone-shaping for ambushes. Avoids direct sunlight.',
    habitat: 'Underdark cities, deep caverns, the Shadowlands',
    abilities: ['Innate darkness', 'Stone sense', 'Sunlight sensitivity', 'Shadow step'],
    languages: ['Elvish', 'Shadow Elf dialect'],
    senses: ['darkvision 120 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_lupin', name: 'Lupin', type: 'humanoid (lupin)', size: 'Medium', alignment: 'lawful good',
    cr: 0.5, ac: 13, hp: '13 (3d8)', speed: '30 ft.',
    description: 'A wolf-headed humanoid in rustic clothes, tail wagging slightly as it raises a hand in greeting.',
    lore: 'Lupins are the dog-folk of Mystara, honorable and clan-based, living in the borderlands between human nations and the wilderness. They have an ancient enmity with werewolves — lycanthropes who pervert the canine form. Lupin rangers are among the finest trackers in the known world.',
    tactics: 'Pack tactics. Keen smell for tracking. Loyal to clan. Distrusts lycanthropes.',
    habitat: 'Borderlands, forests, clan villages',
    abilities: ['Keen hearing and smell', 'Pack tactics', 'Lycanthrope hunter'],
    languages: ['Common', 'Lupin'],
    senses: ['passive Perception 15'],
  },
  {
    id: 'cl_rakasta', name: 'Rakasta', type: 'humanoid (rakasta)', size: 'Medium', alignment: 'neutral',
    cr: 0.5, ac: 13, hp: '13 (3d8)', speed: '35 ft.',
    description: 'A feline humanoid with striped fur and retractable claws, eyes gleaming with independent intelligence.',
    lore: 'Rakasta are the cat-folk of Mystara — proud, nomadic, and highly independent. They ride tamed sabre-tooth tigers and fight with paired claws and scimitars. They are deeply spiritual, worshipping the spirits of ancestors and great cats.',
    tactics: 'Pounce and claw. Hit-and-run mounted attacks. Superior night vision. Agile acrobatics.',
    habitat: 'Savannahs, grasslands, desert edges',
    abilities: ['Pounce', 'Claw attacks', 'Darkvision', 'Mounted combat'],
    languages: ['Common', 'Rakasta'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'cl_aranea', name: 'Aranea', type: 'magical beast (shapechanger)', size: 'Medium', alignment: 'neutral',
    cr: 4, ac: 13, hp: '45 (7d8 + 14)', speed: '30 ft., climb 30 ft.',
    description: 'A giant spider that shimmers and reshapes into a robed humanoid, silk trailing from its sleeves.',
    lore: 'Aranea are intelligent spider-people capable of shifting between giant spider, humanoid, and hybrid forms. They are natural sorcerers, their magic inherited through blood. They live in hidden forest communities and are among the most misunderstood of Mystara\'s peoples.',
    tactics: 'Shapechange for deception. Web spells. Poison. Sorcerer spellcasting.',
    habitat: 'Deep forests, hidden valley communities',
    abilities: ['Shapechanger (spider/humanoid/hybrid)', 'Innate sorcery', 'Web', 'Spider climb'],
    languages: ['Common', 'Aranea'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'cl_phaton', name: 'Phaton', type: 'humanoid (phaton)', size: 'Medium', alignment: 'neutral good',
    cr: 2, ac: 13, hp: '33 (6d8 + 6)', speed: '30 ft., fly 40 ft. (with wing-cloak)',
    description: 'A slender, winged humanoid with skin like polished wood and eyes like amber drops.',
    lore: 'Phatons are a fey-touched flying race who live in the high canopies of Mystara\'s greatest forests. They use wing-cloaks that unfurl for short-distance flight. They are peaceful but fiercely territorial, using blowguns tipped with sleeping poison.',
    tactics: 'Blowgun with sleep poison. Swooping hit-and-run. Tree platform ambushes.',
    habitat: 'Forest canopies, high trees',
    abilities: ['Fly (limited)', 'Sleep poison', 'Keen sight'],
    languages: ['Common', 'Phaton'],
    senses: ['passive Perception 15'],
  },
  {
    id: 'cl_hsiao', name: 'Hsiao', type: 'magical beast', size: 'Large', alignment: 'lawful good',
    cr: 4, ac: 14, hp: '52 (8d10 + 8)', speed: '20 ft., fly 60 ft.',
    description: 'A giant owl with intelligent, golden eyes and feathers that seem woven from moonlight.',
    lore: 'Hsiao are the guardian owls of Mystara, wise and fiercely protective of the innocent. They are the patrons of the forest elves and clerics of the celestial order. A hsiao\'s hoot can heal the wounded or frighten evildoers.',
    tactics: 'Swooping claw attacks. Healing hoot. Clerical spellcasting. Defends allies.',
    habitat: 'Sacred groves, ancient forests, elven lands',
    abilities: ['Healing magic', 'Fly', 'Keen sight and hearing', 'Spellcasting (cleric)'],
    languages: ['Common', 'Elvish', 'Hsiao'],
    senses: ['darkvision 120 ft.', 'passive Perception 18'],
  },
  {
    id: 'cl_pegataur', name: 'Pegataur', type: 'monstrosity', size: 'Large', alignment: 'lawful good',
    cr: 5, ac: 16, hp: '85 (10d10 + 30)', speed: '50 ft., fly 80 ft.',
    description: 'A winged centaur — the torso of an elf fused to the body of a winged horse, a lance balanced in one hand.',
    lore: 'Pegataurs are the sky-wardens of Mystara, combining the centaur\'s martial skill with the pegasus\'s gift of flight. They patrol high mountain passes and defend elven kingdoms from aerial threats. They are rare and noble, born from celestial blessings.',
    tactics: 'Aerial charges with lance. Swooping hooves. Bow from the wing.',
    habitat: 'High mountains, cloud peaks, elven skies',
    abilities: ['Fly', 'Lance charge', 'Trample', 'Aerial combat'],
    languages: ['Common', 'Elvish', 'Sylvan'],
    senses: ['passive Perception 16'],
  },
  {
    id: 'cl_chelonian', name: 'Chelonian', type: 'humanoid (chelonian)', size: 'Medium', alignment: 'lawful neutral',
    cr: 2, ac: 18, hp: '32 (5d8 + 10)', speed: '25 ft.',
    description: 'A tortoise-man in plate-like shell armor, slow of foot but steady of purpose.',
    lore: 'Chelonians are the tortoise-folk of Mystara\'s coasts and swamps. Their natural shell provides armor as strong as steel, and their slow, deliberate culture values patience above all. They are master crafters of shell and coral.',
    tactics: 'Natural AC from shell. Slow but crushing melee. Retracts into shell for total defense.',
    habitat: 'Coasts, swamps, slow rivers',
    abilities: ['Shell armor', 'Shell defense', 'Amphibious', 'Crafting'],
    languages: ['Common', 'Chelonian'],
    senses: ['passive Perception 12'],
  },
  {
    id: 'cl_nagpa', name: 'Nagpa', type: 'humanoid (cursed)', size: 'Medium', alignment: 'chaotic evil',
    cr: 6, ac: 15, hp: '90 (12d8 + 36)', speed: '30 ft.',
    description: 'A vulture-headed humanoid in tattered robes, a staff in one gnarled hand and madness in its yellow eyes.',
    lore: 'Nagpa are a race of humanoids cursed by the Immortals for the hubris of their ancient empire. Now they are twisted, vulture-like schemers consumed with hatred for civilization and desperate to undo the curse. Each nagpa is a potent spellcaster who hoards arcane secrets.',
    tactics: 'Arcane spellcasting. Manipulates rather than fights directly. Curses and corrupts.',
    habitat: 'Ruins of their ancient empire, desolate wastelands',
    abilities: ['Arcane spellcasting', 'Curse of ruin', 'Flight', 'Ancient knowledge'],
    languages: ['Common', 'Nagpa', 'three ancient languages'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'cl_pegataur_flame', name: 'Flame Pegataur', type: 'monstrosity', size: 'Large', alignment: 'neutral good',
    cr: 3, ac: 14, hp: '45 (6d10 + 12)', speed: '50 ft.',
    description: 'A centaur-like fire elemental — a horse body of living flame and a humanoid torso wielding a burning spear.',
    lore: 'Flame pegataurs are elemental guardians bound to sacred fires or volcanic chambers. They are not evil, but they are dangerous to approach without proper tribute. They serve as guardians of ancient dwarven forges and elven fire-groves.',
    tactics: 'Fire aura burns nearby creatures. Burning spear. Immune to fire. Healed by flame.',
    habitat: 'Volcanoes, sacred fires, dwarven forges',
    abilities: ['Fire aura', 'Burning weapons', 'Fire immunity', 'Fire healing'],
    languages: ['Ignan', 'Dwarvish'],
    senses: ['darkvision 60 ft.', 'passive Perception 11'],
  },

  // ── DMR2 Creature Catalog (1993) key entries ──
  {
    id: 'dmr2_actaeon', name: 'Actaeon', type: 'humanoid (cursed)', size: 'Medium', alignment: 'neutral',
    cr: 2, ac: 12, hp: '33 (6d8 + 6)', speed: '40 ft.',
    description: 'A stag-headed hunter in leathers, a longbow in hand, moving silently through the forest.',
    lore: 'Actaeons are hunters cursed by forest spirits for over-hunting, transformed into creatures that are neither fully human nor fully beast. They now hunt only those who harm the forest, becoming its protectors. Their antlers grow with each season.',
    tactics: 'Skilled archers. Forest ambush. Antler charge when cornered. Relentless trackers.',
    habitat: 'Deep forests, sacred hunting grounds',
    abilities: ['Skilled archer', 'Forest stalker', 'Antler gore', 'Trackless step'],
    languages: ['Common', 'Sylvan'],
    senses: ['passive Perception 16'],
  },
  {
    id: 'dmr2_geonid', name: 'Geonid', type: 'humanoid', size: 'Small', alignment: 'lawful neutral',
    cr: 0.5, ac: 16, hp: '13 (3d6 + 3)', speed: '20 ft.',
    description: 'A small boulder that unfolds into a rocky humanoid with crystal eyes, perfectly still until it is not.',
    lore: 'Geonids are living stones — patient, slow, and nearly impossible to detect when motionless. They are not hostile but fiercely defend their mountain homes. Their language is a slow vibration through stone that other races find difficult to parse.',
    tactics: 'Perfect stillness for ambush. Stone fists. Retracts into boulder form. Speaks through stone.',
    habitat: 'Mountains, rock slides, stone quarries',
    abilities: ['False appearance (boulder)', 'Stone fists', 'Retract', 'Stone speech'],
    languages: ['Terran (through vibration)'],
    senses: ['tremorsense 60 ft.', 'passive Perception 9'],
  },
  {
    id: 'dmr2_catoblepas', name: 'Catoblepas', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 5, ac: 14, hp: '84 (8d10 + 40)', speed: '30 ft.',
    description: 'A bloated, wildebeest-like creature with a neck too weak for its heavy head, dragging its snout through the swamp. Its gaze is death.',
    lore: 'The catoblepas is the most pathetic-looking monster in the swamps — and one of the deadliest. Its head is too heavy to lift, but if it manages to raise its gaze, that glance means death by rotting from within. Its swamp lairs are surrounded by the fallen.',
    tactics: 'Death gaze if it lifts its head. Stench repels predators. Poisonous swamp gas around it.',
    habitat: 'Fetid swamps, dead marshes',
    abilities: ['Death gaze (when head raised)', 'Stench aura', 'Poison aura'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'dmr2_werebat', name: 'Werebat', type: 'humanoid (shapechanger)', size: 'Medium', alignment: 'neutral evil',
    cr: 3, ac: 13, hp: '58 (9d8 + 18)', speed: '30 ft., fly 40 ft. (bat form)',
    description: 'A humanoid whose form ripples between man and giant bat, with membrane wings that fold like a cape.',
    lore: 'Werebats are lycanthropes of the night sky, spreading their curse through bite. Unlike many lycanthropes, they can take a hybrid form that retains wings and humanoid limbs. They lair in high dark places — bell towers, cave ceilings, and ruined keeps.',
    tactics: 'Aerial ambush. Bite spreads lycanthropy. Sonic shriek disorients. Flies in darkness.',
    habitat: 'Cave ceilings, bell towers, abandoned keeps',
    abilities: ['Shapechanger', 'Fly', 'Lycanthropic bite', 'Echolocation'],
    languages: ['Common'],
    senses: ['blindsight 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'dmr2_coltpixie', name: 'Coltpixie', type: 'fey', size: 'Tiny', alignment: 'chaotic good',
    cr: 0.25, ac: 15, hp: '2 (1d4)', speed: '20 ft., fly 40 ft.',
    description: 'A tiny winged horse with a mane of gossamer and a playful glint in its eyes.',
    lore: 'Coltpixies are miniature pegasi — fey spirits that look exactly like tiny winged foals. They are mischievous, innocent, and adored by fey and children alike. Their whinny can lift spirits and dispel sadness.',
    tactics: 'Fly out of reach. Inspires allies with neigh. Too small and fast to effectively target.',
    habitat: 'Fey meadows, flower fields, enchanted springs',
    abilities: ['Fly', 'Inspirational neigh', 'Tiny', 'Fey mischief'],
    languages: ['Sylvan'],
    senses: ['passive Perception 12'],
  },
  {
    id: 'dmr2_bone_golem', name: 'Bone Golem', type: 'construct', size: 'Medium', alignment: 'neutral',
    cr: 4, ac: 15, hp: '60 (8d8 + 24)', speed: '30 ft.',
    description: 'A skeletal construct cobbled together from the bones of many different creatures, its ribcage clicking as it moves.',
    lore: 'Bone golems are the cheapest golems to construct — assembled from battlefield remains and animated with dark prayer. They are weaker than stone or iron but can be made in numbers. Some are jointed to rearrange into four-legged hunter-killer forms.',
    tactics: 'Multiattack (four bony limbs). Reassembles broken bones. Fear aura of rattling death.',
    habitat: 'Necromancer lairs, bone pits, ossuaries',
    abilities: ['Multiattack', 'Reassemble', 'Bone rattle (fear)', 'Poison immunity'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'dmr2_silver_drake', name: 'Silver Drake', type: 'dragon', size: 'Medium', alignment: 'lawful good',
    cr: 3, ac: 16, hp: '45 (6d10 + 12)', speed: '30 ft., fly 60 ft.',
    description: 'A sleek, silver-scaled drake with intelligent eyes and a breath of sparkling cold.',
    lore: 'Silver drakes are the loyal companions and messengers of silver dragons, smaller and less powerful but sharing their noble spirit. They are often sent to aid adventurers fighting evil. Their cold breath freezes foes solid.',
    tactics: 'Cold breath. Flies and dives. Loyal to its silver dragon master. Aids the worthy.',
    habitat: 'Silver dragon lairs, alpine peaks, cloud aeries',
    abilities: ['Cold breath', 'Fly', 'Keen senses'],
    languages: ['Draconic', 'understands Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'dmr2_zombie_plague', name: 'Plague Zombie', type: 'undead', size: 'Medium', alignment: 'neutral evil',
    cr: 0.5, ac: 7, hp: '22 (3d8 + 9)', speed: '20 ft.',
    description: 'A shambling corpse covered in weeping sores. Its touch spreads the rot that killed it.',
    lore: 'Plague zombies are created not by necromancy but by disease — victims of magical plagues that reanimate the dead. Their rotting touch spreads the contagion, threatening to turn whole villages into shambling hordes. Fire is the only certain cure.',
    tactics: 'Disease spread on hit. Undead fortitude. Swarms. Fire vulnerability.',
    habitat: 'Plague villages, mass graves, cursed battlegrounds',
    abilities: ['Disease spread', 'Undead fortitude', 'Fire vulnerability', 'Swarm'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 6'],
  },
  {
    id: 'dmr2_fungoid', name: 'Fungoid', type: 'plant', size: 'Medium', alignment: 'neutral evil',
    cr: 2, ac: 12, hp: '39 (6d8 + 12)', speed: '25 ft.',
    description: 'A mushroom that walks on root-like legs, its cap opening to reveal a face of fungal folds and sorrow.',
    lore: 'Fungoids are sentient mushroom people born from the decay of great forests. They spread fungal spores that can control the minds of humanoids. They are not malicious — they simply see flesh creatures as temporary vessels for spore propagation.',
    tactics: 'Spore clouds (confusion/control). Decomposing touch. Regenerates in damp darkness.',
    habitat: 'Dying forests, fungal caves, decaying woodlands',
    abilities: ['Spore cloud', 'Zombie fungus (mental control)', 'Regeneration (in damp dark)', 'Plant'],
    languages: ['Fungoid', 'telepathy 30 ft.'],
    senses: ['blindsight 60 ft.', 'passive Perception 11'],
  },
  {
    id: 'dmr2_elder_orb', name: 'Elder Orb', type: 'aberration', size: 'Large', alignment: 'lawful evil',
    cr: 15, ac: 19, hp: '210 (20d10 + 100)', speed: '0 ft., fly 20 ft. (hover)',
    description: 'A beholder ancient beyond counting, its central eye an abyss of negative energy and its eyestalks heavy with death.',
    lore: 'Elder orbs are beholders that have lived so long their antimagic gaze has evolved into pure death magic. They are the feared elders of beholder society, ruling over younger beholders and their slave-races. An elder orb does not merely disintegrate — it unmakes.',
    tactics: 'Death ray central eye. Finger of death and disintegrate eyestalks. Legendary actions. Commands beholders.',
    habitat: 'Deepest Underdark, beholder hive-cities',
    abilities: ['Death gaze', 'Finger of death', 'Disintegrate', 'Legendary resistance', 'Fly'],
    languages: ['Deep Speech', 'Undercommon', 'Beholder'],
    senses: ['darkvision 120 ft.', 'passive Perception 22'],
  },
];