/**
 * Original Dungeons & Dragons — Monsters & Treasure (1974)
 * The white box bestiary, plus creatures introduced in the supplements
 * (Greyhawk 1975, Blackmoor 1975, Eldritch Wizardry 1976).
 *
 * Entries are original writeups in the modern BestiaryEntry shape;
 * stats are 5e-style approximations for game use.
 */
import type { BestiaryEntry } from '../DnDKnowledge';

export const ODND_BESTIARY: BestiaryEntry[] = [
  // ── Classic dungeon vermin & pests ──
  {
    id: 'odnd_green_slime', name: 'Green Slime', type: 'hazard (ooze)', size: 'Small', alignment: 'unaligned',
    cr: 0, ac: 5, hp: '1 (1d4 - 1)', speed: '0 ft.',
    description: 'A patch of glistening green growth on a ceiling or wall, harmless-looking until it drips onto exposed flesh.',
    lore: 'The green slime is a stationary dungeon hazard from the original 1974 rules, feared far beyond its size. It is not a creature so much as a creeping curse: it eats flesh and turns living tissue into more slime. Only fire or cold can destroy it before it spreads.',
    tactics: 'Drops from above when disturbed. Dissolves flesh, leather, and wood in moments. Immune to ordinary weapons; burn or freeze it or it simply spreads.',
    habitat: 'Dungeon ceilings, damp stone, sewer grates',
    abilities: ['Corrosive', 'Spreads through flesh contact', 'Immune to non-magical weapons'],
    languages: [],
    senses: ['blindsight 30 ft.', 'passive Perception 6'],
  },
  {
    id: 'odnd_yellow_mold', name: 'Yellow Mold', type: 'hazard (fungus)', size: 'Medium', alignment: 'unaligned',
    cr: 0, ac: 5, hp: '2 (1d4)', speed: '0 ft.',
    description: 'A blanket of yellow-gray fungus that erupts in a choking cloud of spores when disturbed.',
    lore: 'Yellow mold infests tombs and forgotten crypts. When touched, it bursts into a cloud of spores that choke the lungs. Fire destroys it instantly, but the burst is what kills most delvers — a lesson learned only once.',
    tactics: 'Releases spore cloud in a 10-ft cube when touched. Spores deal poison damage and linger. Fire triggers an instant burst.',
    habitat: 'Crypts, catacombs, damp dungeons',
    abilities: ['Spore burst', 'Poison spores', 'Vulnerable to fire'],
    languages: [],
    senses: ['blindsight 10 ft.', 'passive Perception 5'],
  },
  {
    id: 'odnd_giant_rat', name: 'Giant Rat', type: 'beast', size: 'Small', alignment: 'unaligned',
    cr: 0.125, ac: 12, hp: '7 (2d6)', speed: '30 ft.',
    description: 'A rat the size of a dog, with yellowed teeth and eyes that gleam in the dark.',
    lore: 'Giant rats are the first thing many adventurers ever fight. They breed in the dark corners of dungeons and sewers, and their bites carry filth fever. Summoners and wererats alike employ them as messengers and guards.',
    tactics: 'Swarm in packs. Bite carries disease. Flee from fire and loud noise.',
    habitat: 'Sewers, dungeons, ship holds',
    abilities: ['Pack tactics', 'Keen smell', 'Diseased bite'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_giant_spider', name: 'Giant Spider', type: 'beast', size: 'Large', alignment: 'unaligned',
    cr: 1, ac: 14, hp: '26 (4d10 + 4)', speed: '30 ft., climb 30 ft.',
    description: 'A spider with legs spanning a doorway, its mandibles dripping venom and webs strung from its spinneret.',
    lore: 'Giant spiders spin webs across corridors to trap prey. They prefer to fight from ambush, retreating up walls when threatened. Some caverns are draped so thickly in their silk that the floor itself is a snare.',
    tactics: 'Webs first (restrains prey), then venomous bite. Climbs out of melee reach. Uses surprise to great effect.',
    habitat: 'Dungeons, forests, caverns',
    abilities: ['Web', 'Spider climb', 'Venomous bite', 'Web sense'],
    languages: [],
    senses: ['blindsight 10 ft.', 'darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_giant_scorpion', name: 'Giant Scorpion', type: 'beast', size: 'Large', alignment: 'unaligned',
    cr: 3, ac: 15, hp: '52 (7d10 + 14)', speed: '40 ft.',
    description: 'A horse-sized scorpion, its segmented tail arched overhead and dripping a dark, glistening venom.',
    lore: 'Giant scorpions are ambush hunters of the wastes and deserts. Their venom can drop a grown man in seconds. They grapple with their pincers while the tail strikes over their back.',
    tactics: 'Grapples with claws, then stings with the tail. Venom deals heavy poison damage. Burrows under sand to surprise prey.',
    habitat: 'Deserts, rocky badlands, warm caverns',
    abilities: ['Pincer grapple', 'Poison sting', 'Tremorsense'],
    languages: [],
    senses: ['blindsight 60 ft.', 'passive Perception 9'],
  },
  {
    id: 'odnd_giant_snake', name: 'Giant Snake', type: 'beast', size: 'Huge', alignment: 'unaligned',
    cr: 2, ac: 12, hp: '60 (8d12 + 8)', speed: '30 ft., swim 30 ft.',
    description: 'A serpent as thick as a barrel, its coils sliding silently through the undergrowth.',
    lore: 'Giant constrictors crush their prey before swallowing it whole. They strike from water or hanging branches. In the original rules, giant snakes were a staple wilderness encounter, whether constrictors, spitters, or venomous pit vipers.',
    tactics: 'Constricts grappled prey each turn. Strikes with surprise from cover. Swallows smaller victims.',
    habitat: 'Jungles, swamps, rivers',
    abilities: ['Constrict', 'Swallow', 'Amphibious'],
    languages: [],
    senses: ['blindsight 10 ft.', 'passive Perception 12'],
  },

  // ── Humanoids & men ──
  {
    id: 'odnd_bandit', name: 'Bandit', type: 'humanoid (human)', size: 'Medium', alignment: 'any non-lawful',
    cr: 0.125, ac: 12, hp: '11 (2d8 + 2)', speed: '30 ft.',
    description: 'A weathered outlaw with a short bow over one shoulder and a short blade at his belt.',
    lore: 'Bandits prey on travelers and remote settlements. Some are desperate; some are cruel. The original rules grouped them with brigands and buccaneers — men who live outside the law by taking from those who pass through their territory.',
    tactics: 'Ambush from cover with missile fire. Demand surrender or toll. Flee when outmatched.',
    habitat: 'Roads, forests, borderlands',
    abilities: ['Ambush', 'Ranged skirmish'],
    languages: ['Common'],
    senses: ['passive Perception 10'],
  },
  {
    id: 'odnd_berserker', name: 'Berserker', type: 'humanoid (human)', size: 'Medium', alignment: 'chaotic neutral',
    cr: 2, ac: 13, hp: '67 (9d8 + 27)', speed: '40 ft.',
    description: 'A wild-eyed warrior in furs, foam at his mouth, wielding an axe too large for reason.',
    lore: 'Berserkers are warriors who fight in a holy rage, ignoring wounds that would fell ordinary men. In the 1974 rules they were a distinct "man" type — unpredictable and dangerous even to allies. Their fury makes them immune to fear and pain.',
    tactics: 'Charges the nearest foe without regard for safety. Ignores pain and charm. Fights to the death once raging.',
    habitat: 'Northern wilderness, raiding parties',
    abilities: ['Rage', 'Fearless', 'Reckless attacks'],
    languages: ['Common'],
    senses: ['passive Perception 9'],
  },
  {
    id: 'odnd_gnoll', name: 'Gnoll', type: 'humanoid (gnoll)', size: 'Medium', alignment: 'chaotic evil',
    cr: 0.5, ac: 15, hp: '22 (5d8)', speed: '30 ft.',
    description: 'A hyena-headed humanoid in patchwork armor, its muzzle stained with gore.',
    lore: 'Gnolls are ravenous scavengers who follow armies and pick over battlefields. They are cruel, cowardly alone, and savage in packs. In the original game they were a fixture of the wilderness encounter tables, raiding in roving warbands.',
    tactics: 'Swarm in numbers. Use hit-and-run raids. Devour the fallen. Break and flee if leaders die.',
    habitat: 'Wastelands, ruins, war-torn borders',
    abilities: ['Rampage', 'Pack tactics', 'Darkvision'],
    languages: ['Gnoll'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_ogre', name: 'Ogre', type: 'giant', size: 'Large', alignment: 'chaotic evil',
    cr: 2, ac: 11, hp: '59 (7d10 + 21)', speed: '40 ft.',
    description: 'A hulking brute nine feet tall with a club the size of a man and the temper of a wounded bear.',
    lore: 'Ogres are the first true giants most adventurers meet. Strong but stupid, they bully weaker creatures into serving them and raid for food and shiny things. They often lead bands of goblins or orcs.',
    tactics: 'Smashes the biggest-looking threat with a greatclub. Hurls rocks at range. Too stupid for strategy, too strong to ignore.',
    habitat: 'Caves, ruined keeps, mountain passes',
    abilities: ['Brute strength', 'Rock throwing'],
    languages: ['Common', 'Giant'],
    senses: ['darkvision 60 ft.', 'passive Perception 8'],
  },
  {
    id: 'odnd_goblin', name: 'Goblin', type: 'humanoid (goblinoid)', size: 'Small', alignment: 'neutral evil',
    cr: 0.25, ac: 15, hp: '7 (2d6)', speed: '30 ft.',
    description: 'A small, green-skinned humanoid with pointed ears, yellow eyes, and a wicked little blade.',
    lore: 'Goblins are the archetypal dungeon pest — numerous, cowardly, and cruel when they have the numbers. They live in warrens, worship their bugbear and hobgoblin masters, and breed fast enough to outlast almost any extermination effort.',
    tactics: 'Attack in swarms, use dark tunnels and traps. Flee from bright light and strong opposition.',
    habitat: 'Caves, warrens, dungeon outskirts',
    abilities: ['Nimble escape', 'Darkvision'],
    languages: ['Common', 'Goblin'],
    senses: ['darkvision 60 ft.', 'passive Perception 9'],
  },
  {
    id: 'odnd_hobgoblin', name: 'Hobgoblin (OD&D)', type: 'humanoid (goblinoid)', size: 'Medium', alignment: 'lawful evil',
    cr: 0.5, ac: 18, hp: '11 (2d8 + 2)', speed: '30 ft.',
    description: 'A disciplined goblinoid soldier in well-kept mail, standing at attention with spear and shield.',
    lore: 'Even in 1974, hobgoblins were the soldiers of the goblin races — organized, armored, and drilled where goblins were rabble. They build forts, march in columns, and hold ground where lesser goblinoids flee.',
    tactics: 'Fight in formation with shields. Use martial advantage against flanked foes. Coordinate with bugbear and goblin allies.',
    habitat: 'Fortified warrens, conquered ruins',
    abilities: ['Martial advantage', 'Formation fighting'],
    languages: ['Common', 'Goblin'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_bugbear', name: 'Bugbear (OD&D)', type: 'humanoid (goblinoid)', size: 'Medium', alignment: 'chaotic evil',
    cr: 1, ac: 16, hp: '27 (5d8 + 5)', speed: '30 ft.',
    description: 'A broad, hairy goblinoid that moves in surprising silence for its bulk, a morningstar in its fist.',
    lore: 'Bugbears are the assassins of goblin society, sneaking up on sleeping victims for the joy of the kill. The 1974 bestiary listed them as fearsome ambushers who strike from hiding with deadly force.',
    tactics: 'Stealth ambush. Surprise attack for bonus damage. Bullies goblins into being bait.',
    habitat: 'Goblin warrens, abandoned buildings',
    abilities: ['Surprise attack', 'Brute', 'Stealthy'],
    languages: ['Common', 'Goblin'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_orc', name: 'Orc', type: 'humanoid (orc)', size: 'Medium', alignment: 'chaotic evil',
    cr: 0.5, ac: 13, hp: '15 (2d8 + 6)', speed: '30 ft.',
    description: 'A gray-green humanoid with tusks and a crude axe, hate burning in its red eyes.',
    lore: 'Orcs are the great enemy of the borderlands — cruel, warlike, and numerous beyond counting. They serve dark masters, raid by night, and despise elves above all. The 1974 rules made them a constant wilderness and dungeon threat.',
    tactics: 'Charge in mobs. Prefer night raids. Use wolf-riders as scouts. Retreat only to return in greater numbers.',
    habitat: 'Caverns, mountains, dark forests',
    abilities: ['Aggressive charge', 'Darkvision'],
    languages: ['Common', 'Orc'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },

  // ── Undead ──
  {
    id: 'odnd_skeleton', name: 'Skeleton', type: 'undead', size: 'Medium', alignment: 'lawful evil',
    cr: 0.25, ac: 13, hp: '13 (2d8 + 4)', speed: '30 ft.',
    description: 'A grinning collection of animated bones, a rusty blade held in fleshless fingers.',
    lore: 'Skeletons are the most basic undead, raised by necromancy to serve without question. They are immune to poison and mind magic, but their brittle bones shatter under bludgeoning weapons. They wait motionless in tombs until the living draw near.',
    tactics: 'Swarms mindlessly. Vulnerable to bludgeoning. Immune to poison and charm.',
    habitat: 'Tombs, crypts, necromantic lairs',
    abilities: ['Undead fortitude', 'Damage vulnerability: bludgeoning', 'Poison immunity'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 9'],
  },
  {
    id: 'odnd_zombie', name: 'Zombie', type: 'undead', size: 'Medium', alignment: 'neutral evil',
    cr: 0.25, ac: 8, hp: '22 (3d8 + 9)', speed: '20 ft.',
    description: 'A shambling corpse with milky eyes and outstretched arms, moaning as it lurches forward.',
    lore: 'Zombies are the slow but relentless servants of the grave. What they lack in speed they make up for in single-minded persistence. They ignore most wounds that would stop a living foe, rising to lurch onward unless truly destroyed.',
    tactics: 'Relentless pursuit. Grapples and bites. Undead fortitude lets it shrug off killing blows.',
    habitat: 'Graveyards, plague pits, necromancer towers',
    abilities: ['Undead fortitude', 'Poison immunity', 'Relentless'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 8'],
  },
  {
    id: 'odnd_ghoul', name: 'Ghoul', type: 'undead', size: 'Medium', alignment: 'chaotic evil',
    cr: 1, ac: 12, hp: '22 (5d8)', speed: '30 ft.',
    description: 'A cadaverous humanoid with long claws and a jaw that hangs too wide, drooling over the flesh of the living.',
    lore: 'Ghouls are corpse-eaters that haunt graveyards and battlefields. Their touch paralyzes, leaving victims helpless to be devoured alive. They serve more powerful undead such as ghasts and liches, and their bite turns the slain into more ghouls.',
    tactics: 'Paralyzing claws, then bite. Swarm a paralyzed victim. Fight over fresh kills.',
    habitat: 'Graveyards, charnel houses, Underdark tunnels',
    abilities: ['Paralyzing claws', 'Bite', 'Turn immunity (in large numbers)'],
    languages: ['Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_wight', name: 'Wight', type: 'undead', size: 'Medium', alignment: 'neutral evil',
    cr: 3, ac: 14, hp: '45 (6d8 + 18)', speed: '30 ft.',
    description: 'A pale, withered figure in tattered grave-clothes, its touch carrying the chill of the grave.',
    lore: 'Wights are the risen dead with a hunger for life energy. Their touch drains vitality permanently, a horror that lingers long after the battle. They haunt barrows and battlefields, hateful of all that lives.',
    tactics: 'Life drain with every strike. Immune to non-magical weapons. Command lesser undead.',
    habitat: 'Barrows, ancient battlefields, desecrated tombs',
    abilities: ['Life drain', 'Sunlight sensitivity', 'Damage immunity: nonmagical weapons'],
    languages: ['the languages it knew in life'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'odnd_wraith', name: 'Wraith (OD&D)', type: 'undead', size: 'Medium', alignment: 'neutral evil',
    cr: 5, ac: 13, hp: '67 (9d8 + 27)', speed: '0 ft., fly 60 ft. (hover)',
    description: 'A shadow-cloaked specter of pure malevolence, eyes burning like coals in the darkness.',
    lore: 'Wraiths are the undead souls of those consumed by hatred. They are incorporeal, passing through walls and armor alike, and their touch drains life itself. Sunlight is their only true bane.',
    tactics: 'Phase through walls to ambush. Life drain. Create specters from its victims.',
    habitat: 'Haunted ruins, ancient tombs, shadowed moors',
    abilities: ['Incorporeal', 'Life drain', 'Create specter', 'Sunlight sensitivity'],
    languages: ['the languages it knew in life'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },
  {
    id: 'odnd_mummy', name: 'Mummy', type: 'undead', size: 'Medium', alignment: 'lawful evil',
    cr: 3, ac: 11, hp: '58 (9d8 + 18)', speed: '20 ft.',
    description: 'A withered corpse wrapped in ancient, dust-choked bandages, a single baleful eye visible in the wrappings.',
    lore: 'Mummies guard the tombs of ancient kings and priests, bound by curses that outlast empires. Their touch spreads a rotting curse that defies ordinary healing, and their gaze fills the living with dread.',
    tactics: 'Dreadful glare to frighten, then rotting fist. Curse lingers and resists healing. Vulnerable to fire.',
    habitat: 'Pyramids, sealed tombs, desert crypts',
    abilities: ['Rotting curse', 'Dreadful glare', 'Damage vulnerability: fire'],
    languages: ['the languages of its ancient land'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_spectre', name: 'Spectre', type: 'undead', size: 'Medium', alignment: 'chaotic evil',
    cr: 1, ac: 12, hp: '22 (5d8)', speed: '0 ft., fly 50 ft. (hover)',
    description: 'A faint, translucent shape that whispers with a dead voice, its touch colder than the grave.',
    lore: 'Spectres are the angry dead, bound to the mortal world by violence and hate. They drain life force with a touch and are impervious to mundane steel. They dwell where great evil or tragedy occurred.',
    tactics: 'Incorporeal hit-and-run. Life drain. Hates sunlight.',
    habitat: 'Places of murder, haunted houses, battlefields',
    abilities: ['Incorporeal', 'Life drain', 'Sunlight sensitivity'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_vampire', name: 'Vampire (OD&D)', type: 'undead', size: 'Medium', alignment: 'chaotic evil',
    cr: 13, ac: 16, hp: '144 (17d8 + 68)', speed: '30 ft.',
    description: 'A pale noble with a wolfish smile and eyes that catch the light like a predator at the edge of firelight.',
    lore: 'Vampires are among the most feared of all undead, commanding legions of lesser creatures. They are repelled by garlic, holy symbols, and running water; a stake through the heart or sunlight ends them. Their bite drains life and creates new vampires.',
    tactics: 'Charm victims. Shapechange into bat or wolf. Regenerate unless struck by radiant or holy power.',
    habitat: 'Castles, crypts, noble estates',
    abilities: ['Shapechanger', 'Regeneration', 'Charm', 'Children of the night'],
    languages: ['the languages it knew in life'],
    senses: ['darkvision 120 ft.', 'passive Perception 17'],
  },

  // ── Mythic beasts ──
  {
    id: 'odnd_basilisk', name: 'Basilisk', type: 'monstrosity', size: 'Medium', alignment: 'unaligned',
    cr: 3, ac: 15, hp: '52 (8d8 + 16)', speed: '20 ft.',
    description: 'A reptilian horror with eight legs and a gaze that turns the living to stone.',
    lore: 'The basilisk is called the king of serpents, though it walks on eight legs and kills without moving. Its gaze petrifies; even its reflection is deadly to the unwary. Heroes who slay one are legend, for few ever get close enough to strike.',
    tactics: 'Petrifying gaze at range. Bites those who avert their eyes. Reflected gaze can petrify the basilisk itself.',
    habitat: 'Caves, ruins, desert mesas',
    abilities: ['Petrifying gaze', 'Poisonous bite'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 9'],
  },
  {
    id: 'odnd_chimera', name: 'Chimera', type: 'monstrosity', size: 'Large', alignment: 'chaotic evil',
    cr: 6, ac: 14, hp: '114 (12d10 + 48)', speed: '30 ft., fly 60 ft.',
    description: 'A beast of impossible parts — a lion\'s body, a goat\'s head at the shoulder, a serpent for a tail, and dragon wings spread wide.',
    lore: 'The chimera is a creature of broken creation, as likely the work of a mad wizard as a curse of the gods. Its three heads each fight with their own hunger: the lion bites, the goat horns, and the serpent tail spits venom or fire.',
    tactics: 'Multiattack from three heads. Breathes fire from the dragon head. Fights from the air, diving on prey.',
    habitat: 'Mountains, volcanic wastelands',
    abilities: ['Fire breath', 'Multiattack (three heads)', 'Fly'],
    languages: ['understands Draconic'],
    senses: ['darkvision 60 ft.', 'passive Perception 18'],
  },
  {
    id: 'odnd_cockatrice', name: 'Cockatrice', type: 'monstrosity', size: 'Small', alignment: 'unaligned',
    cr: 0.5, ac: 11, hp: '27 (6d6 + 6)', speed: '20 ft., fly 40 ft.',
    description: 'A bantam-sized creature with the body of a rooster, the tail of a lizard, and bat wings, its touch turning flesh to stone.',
    lore: 'The cockatrice is a small horror whose peck petrifies. It hatches from eggs laid by roosters and incubated by toads, or so the peasants say. Its gaze is less dangerous than the basilisk\'s, but its touch is just as final.',
    tactics: 'Pecks and claws, petrifying on contact. Flies at faces. Avoids those with mirrors.',
    habitat: 'Farmland edges, caves, ruins',
    abilities: ['Petrifying touch', 'Fly'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 11'],
  },
  {
    id: 'odnd_griffon', name: 'Griffon', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 2, ac: 12, hp: '59 (7d10 + 21)', speed: '30 ft., fly 80 ft.',
    description: 'A kingly beast with the head, wings, and foreclaws of an eagle and the hindquarters of a lion.',
    lore: 'Griffons are proud hunters of high mountains and open sky. They are fiercely territorial and mate for life. Dwarves and nobles alike train them as mounts, a bond that makes a rider feared across the land.',
    tactics: 'Diving attacks with talons. Grabs prey and drops it from height. Fights to defend its nest to the death.',
    habitat: 'Mountains, cliffs, high plains',
    abilities: ['Diving attack', 'Keen sight', 'Fly'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 15'],
  },
  {
    id: 'odnd_hippogriff', name: 'Hippogriff', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 1, ac: 11, hp: '19 (3d10 + 3)', speed: '40 ft., fly 60 ft.',
    description: 'A winged steed with the forelegs and head of an eagle and the hindquarters of a horse.',
    lore: 'The hippogriff is the natural enemy of the horse and the easier-tamed cousin of the griffon. Knights and rangers prize them as loyal, swift mounts. They roost in high, rocky eyries far from the reach of ordinary predators.',
    tactics: 'Dives and strikes with talons and beak. Flees rather than fight to the death unless defending young.',
    habitat: 'Highlands, mountains, sea cliffs',
    abilities: ['Diving attack', 'Fly', 'Keen sight'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 15'],
  },
  {
    id: 'odnd_hydra', name: 'Hydra', type: 'monstrosity', size: 'Huge', alignment: 'unaligned',
    cr: 8, ac: 15, hp: '172 (15d12 + 75)', speed: '30 ft., swim 30 ft.',
    description: 'A serpentine horror with many heads on long necks, each one snapping and hissing with its own hunger.',
    lore: 'The hydra is the nightmare of swamps and caverns. Sever a head and two more may grow in its place, unless the wound is seared with fire or acid. The original rules made the hydra a puzzle-monster: the wrong tactic makes it stronger.',
    tactics: 'One attack per head. Regrows two heads for each severed unless cauterized. Grapples and drags prey into water.',
    habitat: 'Swamps, marsh caves, underground lakes',
    abilities: ['Multiple heads', 'Head regrowth', 'Amphibious'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 16'],
  },
  {
    id: 'odnd_manticore', name: 'Manticore', type: 'monstrosity', size: 'Large', alignment: 'lawful evil',
    cr: 3, ac: 14, hp: '68 (8d10 + 24)', speed: '30 ft., fly 50 ft.',
    description: 'A lion-bodied predator with a human face, bat wings, and a tail bristling with iron spikes.',
    lore: 'The manticore is a cunning and sadistic hunter that toys with its prey. Its tail spikes can be flung like javelins, and it delights in hunting humans above all else. It speaks, and uses its voice to lie, taunt, and bargain.',
    tactics: 'Volleys of tail spikes at range. Closes with bite and claws. Negotiates insincerely when cornered.',
    habitat: 'Mountains, deserts, ruins',
    abilities: ['Tail spike volley', 'Fly', 'Bite and claws'],
    languages: ['Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },
  {
    id: 'odnd_minotaur', name: 'Minotaur', type: 'monstrosity', size: 'Large', alignment: 'chaotic evil',
    cr: 3, ac: 14, hp: '76 (9d10 + 27)', speed: '40 ft.',
    description: 'A bull-headed giant with horns like spears and a labrys axe resting on one shoulder.',
    lore: 'Minotaurs are the cursed offspring of ancient sins, dwelling in labyrinthine ruins where they hunt by scent and memory. They are relentless trackers and ferocious in a charge. Some are born of a curse laid upon an entire bloodline.',
    tactics: 'Charges with horns to gore. Uses the maze to separate prey. Tracks relentlessly.',
    habitat: 'Labyrinths, ruins, mazelike caverns',
    abilities: ['Gore charge', 'Labyrinthine recall', 'Relentless tracking'],
    languages: ['Abyssal'],
    senses: ['darkvision 60 ft.', 'passive Perception 17'],
  },
  {
    id: 'odnd_medusa', name: 'Medusa', type: 'monstrosity', size: 'Medium', alignment: 'lawful evil',
    cr: 6, ac: 15, hp: '127 (17d8 + 51)', speed: '30 ft.',
    description: 'A serpent-haired woman of terrible beauty whose living locks hiss and writhe, her gaze turning flesh to stone.',
    lore: 'Medusae are mortals cursed by the gods for vanity or betrayal, transformed into petrifying predators. They collect the stone forms of their victims as trophies. A mirror is the classic counter, for their own gaze reflected is their undoing.',
    tactics: 'Petrifying gaze. Serpent hair bites. Fights with a bow from range, luring victims to look up.',
    habitat: 'Ruined temples, caverns, lairs full of statues',
    abilities: ['Petrifying gaze', 'Serpent hair', 'Poison'],
    languages: ['Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'odnd_owlbear', name: 'Owlbear', type: 'monstrosity', size: 'Large', alignment: 'unaligned',
    cr: 3, ac: 13, hp: '59 (7d10 + 21)', speed: '40 ft.',
    description: 'A shaggy monstrosity with the body of a bear and the round, feathered head and hooked beak of a giant owl.',
    lore: 'The owlbear is the legendary result of a wizard\'s careless experimentation — or a mad god\'s joke. It is ferocious, territorial, and utterly unpredictable. Its hooting screech chills the blood of travelers in dark woods.',
    tactics: 'Charges with beak and claws. Hugs prey and rends with hind claws. Fights to the death over territory.',
    habitat: 'Dense forests, caves, wild highlands',
    abilities: ['Multiattack (beak and claws)', 'Keen sight and smell', 'Rend'],
    languages: [],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'odnd_roc', name: 'Roc', type: 'monstrosity', size: 'Gargantuan', alignment: 'unaligned',
    cr: 11, ac: 15, hp: '248 (16d20 + 80)', speed: '20 ft., fly 120 ft.',
    description: 'A bird so vast its wings darken the sky, its talons large enough to carry off an elephant or a ship\'s mast.',
    lore: 'The roc is the terror of remote mountains and trackless seas. It nests on peaks above the clouds and hunts whales and elephants. Sailors tell of ships snatched whole from the waves. Its eggs are worth a kingdom — if one can survive the mother.',
    tactics: 'Dives from great height, grappling prey in its talons. Carries victims aloft and drops them. Destroys ships.',
    habitat: 'High mountains, remote islands, open ocean',
    abilities: ['Grapple', 'Fly', 'Siege monster'],
    languages: [],
    senses: ['passive Perception 14'],
  },
  {
    id: 'odnd_purple_worm', name: 'Purple Worm', type: 'monstrosity', size: 'Gargantuan', alignment: 'unaligned',
    cr: 15, ac: 18, hp: '247 (15d20 + 90)', speed: '50 ft., burrow 30 ft.',
    description: 'A colossal segmented worm that bursts from the earth, its maw ringed with teeth and its stinger dripping venom.',
    lore: 'The purple worm is the apex predator of the deep earth, boring tunnels through solid rock and swallowing anything in its path. It detects prey by vibration. Its venomous tail stinger is as deadly as its gullet.',
    tactics: 'Burrows to ambush. Swallows prey whole. Stings with venomous tail. Tremorsense detects all movement.',
    habitat: 'Deep underground, deserts, cavern systems',
    abilities: ['Swallow whole', 'Poison stinger', 'Tunneler', 'Tremorsense'],
    languages: [],
    senses: ['blindsight 30 ft.', 'tremorsense 60 ft.', 'passive Perception 9'],
  },
  {
    id: 'odnd_unicorn', name: 'Unicorn', type: 'celestial', size: 'Large', alignment: 'lawful good',
    cr: 5, ac: 12, hp: '67 (9d10 + 18)', speed: '50 ft.',
    description: 'A white horse of impossible grace, a single spiraled horn of pearl rising from its brow and a light that seems to heal the air around it.',
    lore: 'Unicorns are creatures of pure magic, protectors of enchanted forests. They can sense the hearts of mortals and only approach the truly good. Their horn purifies water and cures poison, and their touch heals the wounded.',
    tactics: 'Flees evil. Defends the innocent. Its horn pierces armor and its touch heals. Teleports short distances.',
    habitat: 'Enchanted forests, sylvan glades',
    abilities: ['Healing touch', 'Magic resistance', 'Teleport', 'Horn attack'],
    languages: ['Celestial', 'Elvish', 'Sylvan', 'telepathy 60 ft.'],
    senses: ['darkvision 60 ft.', 'passive Perception 13'],
  },
  {
    id: 'odnd_pegasi', name: 'Pegasus', type: 'celestial', size: 'Large', alignment: 'chaotic good',
    cr: 2, ac: 12, hp: '59 (7d10 + 21)', speed: '60 ft., fly 90 ft.',
    description: 'A winged white horse that gallops on the wind, its wings folding like thunder when it lands.',
    lore: 'Pegasi are noble winged steeds that serve the forces of good. They are fiercely loyal to worthy riders and will not suffer evil to ride them. They nest on high peaks and drink from springs that no shadow touches.',
    tactics: 'Diving kicks and hoof strikes. Carries a trusted rider. Flees rather than fight evil that outmatches it.',
    habitat: 'Mountain peaks, cloud-touched meadows',
    abilities: ['Fly', 'Hoof attack', 'Keen sight'],
    languages: ['understands Celestial, Common, Elvish, Sylvan'],
    senses: ['passive Perception 15'],
  },

  // ── Fey & sprites ──
  {
    id: 'odnd_pixie', name: 'Pixie', type: 'fey', size: 'Tiny', alignment: 'neutral good',
    cr: 0.25, ac: 15, hp: '1 (1d4 - 1)', speed: '10 ft., fly 30 ft.',
    description: 'A foot-tall winged sprite of pure mischief, glittering with fey light and never quite where it seems.',
    lore: 'Pixies are the laughing spirits of deep woods and mushroom rings. They are naturally invisible and delight in confusing travelers. Though playful, they can be fierce defenders of their glades, wielding sleep-arrows and fey glamours.',
    tactics: 'Turns invisible. Casts sleep and confusion. Uses tiny enchanted arrows. Misleads pursuers.',
    habitat: 'Fey woods, mushroom rings, enchanted glades',
    abilities: ['Invisibility', 'Fey spellcasting', 'Fly'],
    languages: ['Sylvan'],
    senses: ['passive Perception 12'],
  },
  {
    id: 'odnd_sprite', name: 'Sprite', type: 'fey', size: 'Tiny', alignment: 'neutral good',
    cr: 0.25, ac: 15, hp: '2 (1d4)', speed: '10 ft., fly 40 ft.',
    description: 'A tiny winged archer with a bow no longer than a finger, its arrows tipped with enchanted sleep.',
    lore: 'Sprites are the guardians and pranksters of the fey woods. Their arrows knock targets into enchanted slumber rather than killing. They can read the hearts of mortals and are drawn to those of good nature, playing tricks on the wicked.',
    tactics: 'Sleep arrows at range. Turns invisible. Taunts and leads pursuers into bogs and thickets.',
    habitat: 'Forests, meadows, fey crossings',
    abilities: ['Sleep arrows', 'Invisibility', 'Heart sight', 'Fly'],
    languages: ['Common', 'Elvish', 'Sylvan'],
    senses: ['passive Perception 13'],
  },
  {
    id: 'odnd_nixie', name: 'Nixie', type: 'fey', size: 'Small', alignment: 'neutral',
    cr: 1, ac: 15, hp: '18 (4d6 + 4)', speed: '20 ft., swim 40 ft.',
    description: 'A graceful water spirit with green hair and webbed hands, half-seen beneath the surface of a still pool.',
    lore: 'Nixies are water sprites who lure mortals into lakes and rivers with their beauty and song. They can breathe water and charm the unwary. Some drown their victims; others merely steal trinkets and memories. They make pacts with those who treat their waters with respect.',
    tactics: 'Charm person from the water. Drags charmed victims beneath the surface. Escapes into deep water when threatened.',
    habitat: 'Lakes, rivers, deep springs',
    abilities: ['Amphibious', 'Charm person', 'Water breathing'],
    languages: ['Sylvan'],
    senses: ['darkvision 60 ft.', 'passive Perception 12'],
  },

  // ── Constructs & golems ──
  {
    id: 'odnd_golem_flesh', name: 'Flesh Golem', type: 'construct', size: 'Medium', alignment: 'neutral',
    cr: 5, ac: 9, hp: '93 (11d8 + 44)', speed: '30 ft.',
    description: 'A stitched-together hulk of dead flesh animated by lightning, its mismatched limbs twitching as it lurches forward.',
    lore: 'Flesh golems are the crude work of necromancers and mad chirurgeons, built from corpses and sparked to life with lightning. They obey their creator without question but can rage out of control. Fire and lightning heal and enrage them rather than harm.',
    tactics: 'Berserk when damaged. Immune to most magic; lightning heals it. Pummels with fists of dead flesh.',
    habitat: 'Wizard towers, crypts, abandoned laboratories',
    abilities: ['Berserk', 'Lightning absorption', 'Magic resistance', 'Immutable form'],
    languages: ['understands its creator\'s language'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_golem_stone', name: 'Stone Golem', type: 'construct', size: 'Large', alignment: 'unaligned',
    cr: 10, ac: 17, hp: '178 (17d10 + 85)', speed: '30 ft.',
    description: 'A towering figure of carved stone, its joints grinding as it turns its blank face toward intruders.',
    lore: 'Stone golems are the eternal guardians of temples and tombs, carved with prayers and animated by bound elemental spirit. They are slow to anger but nearly impossible to stop once roused. Only adamantine or powerful magic can reliably harm them.',
    tactics: 'Slow spell on intruders. Pummels with stone fists. Immune to nonmagical weapons not made of adamantine.',
    habitat: 'Temples, tombs, dwarven vaults',
    abilities: ['Magic resistance', 'Slow', 'Damage immunity: nonmagical non-adamantine weapons'],
    languages: ['understands its creator\'s language'],
    senses: ['darkvision 120 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_golem_iron', name: 'Iron Golem', type: 'construct', size: 'Large', alignment: 'unaligned',
    cr: 16, ac: 20, hp: '210 (20d10 + 100)', speed: '30 ft.',
    description: 'A twelve-foot colossus of black iron, its furnace-chest glowing and its breath a scalding cloud of poison.',
    lore: 'Iron golems are the mightiest of the common golems, forged by archmages as unstoppable guardians. They are immune to almost all magic — save fire, which heals them — and their poisonous breath chokes those who close with them.',
    tactics: 'Poison breath. Healed by fire, harmed by lightning. Smashes with iron fists. Nearly immune to magic.',
    habitat: 'Wizard fortresses, planar vaults, hidden armories',
    abilities: ['Poison breath', 'Fire absorption', 'Magic immunity', 'Immutable form'],
    languages: ['understands its creator\'s language'],
    senses: ['darkvision 120 ft.', 'passive Perception 10'],
  },

  // ── Giants ──
  {
    id: 'odnd_hill_giant', name: 'Hill Giant', type: 'giant', size: 'Huge', alignment: 'chaotic evil',
    cr: 5, ac: 13, hp: '105 (10d12 + 40)', speed: '40 ft.',
    description: 'A squat, brutish giant with a boulder in one fist and a hunger for anything smaller than itself.',
    lore: 'Hill giants are the dimmest and most gluttonous of the giant races, raiding farms and villages for food. They are cruel without malice — they simply do not think of smaller folk as people. They throw rocks with terrible accuracy.',
    tactics: 'Hurls boulders. Grabs and bites. Bullies weaker creatures into serving it.',
    habitat: 'Hills, caves, raided farmsteads',
    abilities: ['Rock throwing', 'Multiattack (greatclub)', 'Brute'],
    languages: ['Giant'],
    senses: ['passive Perception 8'],
  },
  {
    id: 'odnd_stone_giant', name: 'Stone Giant', type: 'giant', size: 'Huge', alignment: 'neutral',
    cr: 7, ac: 17, hp: '126 (11d12 + 55)', speed: '40 ft.',
    description: 'A grey-skinned giant that blends with the rock face, patient as the mountains it carves into art.',
    lore: 'Stone giants are reclusive sculptors who live in mountain caverns and consider the surface world a dream. They are not evil, but they defend their homes fiercely. Their stone-throwing is legendary for its precision.',
    tactics: 'Ambushes from stone camouflage. Throws boulders. Crushes with stone greatclubs.',
    habitat: 'Mountains, caverns, stone ruins',
    abilities: ['Rock camouflage', 'Rock throwing', 'Stone greatclub'],
    languages: ['Giant'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'odnd_frost_giant', name: 'Frost Giant', type: 'giant', size: 'Huge', alignment: 'neutral evil',
    cr: 8, ac: 15, hp: '138 (12d12 + 60)', speed: '40 ft.',
    description: 'A blue-skinned giant with a braided beard of ice and a greataxe crusted with frost, breathing steam into the cold air.',
    lore: 'Frost giants are raiders of the far north, seafaring warriors who worship strength and plunder. They keep white dragons and winter wolves as hunting beasts and war against the smaller folk of the tundra. Their breath is cold, their hearts colder.',
    tactics: 'Greataxe and thrown boulders. Commands winter wolves. Immune to cold.',
    habitat: 'Glaciers, frozen mountains, arctic coasts',
    abilities: ['Multiattack (greataxe)', 'Rock throwing', 'Cold immunity'],
    languages: ['Giant'],
    senses: ['passive Perception 13'],
  },
  {
    id: 'odnd_fire_giant', name: 'Fire Giant', type: 'giant', size: 'Huge', alignment: 'lawful evil',
    cr: 9, ac: 18, hp: '162 (13d12 + 78)', speed: '30 ft.',
    description: 'A coal-black-skinned giant with hair like flames and a greatsword glowing from the forge-heat of its grip.',
    lore: 'Fire giants are master smiths and tyrants, ruling volcanic strongholds with iron discipline. They enslave dwarves and others to work their forges. They respect strength and craftsmanship, but see all lesser beings as fuel for their ambitions.',
    tactics: 'Heated greatsword. Throws magma-heated boulders. Immune to fire. Commands hell hounds.',
    habitat: 'Volcanoes, deep forges, volcanic strongholds',
    abilities: ['Multiattack (greatsword)', 'Rock throwing', 'Fire immunity'],
    languages: ['Giant', 'Ignan'],
    senses: ['darkvision 60 ft.', 'passive Perception 14'],
  },
  {
    id: 'odnd_cloud_giant', name: 'Cloud Giant', type: 'giant', size: 'Huge', alignment: 'neutral good or neutral evil',
    cr: 9, ac: 14, hp: '200 (16d12 + 96)', speed: '40 ft.',
    description: 'A giant of the skies, robed and calm, its castle drifting on a cloud above the world.',
    lore: 'Cloud giants dwell in castles built on enchanted clouds, above the concerns of lesser folk. They are split between those who are kindly and aloof and those who are arrogant and cruel. They can smell out treasure and are masters of air and weather.',
    tactics: 'Flings wind-borne boulders. Commands air elementals and griffons. Casts fog and gust of wind.',
    habitat: 'Sky castles, mountaintops above the clouds',
    abilities: ['Rock throwing', 'Innate air magic', 'Keen smell (treasure sense)'],
    languages: ['Common', 'Giant'],
    senses: ['passive Perception 17'],
  },
  {
    id: 'odnd_storm_giant', name: 'Storm Giant', type: 'giant', size: 'Huge', alignment: 'chaotic good',
    cr: 13, ac: 16, hp: '230 (20d12 + 100)', speed: '50 ft., swim 50 ft.',
    description: 'A towering violet-skinned giant wreathed in static, lightning flickering in its eyes and voice like rolling thunder.',
    lore: 'Storm giants are the greatest of the true giants, aloof prophets who read the future in storms and tides. They dwell in underwater palaces and cloud-peak fortresses, speaking rarely with mortals. They can hurl lightning as easily as stone.',
    tactics: 'Lightning strike. Throws boulders charged with electricity. Amphibious and at home in storms.',
    habitat: 'Oceans, storm-wracked peaks, cloud fortresses',
    abilities: ['Lightning strike', 'Rock throwing', 'Amphibious', 'Innate storm magic'],
    languages: ['Common', 'Giant'],
    senses: ['passive Perception 19'],
  },

  // ── Dragons (chromatic & metallic) ──
  {
    id: 'odnd_white_dragon', name: 'White Dragon', type: 'dragon', size: 'Large', alignment: 'chaotic evil',
    cr: 6, ac: 17, hp: '133 (14d10 + 56)', speed: '40 ft., burrow 20 ft., fly 80 ft., swim 40 ft.',
    description: 'A drake of frost and fang, its scales like packed snow and its breath a killing blizzard.',
    lore: 'White dragons are the smallest and most feral of the chromatic dragons, hunting the frozen wastes like beasts. They are not cunning schemers like their kin, but savage and relentless predators. They remember every slight and every scent.',
    tactics: 'Cold breath cone. Ambushes from snow or ice. Bites and claws. Fights without fear in its element.',
    habitat: 'Glaciers, frozen tundra, arctic caves',
    abilities: ['Cold breath', 'Burrow', 'Ice walk', 'Fly'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 16'],
  },
  {
    id: 'odnd_black_dragon', name: 'Black Dragon', type: 'dragon', size: 'Large', alignment: 'chaotic evil',
    cr: 7, ac: 18, hp: '127 (15d10 + 45)', speed: '40 ft., fly 80 ft., swim 40 ft.',
    description: 'A reptilian terror of the fens, its black hide dripping with acid and its skull-like face grinning.',
    lore: 'Black dragons are the cruelest of the chromatics, lurking in swamps and ruins where they torment prey before killing. They are amphibious and patient, capable of lying motionless in murky water for hours. They covet treasures of fallen civilizations.',
    tactics: 'Acid breath line. Ambushes from water. Fights dirty, targeting the weakest prey first.',
    habitat: 'Swamps, fens, sunken ruins',
    abilities: ['Acid breath', 'Amphibious', 'Fly'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 16'],
  },
  {
    id: 'odnd_green_dragon', name: 'Green Dragon', type: 'dragon', size: 'Large', alignment: 'lawful evil',
    cr: 8, ac: 18, hp: '136 (16d10 + 48)', speed: '40 ft., fly 80 ft., swim 40 ft.',
    description: 'A forest-shadow dragon with emerald scales and a forked tongue that tastes the air for lies.',
    lore: 'Green dragons are the schemers of dragonkind, manipulating lesser creatures through lies and fear. They lair in deep forests and poison the land around them. They prefer to corrupt and dominate rather than simply destroy.',
    tactics: 'Poison breath cone. Manipulates minions. Ambushes from canopy. Tastes the air to detect intruders.',
    habitat: 'Ancient forests, overgrown ruins',
    abilities: ['Poison breath', 'Amphibious', 'Fly', 'Deception'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 17'],
  },
  {
    id: 'odnd_blue_dragon', name: 'Blue Dragon', type: 'dragon', size: 'Large', alignment: 'lawful evil',
    cr: 9, ac: 18, hp: '152 (16d10 + 64)', speed: '40 ft., burrow 20 ft., fly 80 ft.',
    description: 'A desert tyrant with scales like sapphires and a breath of forked lightning, its voice a dry rasp of command.',
    lore: 'Blue dragons rule the wastes and value order — their order. Vain and territorial, they collect loyal minions and treasure alike. They are patient ambushers, burying themselves in sand and waiting for the perfect moment to strike.',
    tactics: 'Lightning breath line. Burrows in sand to ambush. Blinds prey with sand. Commands loyal tribes.',
    habitat: 'Deserts, mesas, dry badlands',
    abilities: ['Lightning breath', 'Burrow', 'Fly', 'Blindsight'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 17'],
  },
  {
    id: 'odnd_red_dragon', name: 'Red Dragon', type: 'dragon', size: 'Large', alignment: 'chaotic evil',
    cr: 10, ac: 18, hp: '178 (17d10 + 85)', speed: '40 ft., climb 40 ft., fly 80 ft.',
    description: 'The archetypal dragon of legend, scales like molten fire and a furnace in its chest, hoarding gold in a mountain lair.',
    lore: 'Red dragons are greed made flesh — the most arrogant, powerful, and feared of the chromatics. They lair in mountains and volcanos atop mountains of treasure, and they will not share. They see all other creatures as lesser beings to be owned or destroyed.',
    tactics: 'Fire breath cone. Frightful presence. Attacks from the air. Defends its hoard to the death.',
    habitat: 'Volcanoes, mountains, deep caverns',
    abilities: ['Fire breath', 'Frightful presence', 'Fly', 'Climb'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 18'],
  },
  {
    id: 'odnd_brass_dragon', name: 'Brass Dragon', type: 'dragon', size: 'Medium', alignment: 'chaotic good',
    cr: 6, ac: 17, hp: '110 (13d10 + 39)', speed: '40 ft., burrow 20 ft., fly 80 ft.',
    description: 'A talkative desert dragon with polished brass scales and a breath of scorching heat or sleep.',
    lore: 'Brass dragons are the chatterboxes of dragonkind, collecting conversation the way others collect gold. They lair in desert caverns and love to speak with travelers — sometimes at unbearable length. They are good-natured but dangerously self-absorbed.',
    tactics: 'Fire breath or sleep breath. Burrows to escape. Prefers to talk, but fights fiercely if threatened.',
    habitat: 'Deserts, canyon caves',
    abilities: ['Fire breath', 'Sleep breath', 'Burrow', 'Fly'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 16'],
  },
  {
    id: 'odnd_copper_dragon', name: 'Copper Dragon', type: 'dragon', size: 'Medium', alignment: 'chaotic good',
    cr: 7, ac: 17, hp: '119 (14d10 + 42)', speed: '40 ft., climb 40 ft., fly 80 ft.',
    description: 'A prankster dragon with bright copper scales and a breath of acid or slowing gas, its grin permanently amused.',
    lore: 'Copper dragons are jesters and riddlers, lairing in rocky hills where they play tricks on travelers. They are the most sociable of the metallics, but their humor can be sharp. They hoard art, jokes, and riddles alongside coin.',
    tactics: 'Acid breath or slowing breath. Uses terrain and tricks. Avoids killing when a prank will do.',
    habitat: 'Rocky hills, canyons, mountain caves',
    abilities: ['Acid breath', 'Slowing breath', 'Climb', 'Fly'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 17'],
  },
  {
    id: 'odnd_bronze_dragon', name: 'Bronze Dragon', type: 'dragon', size: 'Medium', alignment: 'lawful good',
    cr: 8, ac: 18, hp: '142 (15d10 + 60)', speed: '40 ft., fly 80 ft., swim 40 ft.',
    description: 'A coastal dragon with bronze scales that gleam like a warship\'s plating and a breath of lightning or repulsion.',
    lore: 'Bronze dragons are the guardians of coasts and seas, watching over sailors and fighting the tyranny of chromatic dragons and sea monsters. They are honorable and brave, though stern with those who pollute or abuse the waters they protect.',
    tactics: 'Lightning breath or repulsion breath. Amphibious ambush from the sea. Fights evil dragons without hesitation.',
    habitat: 'Sea caves, coastal cliffs, sunken ruins',
    abilities: ['Lightning breath', 'Repulsion breath', 'Amphibious', 'Fly'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 17'],
  },
  {
    id: 'odnd_silver_dragon', name: 'Silver Dragon', type: 'dragon', size: 'Large', alignment: 'lawful good',
    cr: 9, ac: 18, hp: '168 (16d10 + 80)', speed: '40 ft., fly 80 ft.',
    description: 'A dragon of gleaming silver who walks among mortals in disguise, its breath a cone of cold or paralyzing vapor.',
    lore: 'Silver dragons are the friendliest of dragonkind toward mortals, sometimes living among them in human form. They dwell on mountain peaks above the clouds, where they watch over the lands below. They hate evil and cruelty with a cold, righteous fury.',
    tactics: 'Cold breath or paralyzing breath. Changes shape to walk among mortals. Fights evil with calculated fury.',
    habitat: 'Mountain peaks, cloud-shrouded aeries',
    abilities: ['Cold breath', 'Paralyzing breath', 'Shapechange', 'Fly'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 18'],
  },
  {
    id: 'odnd_gold_dragon', name: 'Gold Dragon', type: 'dragon', size: 'Large', alignment: 'lawful good',
    cr: 10, ac: 19, hp: '178 (17d10 + 85)', speed: '40 ft., fly 80 ft., swim 40 ft.',
    description: 'A magnificent dragon of molten gold, wise beyond measure, its breath a cone of fire or a weakening gas.',
    lore: 'Gold dragons are the wisest and most powerful of the metallic dragons, sages and judges who oppose evil across the ages. They can assume humanoid form and live among mortals as teachers and guardians. Their hoards are libraries of accumulated wisdom.',
    tactics: 'Fire breath or weakening breath. Shapechanges to mortal form. Uses wisdom and patience before force.',
    habitat: 'Remote mountains, lakes, hidden libraries',
    abilities: ['Fire breath', 'Weakening breath', 'Shapechange', 'Amphibious', 'Fly'],
    languages: ['Common', 'Draconic'],
    senses: ['blindsight 30 ft.', 'darkvision 120 ft.', 'passive Perception 19'],
  },

  // ── Elementals & genies ──
  {
    id: 'odnd_air_elemental', name: 'Air Elemental', type: 'elemental', size: 'Large', alignment: 'neutral',
    cr: 5, ac: 15, hp: '90 (12d10 + 24)', speed: '0 ft., fly 90 ft. (hover)',
    description: 'A whirling cyclone given form, its body a maelstrom of wind and cloud with a faint suggestion of eyes.',
    lore: 'Air elementals are living storms, swift and difficult to grasp. They are summoned to scout, to bear messages, and to scatter enemies like leaves. They are capricious — hard to control and impossible to truly pin down.',
    tactics: 'Whirlwind form scatters foes. Flies out of melee reach. Disperses and reforms.',
    habitat: 'The Plane of Air, stormy skies',
    abilities: ['Whirlwind', 'Fly', 'Damage resistance: nonmagical weapons'],
    languages: ['Auran'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_earth_elemental', name: 'Earth Elemental', type: 'elemental', size: 'Large', alignment: 'neutral',
    cr: 5, ac: 17, hp: '126 (12d10 + 60)', speed: '30 ft., burrow 30 ft.',
    description: 'A hulking humanoid of stone and soil, grinding forward with the weight of a landslide.',
    lore: 'Earth elementals are the slow but unstoppable power of the living rock. They stride through stone as fish swim through water. Summoners call them to batter down walls, crush fortifications, and stand as unbreakable bulwarks.',
    tactics: 'Buries through stone to surprise. Pummels with stone fists. Ignores most weapons.',
    habitat: 'The Plane of Earth, deep caverns',
    abilities: ['Earth glide', 'Siege monster', 'Damage resistance: nonmagical weapons'],
    languages: ['Terran'],
    senses: ['darkvision 60 ft.', 'tremorsense 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_fire_elemental', name: 'Fire Elemental', type: 'elemental', size: 'Large', alignment: 'neutral',
    cr: 5, ac: 13, hp: '102 (12d10 + 36)', speed: '50 ft.',
    description: 'A living bonfire in humanoid shape, setting the air itself alight as it surges toward its target.',
    lore: 'Fire elementals are hunger and destruction given will. They burn everything they touch and can pass through flames and forges unharmed. They are difficult to summon safely, for they resent confinement and will turn on careless masters.',
    tactics: 'Sets targets ablaze on touch. Moves through fire. Ignites flammable surroundings.',
    habitat: 'The Plane of Fire, volcanoes, forges',
    abilities: ['Touch burns', 'Fire form', 'Water vulnerability'],
    languages: ['Ignan'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_water_elemental', name: 'Water Elemental', type: 'elemental', size: 'Large', alignment: 'neutral',
    cr: 5, ac: 14, hp: '114 (12d10 + 48)', speed: '30 ft., swim 90 ft.',
    description: 'A cresting wave that refuses to fall, dragging and drowning everything in its path.',
    lore: 'Water elementals are the patient, crushing power of the deep. They drown foes, batter ships, and slip through any crack that admits water. In their element they are nearly unstoppable; out of it, they still crush and smother.',
    tactics: 'Whelm (grapple and drown). Douses fires. Slips through gaps. Fights from water when possible.',
    habitat: 'The Plane of Water, oceans, underground seas',
    abilities: ['Whelm', 'Water form', 'Amphibious'],
    languages: ['Aquan'],
    senses: ['darkvision 60 ft.', 'passive Perception 10'],
  },
  {
    id: 'odnd_djinni', name: 'Djinni', type: 'elemental (genie)', size: 'Large', alignment: 'chaotic good',
    cr: 11, ac: 17, hp: '161 (14d10 + 84)', speed: '30 ft., fly 90 ft.',
    description: 'A towering figure of wind and silk, its lower body a whirlwind, its eyes bright with ancient mischief.',
    lore: 'Djinn are noble genies of the air, proud and unpredictable. Some serve mortals who free them; others grant wishes with clever, unintended consequences. They love beauty, freedom, and the open sky, and despise being bound.',
    tactics: 'Whirlwind. Creates illusions and food. Grants wishes (with twists). Flies out of reach.',
    habitat: 'The Plane of Air, flying palaces, desert oases',
    abilities: ['Whirlwind', 'Innate air magic', 'Wish (limited)', 'Fly'],
    languages: ['Auran', 'Common'],
    senses: ['darkvision 120 ft.', 'passive Perception 13'],
  },
  {
    id: 'odnd_efreeti', name: 'Efreeti', type: 'elemental (genie)', size: 'Large', alignment: 'lawful evil',
    cr: 11, ac: 17, hp: '200 (16d10 + 112)', speed: '40 ft., fly 60 ft.',
    description: 'A horned genie of smoke and flame, bronze-skinned and cruel-eyed, a scimitar of fire in its hand.',
    lore: 'Efreet are the tyrant genies of the Plane of Fire, ruling cities of brass and enslaving lesser beings. They grant wishes only to those who bind them, and always seek to twist the bargain. Their pride is matched only by their cruelty.',
    tactics: 'Fire magic. Conjures flame walls. Grants wishes with betrayal. Fights with flaming scimitar.',
    habitat: 'The Plane of Fire, brass cities, volcanic lairs',
    abilities: ['Innate fire magic', 'Wish (limited)', 'Fly', 'Fire immunity'],
    languages: ['Ignan', 'Common'],
    senses: ['darkvision 120 ft.', 'passive Perception 14'],
  },
  {
    id: 'odnd_invisible_stalker', name: 'Invisible Stalker', type: 'elemental', size: 'Medium', alignment: 'neutral',
    cr: 6, ac: 14, hp: '104 (16d8 + 32)', speed: '50 ft., fly 50 ft. (hover)',
    description: 'An unseen presence of moving air, betrayed only by a faint shimmer and the pressure of its approach.',
    lore: 'Invisible stalkers are air elementals bound to hunt a single target until it is found and returned — or slain. They never rest, never forget, and cannot be reasoned with. Once set on a trail, they follow it across the world.',
    tactics: 'Invisible ambush. Relentless pursuit of its target. Slips through any barrier that admits air.',
    habitat: 'The Plane of Air, wherever its target flees',
    abilities: ['Invisibility', 'Faultless tracker', 'Fly', 'Damage resistance: nonmagical weapons'],
    languages: ['Auran', 'understands Common'],
    senses: ['darkvision 60 ft.', 'passive Perception 16'],
  },

  // ── Demons & devils (first appearances) ──
  {
    id: 'odnd_balrog_type_vi', name: 'Type VI Demon (Balor)', type: 'fiend (demon)', size: 'Huge', alignment: 'chaotic evil',
    cr: 19, ac: 19, hp: '262 (21d12 + 126)', speed: '40 ft., fly 80 ft.',
    description: 'A towering demon of shadow and fire, wreathed in flame, a whip of lightning in one hand and a jagged sword in the other.',
    lore: 'The Type VI demon — later called the balor — was the deadliest of the original demon types, a general of the Abyss whose name meant annihilation. It commands legions of lesser demons and leaves nothing but ash in its wake.',
    tactics: 'Lightning whip drags foes. Explodes in a death burst when slain. Commands lesser demons. Fear aura.',
    habitat: 'The Abyss',
    abilities: ['Death burst', 'Fear aura', 'Magic resistance', 'Whip and sword', 'Fly'],
    languages: ['Abyssal', 'telepathy 120 ft.'],
    senses: ['truesight 120 ft.', 'passive Perception 15'],
  },
  {
    id: 'odnd_hell_hound', name: 'Hell Hound', type: 'fiend', size: 'Medium', alignment: 'lawful evil',
    cr: 3, ac: 15, hp: '45 (7d8 + 14)', speed: '50 ft.',
    description: 'A black-furred hound with eyes like embers and breath that rolls out as a cone of fire.',
    lore: 'Hell hounds are the hunting beasts of the lower planes, bred by devils and fire giants to track and burn. They are fearless, tireless, and nearly impossible to shake once on a scent. Their howls carry for miles across the dark.',
    tactics: 'Fire breath. Relentless tracking. Fights in packs, surrounding prey.',
    habitat: 'The Nine Hells, volcanic wastes, fire giant lairs',
    abilities: ['Fire breath', 'Keen senses', 'Pack tactics', 'Fire immunity'],
    languages: ['understands Infernal'],
    senses: ['darkvision 60 ft.', 'passive Perception 15'],
  },
];
