/**
 * Pre-built dungeons.
 *
 * A hundred delves whose every floor is fixed: the layout, each monster's
 * tile, the boss in its hall. The data lives in `data/PrebuiltDungeons.ts`
 * (generated by tools/dungeons/build_prebuilt.py); this module is the
 * reader. `loadPrebuiltFloor` paints a floor into a TileMap and hands back
 * its rooms, and the placement lists say exactly who stands where. Pure.
 */

import { TileMap, TileType } from './TileMap';
import type { Room } from './DungeonGenerator';
import { MAP_HEIGHT, MAP_WIDTH } from '../engine/types';
import { PREBUILT_DUNGEONS } from '../data/PrebuiltDungeons';

export interface PrebuiltFloor {
  /** Where the encoded rows sit in the 72-square map. */
  x0: number;
  y0: number;
  /** Run-length rows: "3#4.3#" is three walls, four floors, three walls. */
  rows: string[];
  /** [x, y, width, height]; the first is the start room, the last the boss hall. */
  rooms: [number, number, number, number][];
  /** [template id, x, y] for every creature on the floor except the boss. */
  monsters: [string, number, number][];
  /** The boss, by template id, and its tile. */
  boss: [string, number, number];
}

export interface PrebuiltDungeon {
  id: string;
  name: string;
  themeId: string;
  style: string;
  description: string;
  floors: PrebuiltFloor[];
  /** The thing the dungeon is remembered for: a room on one floor made a particular way. */
  setPiece?: { floor: number; room: number; kind: string; hazard: string | null; line: string };
}

export const PREBUILT_BY_ID: ReadonlyMap<string, PrebuiltDungeon> = new Map(PREBUILT_DUNGEONS.map(d => [d.id, d]));

export function getPrebuilt(id: string | null | undefined): PrebuiltDungeon | undefined {
  return id ? PREBUILT_BY_ID.get(id) : undefined;
}

const CHAR_TILE: Record<string, TileType> = {
  ' ': TileType.Void,
  '.': TileType.Floor,
  '#': TileType.Wall,
  '+': TileType.Door,
  '>': TileType.StairsDown,
  '~': TileType.Water,
  'L': TileType.Lava,
};

/** Expand one run-length row into characters. */
export function decodeRow(row: string): string {
  let out = '';
  let count = '';
  for (const ch of row) {
    if (ch >= '0' && ch <= '9') { count += ch; continue; }
    const n = count ? parseInt(count, 10) : 1;
    out += ch.repeat(n);
    count = '';
  }
  return out;
}

/** Paint a floor into the map (which is cleared to void first) and return its rooms. */
export function loadPrebuiltFloor(map: TileMap, floor: PrebuiltFloor): Room[] {
  for (let y = 0; y < MAP_HEIGHT; y++) {
    for (let x = 0; x < MAP_WIDTH; x++) map.setTile(x, y, TileType.Void);
  }
  floor.rows.forEach((row, dy) => {
    const chars = decodeRow(row);
    for (let dx = 0; dx < chars.length; dx++) {
      const tile = CHAR_TILE[chars[dx]];
      if (tile !== undefined && tile !== TileType.Void) map.setTile(floor.x0 + dx, floor.y0 + dy, tile);
    }
  });
  return floor.rooms.map(([x, y, width, height]) => ({ x, y, width, height, cx: x + Math.floor(width / 2), cy: y + Math.floor(height / 2) }));
}

/**
 * Pick a pre-built dungeon for an entrance: one of the theme the land
 * chose, if any is still unused, else any unused one. `rng` in [0, 1).
 */
export function pickPrebuilt(themeId: string | undefined, used: ReadonlySet<string>, rng: () => number = Math.random): PrebuiltDungeon | undefined {
  const free = PREBUILT_DUNGEONS.filter(d => !used.has(d.id));
  if (free.length === 0) return undefined;
  const themed = themeId ? free.filter(d => d.themeId === themeId) : [];
  const pool = themed.length > 0 ? themed : free;
  return pool[Math.min(pool.length - 1, Math.floor(rng() * pool.length))];
}
